DROP PROCEDURE IF EXISTS update_all_ohclv(BIGINT, BIGINT);
DROP FUNCTION IF EXISTS get_ohclv(TEXT, TEXT, TIMESTAMP, TIMESTAMP, INTEGER);
DROP PROCEDURE IF EXISTS update_ohclv_1d(BIGINT, BIGINT);
DROP PROCEDURE IF EXISTS update_ohclv_1m(BIGINT, BIGINT);

DROP INDEX IF EXISTS idx_ohclv_1d_time;
DROP INDEX IF EXISTS idx_ohclv_1d_pool_time;
DROP INDEX IF EXISTS idx_ohclv_1m_time;
DROP INDEX IF EXISTS idx_ohclv_1m_pool_time;

DROP TABLE IF EXISTS ohclv_1d;
DROP TABLE IF EXISTS ohclv_1m;