// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/helper/reference/generate_ssvi_reference.py
// Source data: Block Scholes SSVI params backfill
// v2composite_svi_params_SSVI_B_BTC_20260201_20260630.parquet (BTC, 20-second
// publications). DO NOT EDIT BY HAND — regenerate with
//   python3 generate_ssvi_reference.py
//
// Independent true-math reference (Python stdlib math.log/sqrt/erf, NOT the contract)
// for Pricer.range_price on SSVI slices and the relaxed SVI bounds. Each `tolerance` is
// generate_pricing_reference.up_error_budget at that strike plus a 2-unit cushion.
// `points` quote each slice's real forward (no `ln` error); `unit_forward_points`
// quote strikes around the smile with the same shape seeded at a forward of 1.0.
// See the generator header for the selection and derivation.
//
// Provenance (publication -> expiry):
//   [0] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  smallest sigma in the backfill
//   [1] 2026-04-04T01:22:40.000Z -> 2026-04-04T01:23:00Z  most negative a against the SVI increment's minimum, one minute out
//   [2] 2026-06-19T23:59:40.000Z -> 2026-06-20T00:00:00Z  largest at-the-forward miss by the former 1e9 root, one minute out
//   [3] 2026-05-09T01:17:00.000Z -> 2026-05-09T01:19:00Z  largest at-the-forward miss by the former 1e9 root, one to five minutes out
//   [4] 2026-05-09T01:17:00.000Z -> 2026-05-09T01:25:00Z  largest at-the-forward miss by the former 1e9 root, five minutes to an hour out
//   [5] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: slice [0], sigma at the floor, vertex at the forward
//   [6] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: slice [0], sigma at the floor, forward one width from the vertex
//   [7] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: slice [0], sigma at the floor, forward in the wing
//   [8] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: negative a past the former |a| <= 100 cap
//   [9] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: positive a past the former |a| <= 100 cap
//   [10] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: true total variance under one raw unit at the forward (RP-20)
//   [11] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: rho = -1 with one raw unit of positive a
//   [12] 2026-04-03T22:29:40.000Z -> 2026-04-03T22:30:00Z  synthetic: total variance at the forward exactly one raw unit
#[test_only]
module deepbook_predict::pricing_ssvi_reference_data;

use deepbook_predict::constants;

const ENoSuchSlice: u64 = 0;

/// One independent reference point: Pricer.range_price(lower, higher).probability()
/// must be within `tolerance` units of the true-math `reference`.
public struct RefPoint has copy, drop {
    lower: u64,
    higher: u64,
    reference: u64,
    tolerance: u64,
}

public fun lower(p: &RefPoint): u64 { p.lower }

public fun higher(p: &RefPoint): u64 { p.higher }

public fun reference(p: &RefPoint): u64 { p.reference }

public fun tolerance(p: &RefPoint): u64 { p.tolerance }

fun pt(lower: u64, higher: u64, reference: u64, tolerance: u64): RefPoint {
    RefPoint { lower, higher, reference, tolerance }
}

/// Number of slices.
public fun slice_count(): u64 { 13 }

// === Slice indices ===

/// Smallest sigma in the backfill.
public fun smallest_sigma_slice(): u64 { 0 }

/// Most negative a against the SVI increment's minimum, one minute out.
public fun negative_a_slice(): u64 { 1 }

/// Largest at-the-forward miss by the former 1e9 root, one minute out.
public fun one_minute_root_miss_slice(): u64 { 2 }

/// Largest at-the-forward miss by the former 1e9 root, one to five minutes out.
public fun one_to_five_minute_root_miss_slice(): u64 { 3 }

/// Largest at-the-forward miss by the former 1e9 root, five minutes to an hour out.
public fun sub_hour_root_miss_slice(): u64 { 4 }

/// Synthetic: slice [0], sigma at the floor, vertex at the forward.
public fun floor_vertex_slice(): u64 { 5 }

/// Synthetic: slice [0], sigma at the floor, forward one width from the vertex.
public fun floor_one_width_slice(): u64 { 6 }

/// Synthetic: slice [0], sigma at the floor, forward in the wing.
public fun floor_wing_slice(): u64 { 7 }

/// Synthetic: negative a past the former |a| <= 100 cap.
public fun negative_a_past_cap_slice(): u64 { 8 }

/// Synthetic: positive a past the former |a| <= 100 cap.
public fun positive_a_past_cap_slice(): u64 { 9 }

/// Synthetic: true total variance under one raw unit at the forward (RP-20).
public fun sub_unit_variance_slice(): u64 { 10 }

/// Synthetic: rho = -1 with one raw unit of positive a.
public fun unit_rho_slice(): u64 { 11 }

/// Synthetic: total variance at the forward exactly one raw unit.
public fun one_raw_unit_variance_slice(): u64 { 12 }

/// Spot and forward of the unit-forward seeding (1.0 at 1e9).
public fun unit_forward(): u64 { 1_000_000_000 }

/// Block Scholes spot (1e9), also seeded as the Pyth spot.
public fun spot(s: u64): u64 {
    if (s == 0) {
        66_875_412_510_818
    } else if (s == 1) {
        66_857_051_213_361
    } else if (s == 2) {
        63_488_113_580_056
    } else if (s == 3) {
        80_297_178_526_706
    } else if (s == 4) {
        80_297_178_526_706
    } else if (s == 5) {
        66_875_412_510_818
    } else if (s == 6) {
        66_875_412_510_818
    } else if (s == 7) {
        66_875_412_510_818
    } else if (s == 8) {
        66_875_412_510_818
    } else if (s == 9) {
        66_875_412_510_818
    } else if (s == 10) {
        66_875_412_510_818
    } else if (s == 11) {
        66_875_412_510_818
    } else if (s == 12) {
        66_875_412_510_818
    } else {
        abort ENoSuchSlice
    }
}

/// Block Scholes forward (1e9); the live forward.
public fun forward(s: u64): u64 {
    if (s == 0) {
        66_875_410_000_000
    } else if (s == 1) {
        66_857_050_000_000
    } else if (s == 2) {
        63_488_110_000_000
    } else if (s == 3) {
        80_297_180_000_000
    } else if (s == 4) {
        80_297_170_000_000
    } else if (s == 5) {
        66_875_410_000_000
    } else if (s == 6) {
        66_875_410_000_000
    } else if (s == 7) {
        66_875_410_000_000
    } else if (s == 8) {
        66_875_410_000_000
    } else if (s == 9) {
        66_875_410_000_000
    } else if (s == 10) {
        66_875_410_000_000
    } else if (s == 11) {
        66_875_410_000_000
    } else if (s == 12) {
        66_875_410_000_000
    } else {
        abort ENoSuchSlice
    }
}

/// SVI `a` magnitude (1e9).
public fun svi_a_magnitude(s: u64): u64 {
    if (s == 0) {
        4
    } else if (s == 1) {
        6
    } else if (s == 2) {
        5
    } else if (s == 3) {
        29
    } else if (s == 4) {
        104
    } else if (s == 5) {
        4
    } else if (s == 6) {
        4
    } else if (s == 7) {
        4
    } else if (s == 8) {
        150_000_000_000
    } else if (s == 9) {
        101_000_000_000
    } else if (s == 10) {
        6_504_462
    } else if (s == 11) {
        1
    } else if (s == 12) {
        2
    } else {
        abort ENoSuchSlice
    }
}

/// Sign flag for SVI `a` (true == negative).
public fun svi_a_is_negative(s: u64): bool {
    if (s == 0) {
        false
    } else if (s == 1) {
        true
    } else if (s == 2) {
        false
    } else if (s == 3) {
        true
    } else if (s == 4) {
        true
    } else if (s == 5) {
        false
    } else if (s == 6) {
        false
    } else if (s == 7) {
        false
    } else if (s == 8) {
        true
    } else if (s == 9) {
        false
    } else if (s == 10) {
        true
    } else if (s == 11) {
        false
    } else if (s == 12) {
        true
    } else {
        abort ENoSuchSlice
    }
}

/// SVI `b` (1e9).
public fun svi_b(s: u64): u64 {
    if (s == 0) {
        93_990
    } else if (s == 1) {
        97_835
    } else if (s == 2) {
        84_648
    } else if (s == 3) {
        210_365
    } else if (s == 4) {
        422_591
    } else if (s == 5) {
        93_990
    } else if (s == 6) {
        93_990
    } else if (s == 7) {
        93_990
    } else if (s == 8) {
        1_600_000_000
    } else if (s == 9) {
        93_990
    } else if (s == 10) {
        269_451
    } else if (s == 11) {
        100_000
    } else if (s == 12) {
        1_000
    } else {
        abort ENoSuchSlice
    }
}

/// SVI `rho` magnitude (1e9).
public fun svi_rho_magnitude(s: u64): u64 {
    if (s == 0) {
        402_637
    } else if (s == 1) {
        459_430
    } else if (s == 2) {
        16_036_734
    } else if (s == 3) {
        21_651_600
    } else if (s == 4) {
        32_774_861
    } else if (s == 5) {
        402_637
    } else if (s == 6) {
        402_637
    } else if (s == 7) {
        402_637
    } else if (s == 8) {
        200_000_000
    } else if (s == 9) {
        402_637
    } else if (s == 10) {
        549_040_989
    } else if (s == 11) {
        1_000_000_000
    } else if (s == 12) {
        800_000_000
    } else {
        abort ENoSuchSlice
    }
}

/// Sign flag for SVI `rho` (true == negative).
public fun svi_rho_is_negative(s: u64): bool {
    if (s == 0) {
        false
    } else if (s == 1) {
        false
    } else if (s == 2) {
        true
    } else if (s == 3) {
        false
    } else if (s == 4) {
        false
    } else if (s == 5) {
        false
    } else if (s == 6) {
        false
    } else if (s == 7) {
        false
    } else if (s == 8) {
        true
    } else if (s == 9) {
        false
    } else if (s == 10) {
        false
    } else if (s == 11) {
        true
    } else if (s == 12) {
        false
    } else {
        abort ENoSuchSlice
    }
}

/// SVI `m` magnitude (1e9).
public fun svi_m_magnitude(s: u64): u64 {
    if (s == 0) {
        19
    } else if (s == 1) {
        224
    } else if (s == 2) {
        1_001
    } else if (s == 3) {
        13_884
    } else if (s == 4) {
        60_077
    } else if (s == 5) {
        0
    } else if (s == 6) {
        10_000
    } else if (s == 7) {
        100_000
    } else if (s == 8) {
        100_000_000
    } else if (s == 9) {
        19
    } else if (s == 10) {
        18_973_018_796
    } else if (s == 11) {
        0
    } else if (s == 12) {
        6_666_634
    } else {
        abort ENoSuchSlice
    }
}

/// Sign flag for SVI `m` (true == negative).
public fun svi_m_is_negative(s: u64): bool {
    if (s == 0) {
        true
    } else if (s == 1) {
        false
    } else if (s == 2) {
        false
    } else if (s == 3) {
        true
    } else if (s == 4) {
        true
    } else if (s == 5) {
        false
    } else if (s == 6) {
        false
    } else if (s == 7) {
        true
    } else if (s == 8) {
        false
    } else if (s == 9) {
        true
    } else if (s == 10) {
        false
    } else if (s == 11) {
        false
    } else if (s == 12) {
        false
    } else {
        abort ENoSuchSlice
    }
}

/// SVI `sigma` (1e9).
public fun svi_sigma(s: u64): u64 {
    if (s == 0) {
        47_407
    } else if (s == 1) {
        79_465
    } else if (s == 2) {
        62_432
    } else if (s == 3) {
        246_698
    } else if (s == 4) {
        498_823
    } else if (s == 5) {
        10_000
    } else if (s == 6) {
        10_000
    } else if (s == 7) {
        10_000
    } else if (s == 8) {
        100_000_000_000
    } else if (s == 9) {
        47_407
    } else if (s == 10) {
        28_882_292_262
    } else if (s == 11) {
        1_000_000
    } else if (s == 12) {
        5_000_000
    } else {
        abort ENoSuchSlice
    }
}

/// Reference points for slice `s` at its real forward: the UP digital `(strike, +inf]`.
public fun points(s: u64): vector<RefPoint> {
    if (s == 0) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 499_817_852, 2_199),
        ]
    } else if (s == 1) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_857_050_000_000, constants::pos_inf!(), 501_084_653, 4_863),
        ]
    } else if (s == 2) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(63_488_110_000_000, constants::pos_inf!(), 505_318_407, 2_131),
        ]
    } else if (s == 3) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(80_297_180_000_000, constants::pos_inf!(), 478_451_434, 1_742),
        ]
    } else if (s == 4) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(80_297_170_000_000, constants::pos_inf!(), 461_063_702, 962),
        ]
    } else if (s == 5) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 499_878_577, 2_866),
        ]
    } else if (s == 6) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 681_488_093, 21_309),
        ]
    } else if (s == 7) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 339_052_785, 5_877),
        ]
    } else if (s == 8) {
        vector[
            // at the forward, k=+0.000e+00, d2=-1.584
            pt(66_875_410_000_000, constants::pos_inf!(), 62_413_592, 26),
        ]
    } else if (s == 9) {
        vector[
            // at the forward, k=+0.000e+00, d2=-5.025
            pt(66_875_410_000_000, constants::pos_inf!(), 252, 24),
        ]
    } else if (s == 10) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 499_993_692, 6_336),
        ]
    } else if (s == 11) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 562_701_874, 919),
        ]
    } else if (s == 12) {
        vector[
            // at the forward, k=+0.000e+00, d2=-0.000
            pt(66_875_410_000_000, constants::pos_inf!(), 499_993_683, 6_333),
        ]
    } else {
        abort ENoSuchSlice
    }
}

/// Reference points for slice `s` seeded at spot == forward == `unit_forward()`.
public fun unit_forward_points(s: u64): vector<RefPoint> {
    if (s == 0) {
        vector[
            // vertex, k=-1.900e-08, d2=+0.000
            pt(999_999_981, constants::pos_inf!(), 499_981_996, 19_475),
            // d2 target +2, k=-4.167e-04, d2=+2.000
            pt(999_583_426, constants::pos_inf!(), 989_346_713, 2_563),
            // d2 target +1, k=-1.306e-04, d2=+1.000
            pt(999_869_420, constants::pos_inf!(), 923_165_075, 15_269),
            // d2 target -1, k=+1.306e-04, d2=-1.000
            pt(1_000_130_648, constants::pos_inf!(), 76_800_796, 15_259),
            // d2 target -2, k=+4.169e-04, d2=-2.000
            pt(1_000_416_975, constants::pos_inf!(), 10_651_164, 2_560),
        ]
    } else if (s == 1) {
        vector[
            // vertex, k=+2.240e-07, d2=-0.005
            pt(1_000_000_224, constants::pos_inf!(), 497_657_354, 35_545),
            // d2 target +2, k=-3.299e-04, d2=+2.000
            pt(999_670_167, constants::pos_inf!(), 992_810_617, 3_848),
            // d2 target +1, k=-6.243e-05, d2=+1.000
            pt(999_937_568, constants::pos_inf!(), 958_648_393, 45_482),
            // d2 target -1, k=+6.209e-05, d2=-1.000
            pt(1_000_062_094, constants::pos_inf!(), 41_462_880, 45_773),
            // d2 target -2, k=+3.296e-04, d2=-2.000
            pt(1_000_329_692, constants::pos_inf!(), 7_165_936, 3_853),
        ]
    } else if (s == 2) {
        vector[
            // vertex, k=+1.001e-06, d2=-0.010
            pt(1_000_001_001, constants::pos_inf!(), 498_711_993, 15_313),
            // d2 target +2, k=-3.991e-04, d2=+2.000
            pt(999_600_940, constants::pos_inf!(), 988_747_436, 2_583),
            // d2 target +1, k=-1.330e-04, d2=+1.000
            pt(999_866_962, constants::pos_inf!(), 912_360_832, 13_633),
            // d2 target -1, k=+1.303e-04, d2=-1.000
            pt(1_000_130_299, constants::pos_inf!(), 89_137_624, 13_950),
            // d2 target -2, k=+3.882e-04, d2=-2.000
            pt(1_000_388_229, constants::pos_inf!(), 11_315_452, 2_673),
        ]
    } else if (s == 3) {
        vector[
            // vertex, k=-1.388e-05, d2=+0.092
            pt(999_986_116, constants::pos_inf!(), 530_544_826, 9_519),
            // d2 target +2, k=-6.921e-04, d2=+2.000
            pt(999_308_143, constants::pos_inf!(), 992_318_019, 1_859),
            // d2 target +1, k=-1.817e-04, d2=+1.000
            pt(999_818_347, constants::pos_inf!(), 917_105_118, 11_601),
            // d2 target -1, k=+2.025e-04, d2=-1.000
            pt(1_000_202_529, constants::pos_inf!(), 73_066_961, 10_549),
            // d2 target -2, k=+7.655e-04, d2=-2.000
            pt(1_000_765_775, constants::pos_inf!(), 8_284_551, 1_604),
        ]
    } else if (s == 4) {
        vector[
            // vertex, k=-6.008e-05, d2=+0.184
            pt(999_939_925, constants::pos_inf!(), 564_551_286, 4_639),
            // d2 target +2, k=-1.374e-03, d2=+2.000
            pt(998_627_223, constants::pos_inf!(), 992_235_311, 974),
            // d2 target +1, k=-3.757e-04, d2=+1.000
            pt(999_624_403, constants::pos_inf!(), 909_661_926, 5_435),
            // d2 target -1, k=+4.534e-04, d2=-1.000
            pt(1_000_453_454, constants::pos_inf!(), 74_091_011, 4_615),
            // d2 target -2, k=+1.629e-03, d2=-2.000
            pt(1_001_630_273, constants::pos_inf!(), 8_860_818, 763),
        ]
    } else if (s == 5) {
        vector[
            // one width below the vertex, k=-1.000e-05, d2=+0.137
            pt(999_990_000, constants::pos_inf!(), 734_274_700, 73_386),
            // one width above the vertex, k=+1.000e-05, d2=-0.137
            pt(1_000_010_000, constants::pos_inf!(), 265_511_012, 73_389),
            // ten widths above the vertex, k=+1.000e-04, d2=-0.862
            pt(1_000_100_005, constants::pos_inf!(), 83_297_804, 20_722),
            // d2 target +2, k=-4.146e-04, d2=+2.000
            pt(999_585_529, constants::pos_inf!(), 989_483_108, 2_592),
            // d2 target +1, k=-1.260e-04, d2=+1.000
            pt(999_874_000, constants::pos_inf!(), 931_275_216, 16_805),
            // d2 target -1, k=+1.260e-04, d2=-1.000
            pt(1_000_126_051, constants::pos_inf!(), 68_688_172, 16_797),
            // d2 target -2, k=+4.148e-04, d2=-2.000
            pt(1_000_414_841, constants::pos_inf!(), 10_514_162, 2_590),
        ]
    } else if (s == 6) {
        vector[
            // vertex, k=+1.000e-05, d2=-0.142
            pt(1_000_010_000, constants::pos_inf!(), 443_311_203, 68_789),
            // one width above the vertex, k=+2.000e-05, d2=-0.274
            pt(1_000_020_000, constants::pos_inf!(), 217_044_281, 74_774),
            // ten widths above the vertex, k=+1.100e-04, d2=-0.949
            pt(1_000_110_006, constants::pos_inf!(), 68_800_953, 20_186),
            // d2 target +2, k=-4.227e-04, d2=+2.000
            pt(999_577_391, constants::pos_inf!(), 989_247_700, 2_510),
            // d2 target +1, k=-1.317e-04, d2=+1.000
            pt(999_868_288, constants::pos_inf!(), 927_431_085, 15_447),
            // d2 target -1, k=+1.199e-04, d2=-1.000
            pt(1_000_119_898, constants::pos_inf!(), 64_164_451, 18_519),
            // d2 target -2, k=+4.063e-04, d2=-2.000
            pt(1_000_406_391, constants::pos_inf!(), 10_260_205, 2_680),
        ]
    } else if (s == 7) {
        vector[
            // vertex, k=-1.000e-04, d2=+1.423
            pt(999_900_005, constants::pos_inf!(), 922_557_402, 31_557),
            // one width below the vertex, k=-1.100e-04, d2=+1.507
            pt(999_890_006, constants::pos_inf!(), 992_396_548, 39_588),
            // one width above the vertex, k=-9.000e-05, d2=+1.233
            pt(999_910_004, constants::pos_inf!(), 806_184_811, 51_899),
            // d2 target +2, k=-3.055e-04, d2=+2.000
            pt(999_694_560, constants::pos_inf!(), 993_835_705, 4_419),
            // d2 target +1, k=-7.878e-05, d2=+1.000
            pt(999_921_224, constants::pos_inf!(), 710_706_232, 49_942),
            // d2 target -1, k=+1.720e-04, d2=-1.000
            pt(1_000_172_030, constants::pos_inf!(), 92_571_724, 9_646),
            // d2 target -2, k=+4.863e-04, d2=-2.000
            pt(1_000_486_468, constants::pos_inf!(), 12_314_012, 2_003),
        ]
    } else if (s == 8) {
        vector[
            // vertex, k=+1.000e-01, d2=-1.613
            pt(1_105_170_918, constants::pos_inf!(), 58_896_476, 27),
            // d2 target +2, k=-1.759e+01, d2=+1.999
            pt(23, constants::pos_inf!(), 981_009_849, 64),
            // d2 target +1, k=-1.112e+01, d2=+1.000
            pt(14_869, constants::pos_inf!(), 857_126_878, 127),
            // d2 target -1, k=-2.093e+00, d2=-1.000
            pt(123_332_701, constants::pos_inf!(), 171_763_667, 45),
            // d2 target -2, k=+1.397e+00, d2=-2.000
            pt(4_043_282_742, constants::pos_inf!(), 25_357_631, 29),
        ]
    } else if (s == 9) {
        vector[
            // vertex, k=-1.900e-08, d2=-5.025
            pt(999_999_981, constants::pos_inf!(), 252, 24),
            // k = -2.0, k=-2.000e+00, d2=-4.826
            pt(135_335_283, constants::pos_inf!(), 697, 24),
            // k = -1.0, k=-1.000e+00, d2=-4.925
            pt(367_879_441, constants::pos_inf!(), 421, 24),
            // k = +1.0, k=+1.000e+00, d2=-5.124
            pt(2_718_281_828, constants::pos_inf!(), 149, 24),
            // k = +2.0, k=+2.000e+00, d2=-5.224
            pt(7_389_056_099, constants::pos_inf!(), 88, 24),
        ]
    } else if (s == 10) {
        vector[]
    } else if (s == 11) {
        vector[
            // d2 target +2, k=-9.768e-04, d2=+2.000
            pt(999_023_695, constants::pos_inf!(), 986_640_772, 909),
            // d2 target +1, k=-3.826e-04, d2=+1.000
            pt(999_617_469, constants::pos_inf!(), 884_274_337, 3_329),
            // d2 target -1, k=+2.775e-04, d2=-1.000
            pt(1_000_277_541, constants::pos_inf!(), 190_590_333, 4_573),
            // d2 target -2, k=+5.010e-04, d2=-2.000
            pt(1_000_501_093, constants::pos_inf!(), 28_699_853, 1_795),
        ]
    } else if (s == 12) {
        vector[
            // vertex, k=+6.667e-03, d2=-121.716
            pt(1_006_688_905, constants::pos_inf!(), 0, 24),
            // d2 target +2, k=-6.325e-05, d2=+2.000
            pt(999_936_753, constants::pos_inf!(), 977_252_577, 8_000),
            // d2 target +1, k=-3.162e-05, d2=+1.000
            pt(999_968_377, constants::pos_inf!(), 841_349_053, 27_461),
            // d2 target -1, k=+3.162e-05, d2=-1.000
            pt(1_000_031_623, constants::pos_inf!(), 158_650_915, 27_460),
            // d2 target -2, k=+6.325e-05, d2=-2.000
            pt(1_000_063_250, constants::pos_inf!(), 22_747_444, 7_999),
        ]
    } else {
        abort ENoSuchSlice
    }
}

// === Roll-down ===

/// Slice the roll-down case seeds, priced with 0.25 of its anchored horizon left.
public fun rolled_slice(): u64 { 2 }

/// Expiry of the roll-down market; the tuple is seeded at `test_constants::now_ms`.
public fun rolled_expiry_ms(): u64 { 180_000 }

/// Clock at which the roll-down case is priced.
public fun rolled_priced_at_ms(): u64 { 165_000 }

/// True UP digital at the forward with `a` and `b` rolled down.
public fun rolled_up_at_forward(): u64 { 502_659_203 }

/// Absolute precision budget for `rolled_up_at_forward` (units @1e9).
public fun rolled_budget(): u64 { 4_054 }
