// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/helper/reference/generate_pricing_reference.py
// Source data: packages/predict/simulations/data/scenario_dataset.csv (real on-chain
// Block Scholes SVI, one market, 2026-05-27). DO NOT EDIT BY HAND — regenerate with
//   python3 generate_pricing_reference.py
//
// Independent true-math reference (Python stdlib math.log/sqrt/erf, NOT the contract
// and NOT python_replay's fixed-point pricer) for Pricer.range_price.
// Each point's `tolerance` is the analytic worst-case fixed-point error of UP=Phi(d2),
// propagated from math.move's documented per-primitive budgets at the TRUE values; see
// the generator header for the full derivation. The forward priced is the fresh-Pyth
// round-trip mul(spot, div(forward, spot)).
//
// Worst-case per-endpoint budget across all scenarios/strikes: 2_401 units (@1e9).
// Dominated by the small-variance scenario at |d2|~1: d2=-(k+w/2)/sqrt(w) is
// ill-conditioned in w (w^-3/2), so a 1-ULP variance rounding moves the quote ~1e-6.
//
// Provenance (svi_event_digest @ svi_timestamp, sqrt(w_atm)):
//   [0] 5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9  2026-05-27 08:00:18  sqrt_w_atm=0.017067
//   [1] H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59  2026-05-27 20:04:03  sqrt_w_atm=0.010893
//   [2] 357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9  2026-05-28 02:03:03  sqrt_w_atm=0.008383
#[test_only]
module deepbook_predict::pricing_reference_data;

use deepbook_predict::constants;

const ENoSuchScenario: u64 = 0;

/// One independent reference point: Pricer.range_price(lower, higher)
/// must be within `tolerance` units of the true-math `reference`.
public struct RefPoint has copy, drop {
    lower: u64,
    higher: u64,
    reference: u64,
    tolerance: u64,
}

public fun lower(p: &RefPoint): u64 { p.lower }

public fun higher(p: &RefPoint): u64 { p.higher }

public fun reference(p: &RefPoint): u64 { p.reference }

public fun tolerance(p: &RefPoint): u64 { p.tolerance }

fun pt(lower: u64, higher: u64, reference: u64, tolerance: u64): RefPoint {
    RefPoint { lower, higher, reference, tolerance }
}

/// Number of real-data scenarios.
public fun scenario_count(): u64 { 3 }

/// Worst-case per-endpoint precision budget (units @1e9) over all scenarios/strikes.
public fun worst_case_budget(): u64 { 2_401 }

/// Scenario spot seeded into the Propbook fixtures.
public fun creation_spot(s: u64): u64 { spot(s) }

/// Market tick size used by every scenario.
public fun tick_size(_s: u64): u64 { 1_000_000_000 }

/// Real Block Scholes spot (1e9 fixed-point) seeded into the oracle.
public fun spot(s: u64): u64 {
    if (s == 0) {
        75_852_009_440_344
    } else if (s == 1) {
        75_041_662_630_739
    } else if (s == 2) {
        74_212_635_061_019
    } else {
        abort ENoSuchScenario
    }
}

/// Real Block Scholes forward (1e9) seeded into the oracle (pushed forward).
public fun forward(s: u64): u64 {
    if (s == 0) {
        75_799_394_374_445
    } else if (s == 1) {
        75_044_761_049_821
    } else if (s == 2) {
        74_212_629_180_749
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `a` (1e9) seeded through the Block Scholes surface update.
public fun svi_a(s: u64): u64 {
    if (s == 0) {
        171_736
    } else if (s == 1) {
        99_272
    } else if (s == 2) {
        54_831
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `b` (1e9) seeded through the Block Scholes surface update.
public fun svi_b(s: u64): u64 {
    if (s == 0) {
        7_449_196
    } else if (s == 1) {
        3_466_091
    } else if (s == 2) {
        2_366_211
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `sigma` (1e9) seeded through the Block Scholes surface update.
public fun svi_sigma(s: u64): u64 {
    if (s == 0) {
        15_731_214
    } else if (s == 1) {
        6_351_738
    } else if (s == 2) {
        5_354_101
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `rho` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_rho_magnitude(s: u64): u64 {
    if (s == 0) {
        243_059_022
    } else if (s == 1) {
        475_372_427
    } else if (s == 2) {
        298_114_517
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `rho` (true == negative).
public fun svi_rho_is_negative(s: u64): bool {
    if (s == 0) {
        true
    } else if (s == 1) {
        true
    } else if (s == 2) {
        true
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `m` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_m_magnitude(s: u64): u64 {
    if (s == 0) {
        1_133_202
    } else if (s == 1) {
        3_647_706
    } else if (s == 2) {
        2_324_961
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `m` (true == negative).
public fun svi_m_is_negative(s: u64): bool {
    if (s == 0) {
        false
    } else if (s == 1) {
        true
    } else if (s == 2) {
        false
    } else {
        abort ENoSuchScenario
    }
}

/// Reference points for scenario `s` (lower, higher, true-math reference, tolerance).
public fun points(s: u64): vector<RefPoint> {
    if (s == 0) {
        vector[
            // d2~+3.0 UP(K)=Phi(d2)
            pt(68_488_000_000_000, constants::pos_inf!(), 998_650_400, 32),
            // d2~+2.0 UP(K)=Phi(d2)
            pt(71_901_000_000_000, constants::pos_inf!(), 977_251_761, 139),
            // d2~+1.0 UP(K)=Phi(d2)
            pt(74_265_000_000_000, constants::pos_inf!(), 841_378_954, 489),
            // d2~+0.5 UP(K)=Phi(d2)
            pt(75_100_000_000_000, constants::pos_inf!(), 691_591_293, 492),
            // d2~+0.0 UP(K)=Phi(d2)
            pt(75_788_000_000_000, constants::pos_inf!(), 500_105_501, 99),
            // d2~-0.5 UP(K)=Phi(d2)
            pt(76_433_000_000_000, constants::pos_inf!(), 308_762_488, 533),
            // d2~-1.0 UP(K)=Phi(d2)
            pt(77_136_000_000_000, constants::pos_inf!(), 158_705_775, 618),
            // d2~-2.0 UP(K)=Phi(d2)
            pt(78_942_000_000_000, constants::pos_inf!(), 22_760_736, 204),
            // d2~-3.0 UP(K)=Phi(d2)
            pt(81_484_000_000_000, constants::pos_inf!(), 1_351_185, 38),
            // clamp wing d2~+8
            pt(40_875_000_000_000, constants::pos_inf!(), 1_000_000_000, 2),
            // clamp wing d2~-8
            pt(111_541_000_000_000, constants::pos_inf!(), 0, 2),
            // (-inf, K_atm] = 1 - Phi(d2)
            pt(constants::neg_inf!(), 75_788_000_000_000, 499_894_499, 99),
            // (K@d2=+1, K@d2=-1] = Phi(+1)-Phi(-1)
            pt(74_265_000_000_000, 77_136_000_000_000, 682_673_179, 1_104),
        ]
    } else if (s == 1) {
        vector[
            // d2~+3.0 UP(K)=Phi(d2)
            pt(70_751_000_000_000, constants::pos_inf!(), 998_650_570, 44),
            // d2~+2.0 UP(K)=Phi(d2)
            pt(72_731_000_000_000, constants::pos_inf!(), 977_255_903, 307),
            // d2~+1.0 UP(K)=Phi(d2)
            pt(74_122_000_000_000, constants::pos_inf!(), 841_472_175, 1_205),
            // d2~+0.5 UP(K)=Phi(d2)
            pt(74_620_000_000_000, constants::pos_inf!(), 691_680_691, 1_234),
            // d2~+0.0 UP(K)=Phi(d2)
            pt(75_040_000_000_000, constants::pos_inf!(), 500_150_964, 143),
            // d2~-0.5 UP(K)=Phi(d2)
            pt(75_457_000_000_000, constants::pos_inf!(), 308_555_858, 1_068),
            // d2~-1.0 UP(K)=Phi(d2)
            pt(75_903_000_000_000, constants::pos_inf!(), 158_879_149, 1_247),
            // d2~-2.0 UP(K)=Phi(d2)
            pt(76_919_000_000_000, constants::pos_inf!(), 22_794_161, 456),
            // d2~-3.0 UP(K)=Phi(d2)
            pt(78_125_000_000_000, constants::pos_inf!(), 1_351_430, 67),
            // clamp wing d2~+8
            pt(53_193_000_000_000, constants::pos_inf!(), 1_000_000_000, 2),
            // clamp wing d2~-8
            pt(87_962_000_000_000, constants::pos_inf!(), 0, 2),
            // (-inf, K_atm] = 1 - Phi(d2)
            pt(constants::neg_inf!(), 75_040_000_000_000, 499_849_036, 143),
            // (K@d2=+1, K@d2=-1] = Phi(+1)-Phi(-1)
            pt(74_122_000_000_000, 75_903_000_000_000, 682_593_027, 2_450),
        ]
    } else if (s == 2) {
        vector[
            // d2~+3.0 UP(K)=Phi(d2)
            pt(71_198_000_000_000, constants::pos_inf!(), 998_653_015, 63),
            // d2~+2.0 UP(K)=Phi(d2)
            pt(72_504_000_000_000, constants::pos_inf!(), 977_259_630, 501),
            // d2~+1.0 UP(K)=Phi(d2)
            pt(73_490_000_000_000, constants::pos_inf!(), 841_495_316, 1_672),
            // d2~+0.5 UP(K)=Phi(d2)
            pt(73_878_000_000_000, constants::pos_inf!(), 691_495_970, 1_592),
            // d2~+0.0 UP(K)=Phi(d2)
            pt(74_210_000_000_000, constants::pos_inf!(), 500_012_216, 176),
            // d2~-0.5 UP(K)=Phi(d2)
            pt(74_514_000_000_000, constants::pos_inf!(), 308_719_128, 2_016),
            // d2~-1.0 UP(K)=Phi(d2)
            pt(74_831_000_000_000, constants::pos_inf!(), 158_940_840, 2_401),
            // d2~-2.0 UP(K)=Phi(d2)
            pt(75_576_000_000_000, constants::pos_inf!(), 22_784_057, 807),
            // d2~-3.0 UP(K)=Phi(d2)
            pt(76_497_000_000_000, constants::pos_inf!(), 1_353_149, 98),
            // clamp wing d2~+8
            pt(59_811_000_000_000, constants::pos_inf!(), 1_000_000_000, 2),
            // clamp wing d2~-8
            pt(84_603_000_000_000, constants::pos_inf!(), 0, 2),
            // (-inf, K_atm] = 1 - Phi(d2)
            pt(constants::neg_inf!(), 74_210_000_000_000, 499_987_784, 176),
            // (K@d2=+1, K@d2=-1] = Phi(+1)-Phi(-1)
            pt(73_490_000_000_000, 74_831_000_000_000, 682_554_476, 4_070),
        ]
    } else {
        abort ENoSuchScenario
    }
}

/// Provenance: svi_event_digest of the source CSV row for scenario `s`.
public fun svi_event_digest(s: u64): vector<u8> {
    if (s == 0) {
        b"5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9"
    } else if (s == 1) {
        b"H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59"
    } else if (s == 2) {
        b"357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9"
    } else {
        abort ENoSuchScenario
    }
}
