// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/helper/reference/generate_pricing_reference.py
// Source data: packages/predict/simulations/data/scenario_dataset.csv (real on-chain
// Block Scholes SVI, one market, 2026-05-27). DO NOT EDIT BY HAND — regenerate with
//   python3 generate_pricing_reference.py
//
// Independent true-math reference (Python stdlib math.log/sqrt/erf, NOT the contract
// and NOT python_replay's fixed-point pricer) for Pricer.range_price.
// Each point's `tolerance` is the analytic worst-case fixed-point error of the
// skew-adjusted UP=N(d2)-phi(d2)*w'(k)/(2*sqrt(w)),
// propagated from math.move's documented per-primitive budgets at the TRUE values; see
// the generator header for the full derivation. The forward priced is the fresh-Pyth
// round-trip mul(spot, div(forward, spot)).
//
// `baseline_center` is the exact scalar output observed at parent commit 8046d0e6717efe5cad7eea3f053e7e6b60584a79.
// It detects value drift only; the independent reference + tolerance above decides correctness.
//
// Worst-case per-endpoint budget across all scenarios/strikes: 3_129 units (@1e9).
// Dominated by the small-variance scenario at |d2|~1: d2=-(k+w/2)/sqrt(w)
// and the skew term's 1/sqrt(w) denominator amplify fixed-point variance / slope dust.
//
// Provenance (svi_event_digest @ svi_timestamp, sqrt(w_atm)):
//   [0] 5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9  2026-05-27 08:00:18  sqrt_w_atm=0.017067
//   [1] H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59  2026-05-27 20:04:03  sqrt_w_atm=0.010893
//   [2] 357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9  2026-05-28 02:03:03  sqrt_w_atm=0.008383
#[test_only]
module deepbook_predict::pricing_reference_data;

use deepbook_predict::constants;

const ENoSuchScenario: u64 = 0;

/// One pricing point with independent correctness and exact compatibility expectations.
public struct RefPoint has copy, drop {
    lower: u64,
    higher: u64,
    reference: u64,
    tolerance: u64,
    baseline_center: u64,
}

public fun lower(p: &RefPoint): u64 { p.lower }

public fun higher(p: &RefPoint): u64 { p.higher }

public fun reference(p: &RefPoint): u64 { p.reference }

public fun tolerance(p: &RefPoint): u64 { p.tolerance }

public fun baseline_center(p: &RefPoint): u64 { p.baseline_center }

fun pt(lower: u64, higher: u64, reference: u64, tolerance: u64, baseline_center: u64): RefPoint {
    RefPoint { lower, higher, reference, tolerance, baseline_center }
}

/// Number of real-data scenarios.
public fun scenario_count(): u64 { 3 }

/// Worst-case per-endpoint precision budget (units @1e9) over all scenarios/strikes.
public fun worst_case_budget(): u64 { 3_129 }

/// Scenario spot seeded into the Propbook fixtures.
public fun creation_spot(s: u64): u64 { spot(s) }

/// Market tick size used by every scenario.
public fun tick_size(_s: u64): u64 { 1_000_000_000 }

/// Real Block Scholes spot (1e9 fixed-point) seeded into the oracle.
public fun spot(s: u64): u64 {
    if (s == 0) {
        75_852_009_440_344
    } else if (s == 1) {
        75_041_662_630_739
    } else if (s == 2) {
        74_212_635_061_019
    } else {
        abort ENoSuchScenario
    }
}

/// Real Block Scholes forward (1e9) seeded into the oracle (pushed forward).
public fun forward(s: u64): u64 {
    if (s == 0) {
        75_799_394_374_445
    } else if (s == 1) {
        75_044_761_049_821
    } else if (s == 2) {
        74_212_629_180_749
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `a` (1e9) seeded through the Block Scholes surface update.
public fun svi_a(s: u64): u64 {
    if (s == 0) {
        171_736
    } else if (s == 1) {
        99_272
    } else if (s == 2) {
        54_831
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `b` (1e9) seeded through the Block Scholes surface update.
public fun svi_b(s: u64): u64 {
    if (s == 0) {
        7_449_196
    } else if (s == 1) {
        3_466_091
    } else if (s == 2) {
        2_366_211
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `sigma` (1e9) seeded through the Block Scholes surface update.
public fun svi_sigma(s: u64): u64 {
    if (s == 0) {
        15_731_214
    } else if (s == 1) {
        6_351_738
    } else if (s == 2) {
        5_354_101
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `rho` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_rho_magnitude(s: u64): u64 {
    if (s == 0) {
        243_059_022
    } else if (s == 1) {
        475_372_427
    } else if (s == 2) {
        298_114_517
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `rho` (true == negative).
public fun svi_rho_is_negative(s: u64): bool {
    if (s == 0) {
        true
    } else if (s == 1) {
        true
    } else if (s == 2) {
        true
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `m` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_m_magnitude(s: u64): u64 {
    if (s == 0) {
        1_133_202
    } else if (s == 1) {
        3_647_706
    } else if (s == 2) {
        2_324_961
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `m` (true == negative).
public fun svi_m_is_negative(s: u64): bool {
    if (s == 0) {
        false
    } else if (s == 1) {
        true
    } else if (s == 2) {
        false
    } else {
        abort ENoSuchScenario
    }
}

/// Points for scenario `s` (range, true reference, tolerance, parent scalar center).
public fun points(s: u64): vector<RefPoint> {
    if (s == 0) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+6.045e-04
            pt(68_488_000_000_000, constants::pos_inf!(), 999_254_898, 44, 999_254_900),
            // d2~+2.0 adjusted UP(K) skew=+9.224e-03
            pt(71_901_000_000_000, constants::pos_inf!(), 986_475_283, 202, 986_475_324),
            // d2~+1.0 adjusted UP(K) skew=+4.679e-02
            pt(74_265_000_000_000, constants::pos_inf!(), 888_173_139, 732, 888_173_465),
            // d2~+0.5 adjusted UP(K) skew=+5.726e-02
            pt(75_100_000_000_000, constants::pos_inf!(), 748_850_555, 801, 748_850_877),
            // d2~+0.0 adjusted UP(K) skew=+2.822e-02
            pt(75_788_000_000_000, constants::pos_inf!(), 528_329_906, 229, 528_329_890),
            // d2~-0.5 adjusted UP(K) skew=-1.336e-02
            pt(76_433_000_000_000, constants::pos_inf!(), 295_405_051, 713, 295_404_800),
            // d2~-1.0 adjusted UP(K) skew=-2.440e-02
            pt(77_136_000_000_000, constants::pos_inf!(), 134_304_459, 827, 134_304_135),
            // d2~-2.0 adjusted UP(K) skew=-6.758e-03
            pt(78_942_000_000_000, constants::pos_inf!(), 16_002_241, 276, 16_002_176),
            // d2~-3.0 adjusted UP(K) skew=-5.006e-04
            pt(81_484_000_000_000, constants::pos_inf!(), 850_622, 51, 850_614),
            // clamp wing d2~+8
            pt(40_875_000_000_000, constants::pos_inf!(), 1_000_000_000, 2, 1_000_000_000),
            // clamp wing d2~-8
            pt(111_541_000_000_000, constants::pos_inf!(), 0, 2, 0),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(constants::neg_inf!(), 75_788_000_000_000, 471_670_094, 229, 471_670_110),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(74_265_000_000_000, 77_136_000_000_000, 753_868_680, 1_557, 753_869_330),
        ]
    } else if (s == 1) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+5.761e-04
            pt(70_751_000_000_000, constants::pos_inf!(), 999_226_715, 62, 999_226_717),
            // d2~+2.0 adjusted UP(K) skew=+8.697e-03
            pt(72_731_000_000_000, constants::pos_inf!(), 985_952_951, 440, 985_953_006),
            // d2~+1.0 adjusted UP(K) skew=+4.378e-02
            pt(74_122_000_000_000, constants::pos_inf!(), 885_252_958, 1_886, 885_253_926),
            // d2~+0.5 adjusted UP(K) skew=+4.241e-02
            pt(74_620_000_000_000, constants::pos_inf!(), 734_089_382, 1_988, 734_089_989),
            // d2~+0.0 adjusted UP(K) skew=-1.020e-03
            pt(75_040_000_000_000, constants::pos_inf!(), 499_130_516, 777, 499_130_082),
            // d2~-0.5 adjusted UP(K) skew=-1.902e-02
            pt(75_457_000_000_000, constants::pos_inf!(), 289_536_017, 1_603, 289_535_211),
            // d2~-1.0 adjusted UP(K) skew=-1.634e-02
            pt(75_903_000_000_000, constants::pos_inf!(), 142_539_030, 1_559, 142_538_210),
            // d2~-2.0 adjusted UP(K) skew=-3.789e-03
            pt(76_919_000_000_000, constants::pos_inf!(), 19_005_305, 548, 19_005_077),
            // d2~-3.0 adjusted UP(K) skew=-2.942e-04
            pt(78_125_000_000_000, constants::pos_inf!(), 1_057_214, 81, 1_057_199),
            // clamp wing d2~+8
            pt(53_193_000_000_000, constants::pos_inf!(), 1_000_000_000, 2, 1_000_000_000),
            // clamp wing d2~-8
            pt(87_962_000_000_000, constants::pos_inf!(), 0, 2, 0),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(constants::neg_inf!(), 75_040_000_000_000, 500_869_484, 777, 500_869_918),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(74_122_000_000_000, 75_903_000_000_000, 742_713_927, 3_443, 742_715_716),
        ]
    } else if (s == 2) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+4.899e-04
            pt(71_198_000_000_000, constants::pos_inf!(), 999_142_870, 85, 999_142_883),
            // d2~+2.0 adjusted UP(K) skew=+7.022e-03
            pt(72_504_000_000_000, constants::pos_inf!(), 984_281_878, 673, 984_282_218),
            // d2~+1.0 adjusted UP(K) skew=+3.565e-02
            pt(73_490_000_000_000, constants::pos_inf!(), 877_147_807, 2_326, 877_148_869),
            // d2~+0.5 adjusted UP(K) skew=+5.049e-02
            pt(73_878_000_000_000, constants::pos_inf!(), 741_986_661, 2_645, 741_987_390),
            // d2~+0.0 adjusted UP(K) skew=+3.948e-02
            pt(74_210_000_000_000, constants::pos_inf!(), 539_490_779, 1_293, 539_491_244),
            // d2~-0.5 adjusted UP(K) skew=-4.576e-04
            pt(74_514_000_000_000, constants::pos_inf!(), 308_261_559, 2_564, 308_261_004),
            // d2~-1.0 adjusted UP(K) skew=-1.534e-02
            pt(74_831_000_000_000, constants::pos_inf!(), 143_600_509, 3_129, 143_598_722),
            // d2~-2.0 adjusted UP(K) skew=-4.552e-03
            pt(75_576_000_000_000, constants::pos_inf!(), 18_232_347, 1_005, 18_232_297),
            // d2~-3.0 adjusted UP(K) skew=-3.550e-04
            pt(76_497_000_000_000, constants::pos_inf!(), 998_121, 124, 998_098),
            // clamp wing d2~+8
            pt(59_811_000_000_000, constants::pos_inf!(), 1_000_000_000, 2, 1_000_000_000),
            // clamp wing d2~-8
            pt(84_603_000_000_000, constants::pos_inf!(), 0, 2, 0),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(constants::neg_inf!(), 74_210_000_000_000, 460_509_221, 1_293, 460_508_756),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(73_490_000_000_000, 74_831_000_000_000, 733_547_298, 5_452, 733_550_147),
        ]
    } else {
        abort ENoSuchScenario
    }
}

/// Provenance: svi_event_digest of the source CSV row for scenario `s`.
public fun svi_event_digest(s: u64): vector<u8> {
    if (s == 0) {
        b"5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9"
    } else if (s == 1) {
        b"H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59"
    } else if (s == 2) {
        b"357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9"
    } else {
        abort ENoSuchScenario
    }
}
