// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/helper/reference/generate_pricing_reference.py
// Source data: packages/predict/simulations/data/scenario_dataset.csv plus the
// short-dated Block Scholes fixture documented in the generator. DO NOT EDIT BY HAND.
// Regenerate with
//   python3 generate_pricing_reference.py
//
// Independent true-math reference (Python stdlib math.log/sqrt/erf, NOT the contract
// and NOT python_replay's fixed-point pricer) for Pricer.range_price.
// The first three scenarios use the analytic worst-case fixed-point error of the
// skew-adjusted UP=N(d2)-phi(d2)*w'(k)/(2*sqrt(w)),
// propagated from math.move's documented per-primitive budgets at the TRUE values; see
// the generator header for the full derivation. The short-dated scenario instead
// pins the protocol's 0.1% mint-price ceiling at w~3.26e-8. The forward priced is
// the fresh-Pyth
// fused floor(spot * forward / bs_spot) re-anchoring.
//
// `expected_center` is the exact production fixed-point output.
// It detects value drift only; the independent reference + tolerance above decides correctness.
// `reference_lower` / `reference_upper` add a two-unit outward guard around the
// float64 true-math result; the Approx radius must enclose both endpoints.
//
// Worst-case per-endpoint budget across all scenarios/strikes: 3_129 units (@1e9).
// Dominated by the small-variance scenario at |d2|~1: d2=-(k+w/2)/sqrt(w)
// and the skew term's 1/sqrt(w) denominator amplify fixed-point variance / slope dust.
//
// Provenance (source identifier @ SVI timestamp, sqrt(w_atm)):
//   [0] 5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9  2026-05-27 08:00:18  sqrt_w_atm=0.017067
//   [1] H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59  2026-05-27 20:04:03  sqrt_w_atm=0.010893
//   [2] 357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9  2026-05-28 02:03:03  sqrt_w_atm=0.008383
//   [3] surface_1782548400000  2026-06-27 08:19:53  sqrt_w_atm=0.000184
#[test_only]
module deepbook_predict::pricing_reference_data;

use deepbook_predict::constants;

const ENoSuchScenario: u64 = 0;

/// One pricing point with independent correctness and exact compatibility expectations.
public struct RefPoint has copy, drop {
    lower: u64,
    higher: u64,
    reference: u64,
    reference_lower: u64,
    reference_upper: u64,
    tolerance: u64,
    expected_center: u64,
}

public fun lower(p: &RefPoint): u64 { p.lower }

public fun higher(p: &RefPoint): u64 { p.higher }

public fun reference(p: &RefPoint): u64 { p.reference }

public fun reference_lower(p: &RefPoint): u64 { p.reference_lower }

public fun reference_upper(p: &RefPoint): u64 { p.reference_upper }

public fun tolerance(p: &RefPoint): u64 { p.tolerance }

public fun expected_center(p: &RefPoint): u64 { p.expected_center }

fun pt(
    lower: u64,
    higher: u64,
    reference: u64,
    reference_lower: u64,
    reference_upper: u64,
    tolerance: u64,
    expected_center: u64,
): RefPoint {
    RefPoint {
        lower,
        higher,
        reference,
        reference_lower,
        reference_upper,
        tolerance,
        expected_center,
    }
}

/// Number of real-data scenarios.
public fun scenario_count(): u64 { 4 }

/// Worst-case per-endpoint precision budget (units @1e9) over all scenarios/strikes.
public fun worst_case_budget(): u64 { 3_129 }

/// Scenario spot seeded into the Propbook fixtures.
public fun creation_spot(s: u64): u64 { spot(s) }

/// Market tick size used by every scenario.
public fun tick_size(_s: u64): u64 { 1_000_000_000 }

/// Real Block Scholes spot (1e9 fixed-point) seeded into the oracle.
public fun spot(s: u64): u64 {
    if (s == 0) {
        75_852_009_440_344
    } else if (s == 1) {
        75_041_662_630_739
    } else if (s == 2) {
        74_212_635_061_019
    } else if (s == 3) {
        75_000_000_000_000
    } else {
        abort ENoSuchScenario
    }
}

/// Real Block Scholes forward (1e9) seeded into the oracle (pushed forward).
public fun forward(s: u64): u64 {
    if (s == 0) {
        75_799_394_374_445
    } else if (s == 1) {
        75_044_761_049_821
    } else if (s == 2) {
        74_212_629_180_749
    } else if (s == 3) {
        75_000_000_000_000
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `a` (1e9) seeded through the Block Scholes surface update.
public fun svi_a(s: u64): u64 {
    if (s == 0) {
        171_736
    } else if (s == 1) {
        99_272
    } else if (s == 2) {
        54_831
    } else if (s == 3) {
        28
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `b` (1e9) seeded through the Block Scholes surface update.
public fun svi_b(s: u64): u64 {
    if (s == 0) {
        7_449_196
    } else if (s == 1) {
        3_466_091
    } else if (s == 2) {
        2_366_211
    } else if (s == 3) {
        6_251
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `sigma` (1e9) seeded through the Block Scholes surface update.
public fun svi_sigma(s: u64): u64 {
    if (s == 0) {
        15_731_214
    } else if (s == 1) {
        6_351_738
    } else if (s == 2) {
        5_354_101
    } else if (s == 3) {
        1_000_000
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `rho` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_rho_magnitude(s: u64): u64 {
    if (s == 0) {
        243_059_022
    } else if (s == 1) {
        475_372_427
    } else if (s == 2) {
        298_114_517
    } else if (s == 3) {
        940_000_000
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `rho` (true == negative).
public fun svi_rho_is_negative(s: u64): bool {
    if (s == 0) {
        true
    } else if (s == 1) {
        true
    } else if (s == 2) {
        true
    } else if (s == 3) {
        true
    } else {
        abort ENoSuchScenario
    }
}

/// Real SVI `m` magnitude (1e9) seeded through the Block Scholes surface update.
public fun svi_m_magnitude(s: u64): u64 {
    if (s == 0) {
        1_133_202
    } else if (s == 1) {
        3_647_706
    } else if (s == 2) {
        2_324_961
    } else if (s == 3) {
        48_425
    } else {
        abort ENoSuchScenario
    }
}

/// Sign flag for real SVI `m` (true == negative).
public fun svi_m_is_negative(s: u64): bool {
    if (s == 0) {
        false
    } else if (s == 1) {
        true
    } else if (s == 2) {
        false
    } else if (s == 3) {
        true
    } else {
        abort ENoSuchScenario
    }
}

/// Points for scenario `s` (range, true reference enclosure, tolerance, parent center).
public fun points(s: u64): vector<RefPoint> {
    if (s == 0) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+6.045e-04
            pt(
                68_488_000_000_000,
                constants::pos_inf!(),
                999_254_898,
                999_254_896,
                999_254_901,
                44,
                999_254_898,
            ),
            // d2~+2.0 adjusted UP(K) skew=+9.224e-03
            pt(
                71_901_000_000_000,
                constants::pos_inf!(),
                986_475_283,
                986_475_281,
                986_475_286,
                202,
                986_475_284,
            ),
            // d2~+1.0 adjusted UP(K) skew=+4.679e-02
            pt(
                74_265_000_000_000,
                constants::pos_inf!(),
                888_173_146,
                888_173_143,
                888_173_148,
                732,
                888_173_166,
            ),
            // d2~+0.5 adjusted UP(K) skew=+5.726e-02
            pt(
                75_100_000_000_000,
                constants::pos_inf!(),
                748_850_570,
                748_850_567,
                748_850_572,
                801,
                748_850_600,
            ),
            // d2~+0.0 adjusted UP(K) skew=+2.822e-02
            pt(
                75_788_000_000_000,
                constants::pos_inf!(),
                528_329_929,
                528_329_926,
                528_329_931,
                229,
                528_329_883,
            ),
            // d2~-0.5 adjusted UP(K) skew=-1.336e-02
            pt(
                76_433_000_000_000,
                constants::pos_inf!(),
                295_405_070,
                295_405_067,
                295_405_072,
                713,
                295_404_986,
            ),
            // d2~-1.0 adjusted UP(K) skew=-2.440e-02
            pt(
                77_136_000_000_000,
                constants::pos_inf!(),
                134_304_469,
                134_304_466,
                134_304_471,
                827,
                134_304_491,
            ),
            // d2~-2.0 adjusted UP(K) skew=-6.758e-03
            pt(
                78_942_000_000_000,
                constants::pos_inf!(),
                16_002_242,
                16_002_240,
                16_002_245,
                276,
                16_002_241,
            ),
            // d2~-3.0 adjusted UP(K) skew=-5.006e-04
            pt(
                81_484_000_000_000,
                constants::pos_inf!(),
                850_622,
                850_620,
                850_625,
                51,
                850_622,
            ),
            // clamp wing d2~+8
            pt(
                40_875_000_000_000,
                constants::pos_inf!(),
                1_000_000_000,
                999_999_997,
                1_000_000_000,
                2,
                1_000_000_000,
            ),
            // clamp wing d2~-8
            pt(
                111_541_000_000_000,
                constants::pos_inf!(),
                0,
                0,
                3,
                2,
                0,
            ),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(
                constants::neg_inf!(),
                75_788_000_000_000,
                471_670_071,
                471_670_069,
                471_670_074,
                229,
                471_670_117,
            ),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(
                74_265_000_000_000,
                77_136_000_000_000,
                753_868_677,
                753_868_674,
                753_868_679,
                1_557,
                753_868_675,
            ),
        ]
    } else if (s == 1) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+5.761e-04
            pt(
                70_751_000_000_000,
                constants::pos_inf!(),
                999_226_715,
                999_226_713,
                999_226_718,
                62,
                999_226_716,
            ),
            // d2~+2.0 adjusted UP(K) skew=+8.697e-03
            pt(
                72_731_000_000_000,
                constants::pos_inf!(),
                985_952_952,
                985_952_949,
                985_952_954,
                440,
                985_952_968,
            ),
            // d2~+1.0 adjusted UP(K) skew=+4.378e-02
            pt(
                74_122_000_000_000,
                constants::pos_inf!(),
                885_252_962,
                885_252_959,
                885_252_964,
                1_886,
                885_253_256,
            ),
            // d2~+0.5 adjusted UP(K) skew=+4.241e-02
            pt(
                74_620_000_000_000,
                constants::pos_inf!(),
                734_089_393,
                734_089_391,
                734_089_396,
                1_988,
                734_089_915,
            ),
            // d2~+0.0 adjusted UP(K) skew=-1.020e-03
            pt(
                75_040_000_000_000,
                constants::pos_inf!(),
                499_130_530,
                499_130_528,
                499_130_533,
                777,
                499_130_085,
            ),
            // d2~-0.5 adjusted UP(K) skew=-1.902e-02
            pt(
                75_457_000_000_000,
                constants::pos_inf!(),
                289_536_027,
                289_536_025,
                289_536_030,
                1_603,
                289_535_897,
            ),
            // d2~-1.0 adjusted UP(K) skew=-1.634e-02
            pt(
                75_903_000_000_000,
                constants::pos_inf!(),
                142_539_036,
                142_539_034,
                142_539_039,
                1_559,
                142_538_929,
            ),
            // d2~-2.0 adjusted UP(K) skew=-3.789e-03
            pt(
                76_919_000_000_000,
                constants::pos_inf!(),
                19_005_306,
                19_005_304,
                19_005_309,
                548,
                19_005_287,
            ),
            // d2~-3.0 adjusted UP(K) skew=-2.942e-04
            pt(
                78_125_000_000_000,
                constants::pos_inf!(),
                1_057_214,
                1_057_212,
                1_057_217,
                81,
                1_057_212,
            ),
            // clamp wing d2~+8
            pt(
                53_193_000_000_000,
                constants::pos_inf!(),
                1_000_000_000,
                999_999_997,
                1_000_000_000,
                2,
                1_000_000_000,
            ),
            // clamp wing d2~-8
            pt(
                87_962_000_000_000,
                constants::pos_inf!(),
                0,
                0,
                3,
                2,
                0,
            ),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(
                constants::neg_inf!(),
                75_040_000_000_000,
                500_869_470,
                500_869_467,
                500_869_472,
                777,
                500_869_915,
            ),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(
                74_122_000_000_000,
                75_903_000_000_000,
                742_713_926,
                742_713_923,
                742_713_928,
                3_443,
                742_714_327,
            ),
        ]
    } else if (s == 2) {
        vector[
            // d2~+3.0 adjusted UP(K) skew=+4.899e-04
            pt(
                71_198_000_000_000,
                constants::pos_inf!(),
                999_142_871,
                999_142_868,
                999_142_873,
                85,
                999_142_871,
            ),
            // d2~+2.0 adjusted UP(K) skew=+7.022e-03
            pt(
                72_504_000_000_000,
                constants::pos_inf!(),
                984_281_880,
                984_281_877,
                984_281_882,
                673,
                984_281_911,
            ),
            // d2~+1.0 adjusted UP(K) skew=+3.565e-02
            pt(
                73_490_000_000_000,
                constants::pos_inf!(),
                877_147_821,
                877_147_818,
                877_147_823,
                2_326,
                877_147_899,
            ),
            // d2~+0.5 adjusted UP(K) skew=+5.049e-02
            pt(
                73_878_000_000_000,
                constants::pos_inf!(),
                741_986_688,
                741_986_686,
                741_986_691,
                2_645,
                741_986_937,
            ),
            // d2~+0.0 adjusted UP(K) skew=+3.948e-02
            pt(
                74_210_000_000_000,
                constants::pos_inf!(),
                539_490_822,
                539_490_819,
                539_490_824,
                1_293,
                539_491_163,
            ),
            // d2~-0.5 adjusted UP(K) skew=-4.576e-04
            pt(
                74_514_000_000_000,
                constants::pos_inf!(),
                308_261_598,
                308_261_595,
                308_261_600,
                2_564,
                308_261_500,
            ),
            // d2~-1.0 adjusted UP(K) skew=-1.534e-02
            pt(
                74_831_000_000_000,
                constants::pos_inf!(),
                143_600_530,
                143_600_527,
                143_600_532,
                3_129,
                143_599_998,
            ),
            // d2~-2.0 adjusted UP(K) skew=-4.552e-03
            pt(
                75_576_000_000_000,
                constants::pos_inf!(),
                18_232_350,
                18_232_348,
                18_232_353,
                1_005,
                18_232_308,
            ),
            // d2~-3.0 adjusted UP(K) skew=-3.550e-04
            pt(
                76_497_000_000_000,
                constants::pos_inf!(),
                998_121,
                998_118,
                998_123,
                124,
                998_121,
            ),
            // clamp wing d2~+8
            pt(
                59_811_000_000_000,
                constants::pos_inf!(),
                1_000_000_000,
                999_999_997,
                1_000_000_000,
                2,
                1_000_000_000,
            ),
            // clamp wing d2~-8
            pt(
                84_603_000_000_000,
                constants::pos_inf!(),
                0,
                0,
                3,
                2,
                0,
            ),
            // (-inf, K_atm] = 1 - adjusted UP(d2)
            pt(
                constants::neg_inf!(),
                74_210_000_000_000,
                460_509_178,
                460_509_176,
                460_509_181,
                1_293,
                460_508_837,
            ),
            // (K@d2=+1, K@d2=-1] = adjusted UP(+1)-adjusted UP(-1)
            pt(
                73_490_000_000_000,
                74_831_000_000_000,
                733_547_291,
                733_547_289,
                733_547_294,
                5_452,
                733_547_901,
            ),
        ]
    } else if (s == 3) {
        vector[
            // short-dated w~3.26e-8; 0.1% mint-price policy regression
            pt(
                75_022_000_000_000,
                constants::pos_inf!(),
                53_270_030,
                53_270_028,
                53_270_033,
                53_271,
                53_264_202,
            ),
        ]
    } else {
        abort ENoSuchScenario
    }
}

/// Provenance source identifier (CSV event digest or short-dated surface ID).
public fun svi_event_digest(s: u64): vector<u8> {
    if (s == 0) {
        b"5KbNiu2S7ULJcS1ryDtJ3DC2omTojjJoMFjmu7nYgTAF9"
    } else if (s == 1) {
        b"H4DNoM3eRw83KdZjASFabLJSgu7YNZYRNfCWErcKgnE59"
    } else if (s == 2) {
        b"357n4TarJkp62atdMpfGExEr77SZGqnDBZ7QcBatgpUF9"
    } else if (s == 3) {
        b"surface_1782548400000"
    } else {
        abort ENoSuchScenario
    }
}
