// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/helper/reference/generate_pricing_reference.py
// DO NOT EDIT BY HAND — regenerate with
//   python3 generate_pricing_reference.py --tick-only
// (needs no scenario CSV; a full run regenerates this file too).
//
// Independent true-math reference (Python stdlib math.sqrt/erf, NOT the contract)
// for a Pricer rebuilt at a committed tick: the Block Scholes basis re-anchored on
// the committed spot and SVI `a`, `b` rolled down to the tick. Each point prices
// the skew-adjusted UP digital at the re-anchored forward, where log-moneyness is
// exactly zero; its `tolerance` is the analytic fixed-point budget at k = 0, see
// the generator's tick section.
#[test_only]
module deepbook_predict::tick_pricing_reference_data;

/// One reference point: the UP digital at `forward()` priced at `priced_at_ms`
/// must be within `tolerance` units of the true-math `reference`.
public struct TickPoint has copy, drop {
    priced_at_ms: u64,
    reference: u64,
    tolerance: u64,
}

public fun priced_at_ms(p: &TickPoint): u64 { p.priced_at_ms }

public fun reference(p: &TickPoint): u64 { p.reference }

public fun tolerance(p: &TickPoint): u64 { p.tolerance }

fun pt(priced_at_ms: u64, reference: u64, tolerance: u64): TickPoint {
    TickPoint { priced_at_ms, reference, tolerance }
}

/// Market expiry the surface is priced against.
public fun expiry_ms(): u64 { 240_000 }

/// SVI source timestamp, the roll-down anchor (the fixture clock at seeding).
public fun svi_source_timestamp_ms(): u64 { 120_000 }

/// Block Scholes spot and forward seeded at enqueue (basis 1.005).
public fun bs_spot(): u64 { 100_000_000_000 }

public fun bs_forward(): u64 { 100_500_000_000 }

/// Pyth spot committed for the tick.
public fun committed_spot(): u64 { 102_000_000_000 }

/// `committed_spot * bs_forward / bs_spot`, exact in integers.
public fun forward(): u64 { 102_510_000_000 }

/// Raw SVI parameters (1e9) seeded through the Block Scholes surface update.
public fun svi_a(): u64 { 400 }

public fun svi_a_is_negative(): bool { false }

public fun svi_b(): u64 { 20_000 }

public fun svi_rho_magnitude(): u64 { 300_000_000 }

public fun svi_rho_is_negative(): bool { true }

public fun svi_m_magnitude(): u64 { 1_000_000 }

public fun svi_m_is_negative(): bool { false }

public fun svi_sigma(): u64 { 20_000_000 }

/// Reference points, one per tick (priced_at_ms, true-math reference, tolerance).
public fun points(): vector<TickPoint> {
    vector[
        // roll-down ratio 1.000000
        pt(120_000, 501_375_392, 248),
        // roll-down ratio 0.500000
        pt(180_000, 500_972_549, 340),
        // roll-down ratio 0.100000
        pt(228_000, 500_434_937, 728),
        // roll-down ratio 0.008333
        pt(239_000, 500_125_556, 2_459),
    ]
}
