[package]
name = "deepbook"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "a53f7f879ef3c97d676cdfde0518b6cccfb4b5f0" }
token = { local = "../token"}

[addresses]
deepbook = "0x0"
