[package]
name = "deepbook"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "56f74313c6574a13720d0270bfc393e1bc1da5e1"}

[addresses]
deepbook = "0x0"
