ALTER TABLE oracle_activated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_activated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_settled ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_settled ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_prices_updated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_prices_updated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_svi_updated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_svi_updated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE predict_created ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE predict_created ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_created ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_created ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE position_minted ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE position_minted ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE position_redeemed ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE position_redeemed ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE range_minted ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE range_minted ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE range_redeemed ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE range_redeemed ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE supplied ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE supplied ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE withdrawn ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE withdrawn ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE trading_pause_updated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE trading_pause_updated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE pricing_config_updated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE pricing_config_updated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE risk_config_updated ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE risk_config_updated ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_ask_bounds_set ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_ask_bounds_set ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE oracle_ask_bounds_cleared ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE oracle_ask_bounds_cleared ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE quote_asset_enabled ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE quote_asset_enabled ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE quote_asset_disabled ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE quote_asset_disabled ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;

ALTER TABLE predict_manager_created ADD COLUMN IF NOT EXISTS tx_index BIGINT NOT NULL DEFAULT 0;
ALTER TABLE predict_manager_created ADD COLUMN IF NOT EXISTS event_index BIGINT NOT NULL DEFAULT 0;
