[package]
name = "maker_incentives"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
deepbook = { local = "../deepbook" }
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "main" }
enclave = { git = "https://github.com/MystenLabs/nautilus.git", subdir = "move/enclave", rev = "main" }

[addresses]
maker_incentives = "0x0"
