// DO NOT EDIT — generated by generate.py
// Source of truth: scipy.stats.norm + Python math
// Regenerate: cd tests/generated_tests && python3 generate.py && bunx prettier-move -c *.move --write

#[test_only]
module deepbook_predict::generated_predict;

public struct TradeCase has copy, drop {
    strike: u64,
    quantity: u64,
    is_up: bool,
    expected_cost: u64,
    expected_redeem_payout: u64,
}

public struct PredictScenario has copy, drop {
    oracle_scenario_idx: u64,
    trade_cases: vector<TradeCase>,
}

public fun oracle_scenario_idx(s: &PredictScenario): u64 { s.oracle_scenario_idx }
public fun trade_cases(s: &PredictScenario): &vector<TradeCase> { &s.trade_cases }

public fun strike(tc: &TradeCase): u64 { tc.strike }
public fun quantity(tc: &TradeCase): u64 { tc.quantity }
public fun is_up(tc: &TradeCase): bool { tc.is_up }
public fun expected_cost(tc: &TradeCase): u64 { tc.expected_cost }
public fun expected_redeem_payout(tc: &TradeCase): u64 { tc.expected_redeem_payout }

public fun scenarios(): vector<PredictScenario> {
    vector[
        // Index 0: S0
        PredictScenario {
            oracle_scenario_idx: 7,
            trade_cases: vector[
                TradeCase { strike: 70_782_878_010_000, quantity: 10_000_000, is_up: true, expected_cost: 4_937_084, expected_redeem_payout: 4_737_190 },
                TradeCase { strike: 70_782_878_010_000, quantity: 10_000_000, is_up: false, expected_cost: 5_256_137, expected_redeem_payout: 5_056_235 },
                TradeCase { strike: 77_861_165_811_000, quantity: 10_000_000, is_up: true, expected_cost: 1_167_449, expected_redeem_payout: 1_042_057 },
                TradeCase { strike: 63_704_590_209_000, quantity: 10_000_000, is_up: true, expected_cost: 8_567_932, expected_redeem_payout: 8_424_964 },
                TradeCase { strike: 63_704_590_209_000, quantity: 10_000_000, is_up: false, expected_cost: 1_568_228, expected_redeem_payout: 1_425_522 },
                TradeCase { strike: 70_782_878_010_000, quantity: 1_000, is_up: true, expected_cost: 493, expected_redeem_payout: 473 },
                TradeCase { strike: 70_782_878_010_000, quantity: 500_000_000, is_up: true, expected_cost: 246_854_241, expected_redeem_payout: 236_859_547 },
            ],
        },
        // Index 1: S1
        PredictScenario {
            oracle_scenario_idx: 8,
            trade_cases: vector[
                TradeCase { strike: 74_241_496_580_000, quantity: 10_000_000, is_up: true, expected_cost: 4_998_902, expected_redeem_payout: 4_798_943 },
                TradeCase { strike: 74_241_496_580_000, quantity: 10_000_000, is_up: false, expected_cost: 5_199_868, expected_redeem_payout: 4_999_908 },
                TradeCase { strike: 81_665_646_238_000, quantity: 10_000_000, is_up: true, expected_cost: 421_169, expected_redeem_payout: 321_169 },
                TradeCase { strike: 66_817_346_922_000, quantity: 10_000_000, is_up: true, expected_cost: 9_338_008, expected_redeem_payout: 9_235_046 },
                TradeCase { strike: 66_817_346_922_000, quantity: 10_000_000, is_up: false, expected_cost: 763_724, expected_redeem_payout: 660_842 },
                TradeCase { strike: 74_241_496_580_000, quantity: 1_000, is_up: true, expected_cost: 499, expected_redeem_payout: 479 },
                TradeCase { strike: 74_241_496_580_000, quantity: 500_000_000, is_up: true, expected_cost: 249_945_111, expected_redeem_payout: 239_947_154 },
            ],
        },
        // Index 2: S3
        PredictScenario {
            oracle_scenario_idx: 10,
            trade_cases: vector[
                TradeCase { strike: 72_523_227_120_000, quantity: 10_000_000, is_up: true, expected_cost: 5_018_954, expected_redeem_payout: 4_818_980 },
                TradeCase { strike: 72_523_227_120_000, quantity: 10_000_000, is_up: false, expected_cost: 5_180_974, expected_redeem_payout: 4_981_000 },
                TradeCase { strike: 79_775_549_832_000, quantity: 10_000_000, is_up: true, expected_cost: 162_664, expected_redeem_payout: 62_664 },
                TradeCase { strike: 65_270_904_407_999, quantity: 10_000_000, is_up: true, expected_cost: 9_735_670, expected_redeem_payout: 9_635_670 },
                TradeCase { strike: 65_270_904_407_999, quantity: 10_000_000, is_up: false, expected_cost: 364_284, expected_redeem_payout: 264_284 },
                TradeCase { strike: 72_523_227_120_000, quantity: 1_000, is_up: true, expected_cost: 501, expected_redeem_payout: 481 },
                TradeCase { strike: 72_523_227_120_000, quantity: 500_000_000, is_up: true, expected_cost: 250_947_712, expected_redeem_payout: 240_949_025 },
            ],
        },
        // Index 3: S4
        PredictScenario {
            oracle_scenario_idx: 11,
            trade_cases: vector[
                TradeCase { strike: 72_167_958_690_000, quantity: 10_000_000, is_up: true, expected_cost: 5_019_137, expected_redeem_payout: 4_819_163 },
                TradeCase { strike: 72_167_958_690_000, quantity: 10_000_000, is_up: false, expected_cost: 5_180_834, expected_redeem_payout: 4_980_861 },
                TradeCase { strike: 79_384_754_559_000, quantity: 10_000_000, is_up: true, expected_cost: 175_867, expected_redeem_payout: 75_867 },
                TradeCase { strike: 64_951_162_821_000, quantity: 10_000_000, is_up: true, expected_cost: 9_684_180, expected_redeem_payout: 9_584_180 },
                TradeCase { strike: 64_951_162_821_000, quantity: 10_000_000, is_up: false, expected_cost: 415_818, expected_redeem_payout: 315_818 },
                TradeCase { strike: 72_167_958_690_000, quantity: 1_000, is_up: true, expected_cost: 501, expected_redeem_payout: 481 },
                TradeCase { strike: 72_167_958_690_000, quantity: 500_000_000, is_up: true, expected_cost: 250_956_874, expected_redeem_payout: 240_958_181 },
            ],
        },
        // Index 4: S5
        PredictScenario {
            oracle_scenario_idx: 12,
            trade_cases: vector[
                TradeCase { strike: 72_167_958_690_000, quantity: 10_000_000, is_up: true, expected_cost: 5_019_138, expected_redeem_payout: 4_819_164 },
                TradeCase { strike: 72_167_958_690_000, quantity: 10_000_000, is_up: false, expected_cost: 5_180_835, expected_redeem_payout: 4_980_861 },
                TradeCase { strike: 79_384_754_559_000, quantity: 10_000_000, is_up: true, expected_cost: 175_867, expected_redeem_payout: 75_867 },
                TradeCase { strike: 64_951_162_821_000, quantity: 10_000_000, is_up: true, expected_cost: 9_684_181, expected_redeem_payout: 9_584_181 },
                TradeCase { strike: 64_951_162_821_000, quantity: 10_000_000, is_up: false, expected_cost: 415_818, expected_redeem_payout: 315_818 },
                TradeCase { strike: 72_167_958_690_000, quantity: 1_000, is_up: true, expected_cost: 501, expected_redeem_payout: 481 },
                TradeCase { strike: 72_167_958_690_000, quantity: 500_000_000, is_up: true, expected_cost: 250_956_900, expected_redeem_payout: 240_958_207 },
            ],
        },
    ]
}
