// DO NOT EDIT — generated by generate.py
// Source of truth: scipy.stats.norm + Black-Scholes + SVI
// Regenerate: cd tests/generated_tests && python3 generate.py

#[test_only]
module deepbook_predict::generated_oracle;


// === Synthetic oracle scenarios ===
// Hand-picked SVI params to test specific pricing behaviors.
// All inputs are pure math — no contract conventions (ms, FLOAT_SCALING).
// Move tests must construct oracles that produce matching t values.

// Standard SVI (a=0, b=1, rho=0, m=0, sigma=0.25), rate=0, t=0.0000317098yr
public macro fun SYN_STD_UP_ATM(): u64 { 401_293_674 }
public macro fun SYN_STD_DN_ATM(): u64 { 598_706_325 }
public macro fun SYN_STD_UP_STRIKE_2X(): u64 { 108_101_717 }
public macro fun SYN_STD_DN_STRIKE_2X(): u64 { 891_898_282 }
public macro fun SYN_STD_UP_DEEP_ITM(): u64 { 773_988_940 }
public macro fun SYN_STD_DN_DEEP_ITM(): u64 { 226_011_059 }
public macro fun SYN_STD_UP_DEEP_OTM(): u64 { 11_485_171 }
public macro fun SYN_STD_DN_DEEP_OTM(): u64 { 988_514_828 }
public macro fun SYN_STD_UP_S50(): u64 { 647_390_543 }
public macro fun SYN_STD_DN_S50(): u64 { 352_609_456 }
public macro fun SYN_STD_UP_S80(): u64 { 538_253_668 }
public macro fun SYN_STD_DN_S80(): u64 { 461_746_331 }
public macro fun SYN_STD_UP_S100(): u64 { 401_293_674 }
public macro fun SYN_STD_DN_S100(): u64 { 598_706_325 }
public macro fun SYN_STD_UP_S120(): u64 { 272_292_717 }
public macro fun SYN_STD_DN_S120(): u64 { 727_707_282 }
public macro fun SYN_STD_UP_S150(): u64 { 175_521_297 }
public macro fun SYN_STD_DN_S150(): u64 { 824_478_702 }

// Standard SVI with 5% rate, t=1.0yr
public macro fun SYN_DISCOUNT_5PCT_1YR(): u64 { 951_229_424 } // e^(-0.05*1.0) = 0.951229425
public macro fun SYN_5PCT_UP_S60(): u64 { 587_883_669 }
public macro fun SYN_5PCT_DN_S60(): u64 { 363_345_754 }
public macro fun SYN_5PCT_UP_S80(): u64 { 512_002_726 }
public macro fun SYN_5PCT_DN_S80(): u64 { 439_226_697 }
public macro fun SYN_5PCT_UP_S100(): u64 { 381_722_350 }
public macro fun SYN_5PCT_DN_S100(): u64 { 569_507_073 }
public macro fun SYN_5PCT_UP_S120(): u64 { 259_012_845 }
public macro fun SYN_5PCT_DN_S120(): u64 { 692_216_579 }
public macro fun SYN_5PCT_UP_S140(): u64 { 189_768_394 }
public macro fun SYN_5PCT_DN_S140(): u64 { 761_461_029 }
public macro fun SYN_5PCT_UP_ATM(): u64 { 381_722_350 }
public macro fun SYN_5PCT_DN_ATM(): u64 { 569_507_073 }

// Standard SVI with 10% rate, t=0.5yr
public macro fun SYN_DISCOUNT_10PCT_HALF_YR(): u64 { 951_229_424 } // e^(-0.10*0.5) = 0.951229425
public macro fun SYN_10PCT_HALF_UP_ATM(): u64 { 381_722_350 }
public macro fun SYN_10PCT_HALF_DN_ATM(): u64 { 569_507_073 }

// Standard SVI with 10% rate, t=0.3170979198yr
public macro fun SYN_10PCT_PARTIAL_UP_ATM(): u64 { 388_768_372 }
public macro fun SYN_10PCT_PARTIAL_DN_ATM(): u64 { 580_019_318 }

// Full SVI (a=0.05, b=0.8, rho=-0.3, m=0.1, sigma=0.2), rate=0, t=0.0000317098yr
public macro fun SYN_FULL_UP_ATM(): u64 { 400_737_521 }
public macro fun SYN_FULL_DN_ATM(): u64 { 599_262_478 }

// Small sigma (sigma=0.01), rate=0, t=0.0000317098yr
public macro fun SYN_SMALL_SIGMA_UP_ATM(): u64 { 480_061_194 }
public macro fun SYN_SMALL_SIGMA_DN_ATM(): u64 { 519_938_805 }

// Nonzero a (a=0.1), rate=0, t=0.0000317098yr — increases variance
public macro fun SYN_A100M_UP_ATM(): u64 { 383_689_888 }

// Negative rho (rho=-0.3), rate=0, t=0.0000317098yr — skews the smile
public macro fun SYN_NEG_RHO_UP_S80(): u64 { 513_915_360 }
public macro fun SYN_NEG_RHO_DN_S80(): u64 { 486_084_639 }
public macro fun SYN_NEG_RHO_UP_S100(): u64 { 401_293_674 }
public macro fun SYN_NEG_RHO_DN_S100(): u64 { 598_706_325 }
public macro fun SYN_NEG_RHO_UP_S120(): u64 { 269_740_854 }
public macro fun SYN_NEG_RHO_DN_S120(): u64 { 730_259_145 }

// Nonzero m (m=0.1), rate=0, t=0.0000317098yr — shifts the smile center
public macro fun SYN_M_UP_S80(): u64 { 511_771_599 }
public macro fun SYN_M_DN_S80(): u64 { 488_228_400 }
public macro fun SYN_M_UP_S100(): u64 { 397_643_836 }
public macro fun SYN_M_DN_S100(): u64 { 602_356_163 }
public macro fun SYN_M_UP_S120(): u64 { 270_303_319 }
public macro fun SYN_M_DN_S120(): u64 { 729_696_680 }

// === Oracle pricing scenarios from real Block Scholes data ===
// Sampled by time-to-expiry diversity: 7d, 3d, 1d, 6h, 1h, 5m, <1m
// MTM values use quantity = 10.0

// --- S0: spot=70770.30, forward=70782.88, tte=7.0d ---
public macro fun S0_SPOT(): u64 { 70_770_295_760_000 }
public macro fun S0_FORWARD(): u64 { 70_782_878_010_000 }
public macro fun S0_A(): u64 { 1_080_000 }
public macro fun S0_B(): u64 { 42_280_000 }
public macro fun S0_RHO(): u64 { 332_660_000 }
public macro fun S0_RHO_NEG(): u64 { 1 }
public macro fun S0_M(): u64 { 3_020_000 }
public macro fun S0_M_NEG(): u64 { 1 }
public macro fun S0_SIGMA(): u64 { 126_980_000 }
public macro fun S0_RATE(): u64 { 35_000_000 }
public macro fun S0_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S0_NOW_MS(): u64 { 1_773_241_327_070 }
public macro fun S0_STRIKE_ATM(): u64 { 70_782_878_010_000 }
public macro fun S0_UP_ATM(): u64 { 483_713_788 }
public macro fun S0_DN_ATM(): u64 { 515_618_669 }
public macro fun S0_MTM_UP_ATM(): u64 { 4_837_137 }
public macro fun S0_MTM_DN_ATM(): u64 { 5_156_186 }
public macro fun S0_STRIKE_OTM5(): u64 { 74_322_021_910_500 }
public macro fun S0_UP_OTM5(): u64 { 254_016_436 }
public macro fun S0_DN_OTM5(): u64 { 745_316_021 }
public macro fun S0_MTM_UP_OTM5(): u64 { 2_540_164 }
public macro fun S0_MTM_DN_OTM5(): u64 { 7_453_160 }
public macro fun S0_STRIKE_OTM10(): u64 { 77_861_165_811_000 }
public macro fun S0_UP_OTM10(): u64 { 110_475_331 }
public macro fun S0_DN_OTM10(): u64 { 888_857_126 }
public macro fun S0_MTM_UP_OTM10(): u64 { 1_104_753 }
public macro fun S0_MTM_DN_OTM10(): u64 { 8_888_571 }
public macro fun S0_STRIKE_ITM5(): u64 { 67_243_734_109_500 }
public macro fun S0_UP_ITM5(): u64 { 707_981_468 }
public macro fun S0_DN_ITM5(): u64 { 291_350_988 }
public macro fun S0_MTM_UP_ITM5(): u64 { 7_079_814 }
public macro fun S0_MTM_DN_ITM5(): u64 { 2_913_509 }
public macro fun S0_STRIKE_ITM10(): u64 { 63_704_590_209_000 }
public macro fun S0_UP_ITM10(): u64 { 849_644_865 }
public macro fun S0_DN_ITM10(): u64 { 149_687_592 }
public macro fun S0_MTM_UP_ITM10(): u64 { 8_496_448 }
public macro fun S0_MTM_DN_ITM10(): u64 { 1_496_875 }

// --- S1: spot=70450.71, forward=70450.19, tte=5.9d ---
public macro fun S1_SPOT(): u64 { 70_450_708_810_000 }
public macro fun S1_FORWARD(): u64 { 70_450_190_810_000 }
public macro fun S1_A(): u64 { 2_080_000 }
public macro fun S1_B(): u64 { 34_010_000 }
public macro fun S1_RHO(): u64 { 481_790_000 }
public macro fun S1_RHO_NEG(): u64 { 1 }
public macro fun S1_M(): u64 { 4_090_000 }
public macro fun S1_M_NEG(): u64 { 1 }
public macro fun S1_SIGMA(): u64 { 113_820_000 }
public macro fun S1_RATE(): u64 { 35_000_000 }
public macro fun S1_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S1_NOW_MS(): u64 { 1_773_336_294_232 }
public macro fun S1_STRIKE_ATM(): u64 { 70_450_190_810_000 }
public macro fun S1_UP_ATM(): u64 { 484_427_121 }
public macro fun S1_DN_ATM(): u64 { 515_010_669 }
public macro fun S1_MTM_UP_ATM(): u64 { 4_844_271 }
public macro fun S1_MTM_DN_ATM(): u64 { 5_150_106 }
public macro fun S1_STRIKE_OTM5(): u64 { 73_972_700_350_500 }
public macro fun S1_UP_OTM5(): u64 { 243_080_680 }
public macro fun S1_DN_OTM5(): u64 { 756_357_111 }
public macro fun S1_MTM_UP_OTM5(): u64 { 2_430_806 }
public macro fun S1_MTM_DN_OTM5(): u64 { 7_563_571 }
public macro fun S1_STRIKE_OTM10(): u64 { 77_495_209_891_000 }
public macro fun S1_UP_OTM10(): u64 { 94_692_180 }
public macro fun S1_DN_OTM10(): u64 { 904_745_611 }
public macro fun S1_MTM_UP_OTM10(): u64 { 946_921 }
public macro fun S1_MTM_DN_OTM10(): u64 { 9_047_456 }
public macro fun S1_STRIKE_ITM5(): u64 { 66_927_681_269_500 }
public macro fun S1_UP_ITM5(): u64 { 714_981_612 }
public macro fun S1_DN_ITM5(): u64 { 284_456_179 }
public macro fun S1_MTM_UP_ITM5(): u64 { 7_149_816 }
public macro fun S1_MTM_DN_ITM5(): u64 { 2_844_561 }
public macro fun S1_STRIKE_ITM10(): u64 { 63_405_171_729_000 }
public macro fun S1_UP_ITM10(): u64 { 856_823_042 }
public macro fun S1_DN_ITM10(): u64 { 142_614_749 }
public macro fun S1_MTM_UP_ITM10(): u64 { 8_568_230 }
public macro fun S1_MTM_DN_ITM10(): u64 { 1_426_147 }

// --- S2: spot=71459.79, forward=71461.69, tte=3.3d ---
public macro fun S2_SPOT(): u64 { 71_459_792_540_000 }
public macro fun S2_FORWARD(): u64 { 71_461_685_310_000 }
public macro fun S2_A(): u64 { 1_170_000 }
public macro fun S2_B(): u64 { 30_460_000 }
public macro fun S2_RHO(): u64 { 354_910_000 }
public macro fun S2_RHO_NEG(): u64 { 1 }
public macro fun S2_M(): u64 { 1_250_000 }
public macro fun S2_M_NEG(): u64 { 0 }
public macro fun S2_SIGMA(): u64 { 95_040_000 }
public macro fun S2_RATE(): u64 { 35_000_000 }
public macro fun S2_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S2_NOW_MS(): u64 { 1_773_558_189_150 }
public macro fun S2_STRIKE_ATM(): u64 { 71_461_685_310_000 }
public macro fun S2_UP_ATM(): u64 { 487_109_029 }
public macro fun S2_DN_ATM(): u64 { 512_574_922 }
public macro fun S2_MTM_UP_ATM(): u64 { 4_871_090 }
public macro fun S2_MTM_DN_ATM(): u64 { 5_125_749 }
public macro fun S2_STRIKE_OTM5(): u64 { 75_034_769_575_500 }
public macro fun S2_UP_OTM5(): u64 { 207_994_210 }
public macro fun S2_DN_OTM5(): u64 { 791_689_741 }
public macro fun S2_MTM_UP_OTM5(): u64 { 2_079_942 }
public macro fun S2_MTM_DN_OTM5(): u64 { 7_916_897 }
public macro fun S2_STRIKE_OTM10(): u64 { 78_607_853_841_000 }
public macro fun S2_UP_OTM10(): u64 { 66_965_344 }
public macro fun S2_DN_OTM10(): u64 { 932_718_607 }
public macro fun S2_MTM_UP_OTM10(): u64 { 669_653 }
public macro fun S2_MTM_DN_OTM10(): u64 { 9_327_186 }
public macro fun S2_STRIKE_ITM5(): u64 { 67_888_601_044_500 }
public macro fun S2_UP_ITM5(): u64 { 753_585_729 }
public macro fun S2_DN_ITM5(): u64 { 246_098_222 }
public macro fun S2_MTM_UP_ITM5(): u64 { 7_535_857 }
public macro fun S2_MTM_DN_ITM5(): u64 { 2_460_982 }
public macro fun S2_STRIKE_ITM10(): u64 { 64_315_516_779_000 }
public macro fun S2_UP_ITM10(): u64 { 893_875_730 }
public macro fun S2_DN_ITM10(): u64 { 105_808_221 }
public macro fun S2_MTM_UP_ITM10(): u64 { 8_938_757 }
public macro fun S2_MTM_DN_ITM10(): u64 { 1_058_082 }

// --- S3: spot=74228.29, forward=74241.50, tte=1.2d ---
public macro fun S3_SPOT(): u64 { 74_228_286_720_000 }
public macro fun S3_FORWARD(): u64 { 74_241_496_580_000 }
public macro fun S3_A(): u64 { 550_000 }
public macro fun S3_B(): u64 { 26_870_000 }
public macro fun S3_RHO(): u64 { 360_900_000 }
public macro fun S3_RHO_NEG(): u64 { 1 }
public macro fun S3_M(): u64 { 4_160_000 }
public macro fun S3_M_NEG(): u64 { 1 }
public macro fun S3_SIGMA(): u64 { 75_400_000 }
public macro fun S3_RATE(): u64 { 35_000_000 }
public macro fun S3_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S3_NOW_MS(): u64 { 1_773_735_844_810 }
public macro fun S3_STRIKE_ATM(): u64 { 74_241_496_580_000 }
public macro fun S3_UP_ATM(): u64 { 489_892_266 }
public macro fun S3_DN_ATM(): u64 { 509_988_812 }
public macro fun S3_MTM_UP_ATM(): u64 { 4_898_922 }
public macro fun S3_MTM_DN_ATM(): u64 { 5_099_888 }
public macro fun S3_STRIKE_OTM5(): u64 { 77_953_571_409_000 }
public macro fun S3_UP_OTM5(): u64 { 159_001_188 }
public macro fun S3_DN_OTM5(): u64 { 840_879_890 }
public macro fun S3_MTM_UP_OTM5(): u64 { 1_590_011 }
public macro fun S3_MTM_DN_OTM5(): u64 { 8_408_798 }
public macro fun S3_STRIKE_OTM10(): u64 { 81_665_646_238_000 }
public macro fun S3_UP_OTM10(): u64 { 37_116_900 }
public macro fun S3_DN_OTM10(): u64 { 962_764_178 }
public macro fun S3_MTM_UP_OTM10(): u64 { 371_169 }
public macro fun S3_MTM_DN_OTM10(): u64 { 9_627_641 }
public macro fun S3_STRIKE_ITM5(): u64 { 70_529_421_751_000 }
public macro fun S3_UP_ITM5(): u64 { 802_521_926 }
public macro fun S3_DN_ITM5(): u64 { 197_359_152 }
public macro fun S3_MTM_UP_ITM5(): u64 { 8_025_219 }
public macro fun S3_MTM_DN_ITM5(): u64 { 1_973_591 }
public macro fun S3_STRIKE_ITM10(): u64 { 66_817_346_922_000 }
public macro fun S3_UP_ITM10(): u64 { 928_652_729 }
public macro fun S3_DN_ITM10(): u64 { 71_228_349 }
public macro fun S3_MTM_UP_ITM10(): u64 { 9_286_527 }
public macro fun S3_MTM_DN_ITM10(): u64 { 712_283 }

// --- S4: spot=74105.49, forward=74127.85, tte=5.0h ---
public macro fun S4_SPOT(): u64 { 74_105_490_370_000 }
public macro fun S4_FORWARD(): u64 { 74_127_848_210_000 }
public macro fun S4_A(): u64 { 960_000 }
public macro fun S4_B(): u64 { 12_900_000 }
public macro fun S4_RHO(): u64 { 640_610_000 }
public macro fun S4_RHO_NEG(): u64 { 1 }
public macro fun S4_M(): u64 { 16_010_000 }
public macro fun S4_M_NEG(): u64 { 1 }
public macro fun S4_SIGMA(): u64 { 31_180_000 }
public macro fun S4_RATE(): u64 { 35_000_000 }
public macro fun S4_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S4_NOW_MS(): u64 { 1_773_825_103_183 }
public macro fun S4_STRIKE_ATM(): u64 { 74_127_848_210_000 }
public macro fun S4_UP_ATM(): u64 { 492_854_532 }
public macro fun S4_DN_ATM(): u64 { 507_125_601 }
public macro fun S4_MTM_UP_ATM(): u64 { 4_928_545 }
public macro fun S4_MTM_DN_ATM(): u64 { 5_071_256 }
public macro fun S4_STRIKE_OTM5(): u64 { 77_834_240_620_500 }
public macro fun S4_UP_OTM5(): u64 { 89_274_331 }
public macro fun S4_DN_OTM5(): u64 { 910_705_803 }
public macro fun S4_MTM_UP_OTM5(): u64 { 892_743 }
public macro fun S4_MTM_DN_OTM5(): u64 { 9_107_058 }
public macro fun S4_STRIKE_OTM10(): u64 { 81_540_633_031_000 }
public macro fun S4_UP_OTM10(): u64 { 7_041_435 }
public macro fun S4_DN_OTM10(): u64 { 992_938_699 }
public macro fun S4_MTM_UP_OTM10(): u64 { 70_414 }
public macro fun S4_MTM_DN_OTM10(): u64 { 9_929_386 }
public macro fun S4_STRIKE_ITM5(): u64 { 70_421_455_799_500 }
public macro fun S4_UP_ITM5(): u64 { 878_599_456 }
public macro fun S4_DN_ITM5(): u64 { 121_380_678 }
public macro fun S4_MTM_UP_ITM5(): u64 { 8_785_994 }
public macro fun S4_MTM_DN_ITM5(): u64 { 1_213_806 }
public macro fun S4_STRIKE_ITM10(): u64 { 66_715_063_389_000 }
public macro fun S4_UP_ITM10(): u64 { 972_743_617 }
public macro fun S4_DN_ITM10(): u64 { 27_236_517 }
public macro fun S4_MTM_UP_ITM10(): u64 { 9_727_436 }
public macro fun S4_MTM_DN_ITM10(): u64 { 272_365 }

// --- S5: spot=72385.19, forward=72523.23, tte=1.1h ---
public macro fun S5_SPOT(): u64 { 72_385_193_560_000 }
public macro fun S5_FORWARD(): u64 { 72_523_227_120_000 }
public macro fun S5_A(): u64 { 1_050_000 }
public macro fun S5_B(): u64 { 12_360_000 }
public macro fun S5_RHO(): u64 { 526_610_000 }
public macro fun S5_RHO_NEG(): u64 { 1 }
public macro fun S5_M(): u64 { 3_690_000 }
public macro fun S5_M_NEG(): u64 { 1 }
public macro fun S5_SIGMA(): u64 { 50_320_000 }
public macro fun S5_RATE(): u64 { 35_000_000 }
public macro fun S5_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S5_NOW_MS(): u64 { 1_773_838_922_225 }
public macro fun S5_STRIKE_ATM(): u64 { 72_523_227_120_000 }
public macro fun S5_UP_ATM(): u64 { 491_896_737 }
public macro fun S5_DN_ATM(): u64 { 508_098_734 }
public macro fun S5_MTM_UP_ATM(): u64 { 4_918_967 }
public macro fun S5_MTM_DN_ATM(): u64 { 5_080_987 }
public macro fun S5_STRIKE_OTM5(): u64 { 76_149_388_476_000 }
public macro fun S5_UP_OTM5(): u64 { 108_022_023 }
public macro fun S5_DN_OTM5(): u64 { 891_973_448 }
public macro fun S5_MTM_UP_OTM5(): u64 { 1_080_220 }
public macro fun S5_MTM_DN_OTM5(): u64 { 8_919_734 }
public macro fun S5_STRIKE_OTM10(): u64 { 79_775_549_832_000 }
public macro fun S5_UP_OTM10(): u64 { 11_266_430 }
public macro fun S5_DN_OTM10(): u64 { 988_729_041 }
public macro fun S5_MTM_UP_OTM10(): u64 { 112_664 }
public macro fun S5_MTM_DN_OTM10(): u64 { 9_887_290 }
public macro fun S5_STRIKE_ITM5(): u64 { 68_897_065_764_000 }
public macro fun S5_UP_ITM5(): u64 { 856_802_910 }
public macro fun S5_DN_ITM5(): u64 { 143_192_561 }
public macro fun S5_MTM_UP_ITM5(): u64 { 8_568_029 }
public macro fun S5_MTM_DN_ITM5(): u64 { 1_431_925 }
public macro fun S5_STRIKE_ITM10(): u64 { 65_270_904_407_999 }
public macro fun S5_UP_ITM10(): u64 { 968_567_058 }
public macro fun S5_DN_ITM10(): u64 { 31_428_412 }
public macro fun S5_MTM_UP_ITM10(): u64 { 9_685_670 }
public macro fun S5_MTM_DN_ITM10(): u64 { 314_284 }

// --- S6: spot=72137.86, forward=72167.96, tte=2m ---
public macro fun S6_SPOT(): u64 { 72_137_857_040_000 }
public macro fun S6_FORWARD(): u64 { 72_167_958_690_000 }
public macro fun S6_A(): u64 { 770_000 }
public macro fun S6_B(): u64 { 15_490_000 }
public macro fun S6_RHO(): u64 { 399_060_000 }
public macro fun S6_RHO_NEG(): u64 { 1 }
public macro fun S6_M(): u64 { 4_540_000 }
public macro fun S6_M_NEG(): u64 { 0 }
public macro fun S6_SIGMA(): u64 { 54_360_000 }
public macro fun S6_RATE(): u64 { 35_000_000 }
public macro fun S6_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S6_NOW_MS(): u64 { 1_773_842_876_472 }
public macro fun S6_STRIKE_ATM(): u64 { 72_167_958_690_000 }
public macro fun S6_UP_ATM(): u64 { 491_915_056 }
public macro fun S6_DN_ATM(): u64 { 508_084_803 }
public macro fun S6_MTM_UP_ATM(): u64 { 4_919_150 }
public macro fun S6_MTM_DN_ATM(): u64 { 5_080_848 }
public macro fun S6_STRIKE_OTM5(): u64 { 75_776_356_624_500 }
public macro fun S6_UP_OTM5(): u64 { 106_294_469 }
public macro fun S6_DN_OTM5(): u64 { 893_705_391 }
public macro fun S6_MTM_UP_OTM5(): u64 { 1_062_944 }
public macro fun S6_MTM_DN_OTM5(): u64 { 8_937_053 }
public macro fun S6_STRIKE_OTM10(): u64 { 79_384_754_559_000 }
public macro fun S6_UP_OTM10(): u64 { 12_586_700 }
public macro fun S6_DN_OTM10(): u64 { 987_413_159 }
public macro fun S6_MTM_UP_OTM10(): u64 { 125_867 }
public macro fun S6_MTM_DN_OTM10(): u64 { 9_874_131 }
public macro fun S6_STRIKE_ITM5(): u64 { 68_559_560_755_500 }
public macro fun S6_UP_ITM5(): u64 { 850_904_533 }
public macro fun S6_DN_ITM5(): u64 { 149_095_326 }
public macro fun S6_MTM_UP_ITM5(): u64 { 8_509_045 }
public macro fun S6_MTM_DN_ITM5(): u64 { 1_490_953 }
public macro fun S6_STRIKE_ITM10(): u64 { 64_951_162_821_000 }
public macro fun S6_UP_ITM10(): u64 { 963_418_037 }
public macro fun S6_DN_ITM10(): u64 { 36_581_823 }
public macro fun S6_MTM_UP_ITM10(): u64 { 9_634_180 }
public macro fun S6_MTM_DN_ITM10(): u64 { 365_818 }

// --- S7: spot=72137.86, forward=72167.96, tte=31s ---
public macro fun S7_SPOT(): u64 { 72_137_857_040_000 }
public macro fun S7_FORWARD(): u64 { 72_167_958_690_000 }
public macro fun S7_A(): u64 { 770_000 }
public macro fun S7_B(): u64 { 15_490_000 }
public macro fun S7_RHO(): u64 { 399_060_000 }
public macro fun S7_RHO_NEG(): u64 { 1 }
public macro fun S7_M(): u64 { 4_540_000 }
public macro fun S7_M_NEG(): u64 { 0 }
public macro fun S7_SIGMA(): u64 { 54_360_000 }
public macro fun S7_RATE(): u64 { 35_000_000 }
public macro fun S7_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun S7_NOW_MS(): u64 { 1_773_842_971_565 }
public macro fun S7_STRIKE_ATM(): u64 { 72_167_958_690_000 }
public macro fun S7_UP_ATM(): u64 { 491_915_108 }
public macro fun S7_DN_ATM(): u64 { 508_084_857 }
public macro fun S7_MTM_UP_ATM(): u64 { 4_919_151 }
public macro fun S7_MTM_DN_ATM(): u64 { 5_080_848 }
public macro fun S7_STRIKE_OTM5(): u64 { 75_776_356_624_500 }
public macro fun S7_UP_OTM5(): u64 { 106_294_480 }
public macro fun S7_DN_OTM5(): u64 { 893_705_485 }
public macro fun S7_MTM_UP_OTM5(): u64 { 1_062_944 }
public macro fun S7_MTM_DN_OTM5(): u64 { 8_937_054 }
public macro fun S7_STRIKE_OTM10(): u64 { 79_384_754_559_000 }
public macro fun S7_UP_OTM10(): u64 { 12_586_702 }
public macro fun S7_DN_OTM10(): u64 { 987_413_263 }
public macro fun S7_MTM_UP_OTM10(): u64 { 125_867 }
public macro fun S7_MTM_DN_OTM10(): u64 { 9_874_132 }
public macro fun S7_STRIKE_ITM5(): u64 { 68_559_560_755_500 }
public macro fun S7_UP_ITM5(): u64 { 850_904_623 }
public macro fun S7_DN_ITM5(): u64 { 149_095_342 }
public macro fun S7_MTM_UP_ITM5(): u64 { 8_509_046 }
public macro fun S7_MTM_DN_ITM5(): u64 { 1_490_953 }
public macro fun S7_STRIKE_ITM10(): u64 { 64_951_162_821_000 }
public macro fun S7_UP_ITM10(): u64 { 963_418_138 }
public macro fun S7_DN_ITM10(): u64 { 36_581_826 }
public macro fun S7_MTM_UP_ITM10(): u64 { 9_634_181 }
public macro fun S7_MTM_DN_ITM10(): u64 { 365_818 }
