#!/usr/bin/env python3
"""
Generates generated_math.move with ground-truth test constants for
ln, exp, and normal_cdf.

Pure Python/scipy math — no FLOAT_SCALING in calculations. Scaling to
the contract's 1e9 fixed-point representation happens only at the output
layer when writing the .move file.

Source of truth:
- scipy.stats.norm for normal CDF
- Python math for ln/exp

Usage: python3 generate_math.py
Dependencies: pip install scipy
"""

import math
from pathlib import Path

from scipy.stats import norm

# ====================================================================
# Constants
# ====================================================================

FLOAT_SCALING = 1_000_000_000  # only used at the output layer
USDC_SCALING = 1_000_000  # 6 decimals: 1_000_000 = $1

DATA_DIR = Path(__file__).parent
MATH_OUTPUT = DATA_DIR / "generated_math.move"

# Protocol quote bounds: only produce quotes between 0.1c and 99.9c
MIN_QUOTE_PRICE = 0.001  # 0.1 cent
MAX_QUOTE_PRICE = 0.999  # 99.9 cents

# Block Scholes provider SVI parameter bounds.
SVI_B_MAX = 1.0
SVI_RHO_MAX_ABS = 0.95
SVI_SIGMA_MAX = 100.0

# Conservative upper bound on 'a'
A_MAX_CONSERVATIVE = 1.0

# Max risk-free rate and time to expiry we support
MAX_RATE = 0.15
MAX_TIME_YEARS = 1.0


# ====================================================================
# Scaling helpers
# ====================================================================


def to_float_scaled(value: float) -> int:
    """Convert a price/percentage/strike to FLOAT_SCALING (1e9), floor-truncated."""
    return int(value * FLOAT_SCALING)


def to_usdc(value: float) -> int:
    """Convert a dollar amount/quantity to USDC units (1e6), floor-truncated."""
    return int(value * USDC_SCALING)


# ====================================================================
# Move file writer
# ====================================================================


class MoveWriter:
    """Builds a #[test_only] Move module with generated constants."""

    def __init__(self):
        self.lines: list[str] = []

    def header(self, module_name: str):
        self.lines.append("// DO NOT EDIT — generated by generate_math.py")
        self.lines.append(
            "// Source of truth: scipy.stats.norm + Python math"
        )
        self.lines.append(
            "// Regenerate: cd tests/generated_tests && python3 generate_math.py"
        )
        self.lines.append("")
        self.lines.append("#[test_only]")
        self.lines.append(f"module deepbook_predict::{module_name};")
        self.lines.append("")

    def comment(self, text: str):
        self.lines.append(f"// {text}")

    def blank(self):
        self.lines.append("")

    def section(self, title: str):
        self.blank()
        self.lines.append(f"// === {title} ===")

    def const(self, name: str, value: int, comment: str = ""):
        suffix = f" // {comment}" if comment else ""
        self.lines.append(f"public macro fun {name}(): u64 {{ {value:_} }}{suffix}")

    def write(self, path: Path):
        with open(path, "w") as f:
            f.write("\n".join(self.lines))
            f.write("\n")
        print(f"Wrote {path} ({len(self.lines)} lines)")


# ====================================================================
# Operating range analysis
# ====================================================================


def compute_smart_contract_bounds():
    """
    Derive on-chain validation constants from protocol quote bounds
    and provider SVI parameter bounds.

    Pricing pipeline (forward direction):
      SVI params → ln(strike/forward) → total_var → d2 → normal_cdf → price
      rate + time → exp(-rt) → discount
      final_price = discount * cdf(d2)

    We work backwards from the quote clamp to derive what each
    function's inputs must be bounded to.
    """

    # Derived: discount factor bounds
    MAX_RT = MAX_RATE * MAX_TIME_YEARS
    MIN_DISCOUNT = math.exp(-MAX_RT)

    # Derived: normal_cdf input bounds
    d2_at_min_quote = norm.ppf(MIN_QUOTE_PRICE)
    d2_at_max_quote = norm.ppf(MAX_QUOTE_PRICE)
    cdf_upper_with_discount = min(MAX_QUOTE_PRICE / MIN_DISCOUNT, 1.0)
    d2_at_max_with_discount = norm.ppf(min(cdf_upper_with_discount, 0.9999999))
    MAX_ABS_D2 = max(abs(d2_at_min_quote), abs(d2_at_max_quote),
                     abs(d2_at_max_with_discount))

    # Derived: exp bounds (inside cdf_pdf)
    MAX_EXP_CDF_INPUT = MAX_ABS_D2 ** 2 / 2

    # Derived: total variance bounds
    TV_MAX = A_MAX_CONSERVATIVE + SVI_B_MAX * SVI_SIGMA_MAX

    # Derived: ln bounds (strike/forward ratio)
    MAX_ABS_K = MAX_ABS_D2 * math.sqrt(TV_MAX) + TV_MAX / 2
    MAX_STRIKE_RATIO = math.exp(MAX_ABS_K)
    MIN_STRIKE_RATIO = math.exp(-MAX_ABS_K)

    bounds = {
        "on_chain_constants": {
            "max_abs_d2": to_float_scaled(MAX_ABS_D2),
            "min_quote": to_usdc(MIN_QUOTE_PRICE),
            "max_quote": to_usdc(MAX_QUOTE_PRICE),
        },
        "derived_info": {
            "d2_range_no_discount": (d2_at_min_quote, d2_at_max_quote),
            "d2_range_with_discount": (d2_at_min_quote, d2_at_max_with_discount),
            "max_abs_d2": MAX_ABS_D2,
            "min_discount": MIN_DISCOUNT,
            "max_exp_cdf_input": MAX_EXP_CDF_INPUT,
            "tv_max": TV_MAX,
            "max_abs_k": MAX_ABS_K,
            "strike_ratio_range": (MIN_STRIKE_RATIO, MAX_STRIKE_RATIO),
        },
    }

    return bounds


# ====================================================================
# Math constant generation
# ====================================================================


def generate_math_constants(w: MoveWriter, bounds: dict):
    max_abs_d2 = bounds["derived_info"]["max_abs_d2"]
    max_exp_input = bounds["derived_info"]["max_exp_cdf_input"]

    w.section("Math constants")

    w.const("LN2", to_float_scaled(math.log(2)), f"ln(2) = {math.log(2):.15f}")
    w.const("LN4", to_float_scaled(math.log(4)), f"ln(4) = {math.log(4):.15f}")
    w.const("LN8", to_float_scaled(math.log(8)), f"ln(8) = {math.log(8):.15f}")
    w.const("LN16", to_float_scaled(math.log(16)), f"ln(16) = {math.log(16):.15f}")
    w.const(
        "LN_1E9", to_float_scaled(math.log(1e9)), f"ln(1e9) = {math.log(1e9):.15f}"
    )
    w.const("E", to_float_scaled(math.e), f"e = {math.e:.15f}")
    w.const("E_INV", to_float_scaled(1.0 / math.e), f"1/e = {1 / math.e:.15f}")

    w.section("ln — non-trivial inputs (exercise ln_series with nonzero z)")
    for x in [1.5, 3.0, 5.0, 7.0, 10.0, 0.1, 0.3, 0.7, 0.999, 1.001, 100.0, 1000.0]:
        name = str(x).replace(".", "_")
        w.const(f"LN_{name}", to_float_scaled(abs(math.log(x))),
                f"|ln({x})| = {abs(math.log(x)):.15f}")

    w.section(
        f"exp — operating range: max input = {max_exp_input:.2f} "
        f"(from max |d2| = {max_abs_d2:.4f})"
    )
    exp_points = [0.001, 0.01, 0.1, 0.3, 0.5, 1.5, 2.5]
    exp_points.append(round(max_exp_input * 0.5, 1))
    exp_points.append(round(max_exp_input * 0.9, 1))
    exp_points = sorted(set(exp_points))

    for x in exp_points:
        name = str(x).replace(".", "_")
        w.const(f"EXP_{name}", to_float_scaled(math.exp(x)),
                f"e^{x} = {math.exp(x):.15f}")
        w.const(f"EXP_NEG_{name}", to_float_scaled(math.exp(-x)),
                f"e^(-{x}) = {math.exp(-x):.15f}")

    w.section(
        f"Normal CDF — operating range: |d2| <= {max_abs_d2:.4f} "
        f"(from {MIN_QUOTE_PRICE*100:.1f}c—{MAX_QUOTE_PRICE*100:.1f}c quote bounds)"
    )

    cdf_points = [0, 0.01, 0.05, 0.1, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0]
    cdf_boundary = round(max_abs_d2, 2)
    if cdf_boundary not in cdf_points:
        cdf_points.append(cdf_boundary)
    cdf_points.append(8.0)
    cdf_points = sorted(set(cdf_points))

    for x in cdf_points:
        name = str(x).replace(".", "_")
        w.const(f"PHI_{name}", to_float_scaled(norm.cdf(x)), f"Φ({x})")
        w.const(f"PHI_NEG_{name}", to_float_scaled(norm.cdf(-x)), f"Φ(-{x})")


# ====================================================================
# Main
# ====================================================================


def main():
    bounds = compute_smart_contract_bounds()

    w = MoveWriter()
    w.header("generated_math")
    generate_math_constants(w, bounds)
    w.write(MATH_OUTPUT)


if __name__ == "__main__":
    main()
