// DO NOT EDIT — generated by generate.py
// Source of truth: scipy.stats.norm + Python math
// Regenerate: cd tests/generated_tests && python3 generate.py && bunx prettier-move -c *.move --write

#[test_only]
module deepbook_predict::generated_predict;

public struct TradeCase has copy, drop {
    strike: u64,
    quantity: u64,
    is_up: bool,
    expected_cost: u64,
    expected_redeem_payout: u64,
}

public struct PredictScenario has copy, drop {
    oracle_scenario_idx: u64,
    trade_cases: vector<TradeCase>,
}

public fun oracle_scenario_idx(s: &PredictScenario): u64 { s.oracle_scenario_idx }

public fun trade_cases(s: &PredictScenario): &vector<TradeCase> { &s.trade_cases }

public fun strike(tc: &TradeCase): u64 { tc.strike }

public fun quantity(tc: &TradeCase): u64 { tc.quantity }

public fun is_up(tc: &TradeCase): bool { tc.is_up }

public fun expected_cost(tc: &TradeCase): u64 { tc.expected_cost }

public fun expected_redeem_payout(tc: &TradeCase): u64 { tc.expected_redeem_payout }

public fun scenarios(): vector<PredictScenario> {
    vector[
        // Index 0: S0
        PredictScenario {
            oracle_scenario_idx: 7,
            trade_cases: vector[
                TradeCase {
                    strike: 70_782_876_450_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 4_940_319,
                    expected_redeem_payout: 4_740_421,
                },
                TradeCase {
                    strike: 70_782_876_450_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 5_259_578,
                    expected_redeem_payout: 5_059_680,
                },
                TradeCase {
                    strike: 77_861_234_880_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 1_168_186,
                    expected_redeem_payout: 1_042_758,
                },
                TradeCase {
                    strike: 63_704_659_590_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 8_573_477,
                    expected_redeem_payout: 8_430_731,
                },
                TradeCase {
                    strike: 63_704_659_590_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 1_569_268,
                    expected_redeem_payout: 1_426_522,
                },
                TradeCase {
                    strike: 70_782_876_450_000,
                    quantity: 1_000,
                    is_up: true,
                    expected_cost: 494,
                    expected_redeem_payout: 474,
                },
                TradeCase {
                    strike: 70_782_876_450_000,
                    quantity: 500_000_000,
                    is_up: true,
                    expected_cost: 247_015_957,
                    expected_redeem_payout: 237_021_055,
                },
            ],
        },
        // Index 1: S1
        PredictScenario {
            oracle_scenario_idx: 8,
            trade_cases: vector[
                TradeCase {
                    strike: 74_241_436_240_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 4_999_549,
                    expected_redeem_payout: 4_799_589,
                },
                TradeCase {
                    strike: 74_241_436_240_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 5_200_410,
                    expected_redeem_payout: 5_000_450,
                },
                TradeCase {
                    strike: 81_665_639_260_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 421_214,
                    expected_redeem_payout: 321_214,
                },
                TradeCase {
                    strike: 66_817_381_710_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 9_339_069,
                    expected_redeem_payout: 9_236_180,
                },
                TradeCase {
                    strike: 66_817_381_710_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 763_819,
                    expected_redeem_payout: 660_930,
                },
                TradeCase {
                    strike: 74_241_436_240_000,
                    quantity: 1_000,
                    is_up: true,
                    expected_cost: 499,
                    expected_redeem_payout: 479,
                },
                TradeCase {
                    strike: 74_241_436_240_000,
                    quantity: 500_000_000,
                    is_up: true,
                    expected_cost: 249_977_467,
                    expected_redeem_payout: 239_979_484,
                },
            ],
        },
        // Index 2: S3
        PredictScenario {
            oracle_scenario_idx: 10,
            trade_cases: vector[
                TradeCase {
                    strike: 72_523_259_400_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 5_018_932,
                    expected_redeem_payout: 4_818_959,
                },
                TradeCase {
                    strike: 72_523_259_400_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 5_181_040,
                    expected_redeem_payout: 4_981_067,
                },
                TradeCase {
                    strike: 79_775_614_350_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 162_659,
                    expected_redeem_payout: 62_659,
                },
                TradeCase {
                    strike: 65_270_904_450_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 9_735_714,
                    expected_redeem_payout: 9_635_714,
                },
                TradeCase {
                    strike: 65_270_904_450_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 364_285,
                    expected_redeem_payout: 264_285,
                },
                TradeCase {
                    strike: 72_523_259_400_000,
                    quantity: 1_000,
                    is_up: true,
                    expected_cost: 501,
                    expected_redeem_payout: 481,
                },
                TradeCase {
                    strike: 72_523_259_400_000,
                    quantity: 500_000_000,
                    is_up: true,
                    expected_cost: 250_946_642,
                    expected_redeem_payout: 240_947_956,
                },
            ],
        },
        // Index 3: S4
        PredictScenario {
            oracle_scenario_idx: 11,
            trade_cases: vector[
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 5_019_110,
                    expected_redeem_payout: 4_819_136,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 5_180_863,
                    expected_redeem_payout: 4_980_889,
                },
                TradeCase {
                    strike: 79_384_690_560_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 175_872,
                    expected_redeem_payout: 75_872,
                },
                TradeCase {
                    strike: 64_951_123_580_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 9_684_187,
                    expected_redeem_payout: 9_584_187,
                },
                TradeCase {
                    strike: 64_951_123_580_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 415_812,
                    expected_redeem_payout: 315_812,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 1_000,
                    is_up: true,
                    expected_cost: 501,
                    expected_redeem_payout: 481,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 500_000_000,
                    is_up: true,
                    expected_cost: 250_955_509,
                    expected_redeem_payout: 240_956_818,
                },
            ],
        },
        // Index 4: S5
        PredictScenario {
            oracle_scenario_idx: 12,
            trade_cases: vector[
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 5_019_110,
                    expected_redeem_payout: 4_819_136,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 5_180_863,
                    expected_redeem_payout: 4_980_889,
                },
                TradeCase {
                    strike: 79_384_690_560_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 175_872,
                    expected_redeem_payout: 75_872,
                },
                TradeCase {
                    strike: 64_951_123_580_000,
                    quantity: 10_000_000,
                    is_up: true,
                    expected_cost: 9_684_187,
                    expected_redeem_payout: 9_584_187,
                },
                TradeCase {
                    strike: 64_951_123_580_000,
                    quantity: 10_000_000,
                    is_up: false,
                    expected_cost: 415_812,
                    expected_redeem_payout: 315_812,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 1_000,
                    is_up: true,
                    expected_cost: 501,
                    expected_redeem_payout: 481,
                },
                TradeCase {
                    strike: 72_167_979_240_000,
                    quantity: 500_000_000,
                    is_up: true,
                    expected_cost: 250_955_509,
                    expected_redeem_payout: 240_956_818,
                },
            ],
        },
    ]
}
