#!/usr/bin/env python3
"""
Generates generated_math.move with ground-truth test constants for
ln, exp, and normal_cdf.

Pure Python/scipy math — no FLOAT_SCALING in calculations. Scaling to
the contract's 1e9 fixed-point representation happens only at the output
layer when writing the .move file.

Produces:
- Named macro constants for hand-written property tests (ln(2), e, etc.)
- Vector-of-struct test cases with randomized inputs for broad coverage

Source of truth:
- scipy.stats.norm for normal CDF
- Python math for ln/exp

Usage: python3 generate_math.py
Dependencies: pip install scipy
"""

import math
import random
from pathlib import Path

from scipy.stats import norm

# ====================================================================
# Constants
# ====================================================================

FLOAT_SCALING = 1_000_000_000

DATA_DIR = Path(__file__).parent
MATH_OUTPUT = DATA_DIR / "generated_math.move"

# Deterministic seed for reproducible test vectors
SEED = 42

# Number of randomized test cases per function
N_LN_CASES = 200
N_EXP_CASES = 200
N_CDF_CASES = 200

U64_MAX = 2**64 - 1

# ln: any u64 > 0 is valid. Sample log-uniformly across the full range.
LN_EXP_MIN = -9    # 10^-9 → input = 1 (minimum valid)
LN_EXP_MAX = 10    # 10^10 → input ≈ 1e19 (near u64_max)

# exp positive: contract aborts at MAX_EXP_INPUT + 1 = 23_638_153_700.
# We generate valid cases up to the boundary and overflow cases above it.
MAX_EXP_INPUT = 23_638_153_699
N_EXP_OVERFLOW_CASES = 20  # cases that should abort with EExpOverflow

# exp negative: any u64 is valid (gracefully returns 0 for large inputs).
# Sample up to u64_max.
EXP_NEG_MAX_INPUT = U64_MAX

# normal_cdf: any u64 is valid (clamps at 8*FLOAT internally).
# Sample up to u64_max.
CDF_MAX_INPUT = U64_MAX


# ====================================================================
# Scaling helpers
# ====================================================================


def to_float_scaled(value: float) -> int:
    """Convert to FLOAT_SCALING (1e9), floor-truncated."""
    return int(value * FLOAT_SCALING)


def fmt_u64(value: int) -> str:
    """Format an integer with underscore separators for Move readability."""
    return f"{value:_}"


# ====================================================================
# Move file writer
# ====================================================================


class MoveWriter:
    """Builds a #[test_only] Move module with generated constants."""

    def __init__(self):
        self.lines: list[str] = []

    def header(self, module_name: str):
        self.lines.append("// DO NOT EDIT — generated by generate_math.py")
        self.lines.append("// Source of truth: scipy.stats.norm + Python math")
        self.lines.append(
            "// Regenerate: cd tests/generated_tests && python3 generate_math.py"
        )
        self.lines.append("")
        self.lines.append("#[test_only]")
        self.lines.append(f"module deepbook_predict::{module_name};")
        self.lines.append("")

    def comment(self, text: str):
        self.lines.append(f"// {text}")

    def blank(self):
        self.lines.append("")

    def section(self, title: str):
        self.blank()
        self.lines.append(f"// === {title} ===")

    def const(self, name: str, value: int, comment: str = ""):
        suffix = f" // {comment}" if comment else ""
        self.lines.append(
            f"public macro fun {name}(): u64 {{ {fmt_u64(value)} }}{suffix}"
        )

    def raw(self, text: str):
        self.lines.append(text)

    def write(self, path: Path):
        with open(path, "w") as f:
            f.write("\n".join(self.lines))
            f.write("\n")
        print(f"Wrote {path} ({len(self.lines)} lines)")


# ====================================================================
# Named constants (for hand-written property tests)
# ====================================================================


def emit_named_constants(w: MoveWriter):
    """Emit constants used by hand-written property tests (mathematical identities)."""
    w.section("Math constants")
    w.const("LN2", to_float_scaled(math.log(2)), f"ln(2) = {math.log(2):.15f}")
    w.const("LN4", to_float_scaled(math.log(4)), f"ln(4) = {math.log(4):.15f}")
    w.const("LN8", to_float_scaled(math.log(8)), f"ln(8) = {math.log(8):.15f}")
    w.const("LN16", to_float_scaled(math.log(16)), f"ln(16) = {math.log(16):.15f}")
    w.const(
        "LN_1E9",
        to_float_scaled(math.log(1e9)),
        f"ln(1e9) = {math.log(1e9):.15f}",
    )
    w.const("E", to_float_scaled(math.e), f"e = {math.e:.15f}")
    w.const("E_INV", to_float_scaled(1.0 / math.e), f"1/e = {1 / math.e:.15f}")


# ====================================================================
# Randomized test vectors
# ====================================================================


def emit_ln_vector(w: MoveWriter, rng: random.Random):
    """Generate ln test cases sampling the full u64 domain (x > 0).

    We sample log-uniformly via 10^exp to get even coverage across
    orders of magnitude, from x=1 (minimum valid) to near u64_max.
    """
    w.section(f"ln test vector ({N_LN_CASES} randomized cases)")
    w.blank()
    w.raw("public struct LnCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    expected_mag: u64,")
    w.raw("    expected_neg: bool,")
    w.raw("}")
    w.blank()
    w.raw("public fun ln_input(c: &LnCase): u64 { c.input }")
    w.raw("public fun ln_expected_mag(c: &LnCase): u64 { c.expected_mag }")
    w.raw("public fun ln_expected_neg(c: &LnCase): bool { c.expected_neg }")
    w.blank()
    w.raw("public fun ln_cases(): vector<LnCase> { vector[")

    for _ in range(N_LN_CASES):
        exp = rng.uniform(LN_EXP_MIN, LN_EXP_MAX)
        x_float = 10 ** exp
        x_scaled = max(1, to_float_scaled(x_float))

        # Recompute from scaled integer to match what the contract receives
        x_actual = x_scaled / FLOAT_SCALING
        ln_val = math.log(x_actual)
        mag = to_float_scaled(abs(ln_val))
        neg = "true" if ln_val < 0 else "false"

        w.raw(
            f"    LnCase {{ input: {fmt_u64(x_scaled)}, "
            f"expected_mag: {fmt_u64(mag)}, expected_neg: {neg} }},"
        )

    w.raw("]}")


def emit_exp_vector(w: MoveWriter, rng: random.Random):
    """Generate exp test cases sampling the full valid domain.

    Positive: uniform over [0, MAX_EXP_INPUT] (valid inputs).
    Negative: uniform over [0, u64_max] (all valid, gracefully returns 0).
    """
    w.section(f"exp test vector ({N_EXP_CASES} valid + {N_EXP_OVERFLOW_CASES} overflow cases)")
    w.blank()
    w.raw("public struct ExpCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    is_negative: bool,")
    w.raw("    expected: u64,")
    w.raw("}")
    w.blank()
    w.raw("public fun exp_input(c: &ExpCase): u64 { c.input }")
    w.raw("public fun exp_is_negative(c: &ExpCase): bool { c.is_negative }")
    w.raw("public fun exp_expected(c: &ExpCase): u64 { c.expected }")
    w.blank()

    # Valid positive cases: [0, MAX_EXP_INPUT]
    w.raw("public fun exp_cases(): vector<ExpCase> { vector[")
    half = N_EXP_CASES // 2
    for _ in range(half):
        x_scaled = rng.randint(0, MAX_EXP_INPUT)
        expected = to_float_scaled(math.exp(x_scaled / FLOAT_SCALING))
        w.raw(
            f"    ExpCase {{ input: {fmt_u64(x_scaled)}, "
            f"is_negative: false, expected: {fmt_u64(expected)} }},"
        )

    # Valid negative cases: [0, u64_max]
    for _ in range(N_EXP_CASES - half):
        x_scaled = rng.randint(0, U64_MAX)
        expected = to_float_scaled(math.exp(-x_scaled / FLOAT_SCALING))
        w.raw(
            f"    ExpCase {{ input: {fmt_u64(x_scaled)}, "
            f"is_negative: true, expected: {fmt_u64(expected)} }},"
        )
    w.raw("]}")

    # Overflow cases: positive inputs above MAX_EXP_INPUT
    w.blank()
    w.raw("public fun exp_overflow_cases(): vector<u64> { vector[")
    for _ in range(N_EXP_OVERFLOW_CASES):
        x_scaled = rng.randint(MAX_EXP_INPUT + 1, U64_MAX)
        w.raw(f"    {fmt_u64(x_scaled)},")
    w.raw("]}")


def emit_cdf_vector(w: MoveWriter, rng: random.Random):
    """Generate normal_cdf test cases sampling the full u64 domain.

    All u64 inputs are valid. The contract clamps at 8*FLOAT, so inputs
    above that return FLOAT (positive) or 0 (negative). We sample the
    full range to verify both the polynomial and clamp paths.
    """
    w.section(f"Normal CDF test vector ({N_CDF_CASES} randomized cases)")
    w.blank()
    w.raw("public struct CdfCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    is_negative: bool,")
    w.raw("    expected: u64,")
    w.raw("}")
    w.blank()
    w.raw("public fun cdf_input(c: &CdfCase): u64 { c.input }")
    w.raw("public fun cdf_is_negative(c: &CdfCase): bool { c.is_negative }")
    w.raw("public fun cdf_expected(c: &CdfCase): u64 { c.expected }")
    w.blank()
    w.raw("public fun cdf_cases(): vector<CdfCase> { vector[")

    half = N_CDF_CASES // 2
    for i in range(N_CDF_CASES):
        x_scaled = rng.randint(0, U64_MAX)
        x_float = x_scaled / FLOAT_SCALING
        is_neg = i >= half
        # For inputs > 8, contract clamps to FLOAT or 0
        if x_float > 8.0:
            expected = 0 if is_neg else FLOAT_SCALING
        else:
            expected = to_float_scaled(norm.cdf(-x_float if is_neg else x_float))
        neg_str = "true" if is_neg else "false"
        w.raw(
            f"    CdfCase {{ input: {fmt_u64(x_scaled)}, "
            f"is_negative: {neg_str}, expected: {fmt_u64(expected)} }},"
        )

    w.raw("]}")


# ====================================================================
# Main
# ====================================================================


def main():
    rng = random.Random(SEED)

    w = MoveWriter()
    w.header("generated_math")

    emit_named_constants(w)
    emit_ln_vector(w, rng)
    emit_exp_vector(w, rng)
    emit_cdf_vector(w, rng)

    w.write(MATH_OUTPUT)


if __name__ == "__main__":
    main()
