// DO NOT EDIT — generated by generate.py
// Source of truth: scipy.stats.norm + Python math
// Regenerate: cd tests/generated_tests && python3 generate.py && bunx prettier-move -c *.move --write

#[test_only]
module deepbook_predict::generated_oracle;

public struct StrikePoint has copy, drop {
    strike: u64,
    expected_up: u64,
    expected_dn: u64,
}

public struct OracleScenario has copy, drop {
    spot: u64,
    forward: u64,
    a: u64,
    b: u64,
    rho: u64,
    rho_neg: bool,
    m: u64,
    m_neg: bool,
    sigma: u64,
    rate: u64,
    expiry_ms: u64,
    now_ms: u64,
    min_strike: u64,
    max_strike: u64,
    tick_size: u64,
    strike_points: vector<StrikePoint>,
}

public fun spot(s: &OracleScenario): u64 { s.spot }

public fun forward(s: &OracleScenario): u64 { s.forward }

public fun a(s: &OracleScenario): u64 { s.a }

public fun b(s: &OracleScenario): u64 { s.b }

public fun rho(s: &OracleScenario): u64 { s.rho }

public fun rho_neg(s: &OracleScenario): bool { s.rho_neg }

public fun m(s: &OracleScenario): u64 { s.m }

public fun m_neg(s: &OracleScenario): bool { s.m_neg }

public fun sigma(s: &OracleScenario): u64 { s.sigma }

public fun rate(s: &OracleScenario): u64 { s.rate }

public fun expiry_ms(s: &OracleScenario): u64 { s.expiry_ms }

public fun now_ms(s: &OracleScenario): u64 { s.now_ms }

public fun min_strike(s: &OracleScenario): u64 { s.min_strike }

public fun max_strike(s: &OracleScenario): u64 { s.max_strike }

public fun tick_size(s: &OracleScenario): u64 { s.tick_size }

public fun strike_points(s: &OracleScenario): &vector<StrikePoint> { &s.strike_points }

public fun strike(sp: &StrikePoint): u64 { sp.strike }

public fun expected_up(sp: &StrikePoint): u64 { sp.expected_up }

public fun expected_dn(sp: &StrikePoint): u64 { sp.expected_dn }

public fun scenarios(): vector<OracleScenario> {
    vector[
        // Index 0: STD
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 0,
            b: 1_000_000_000,
            rho: 0,
            rho_neg: false,
            m: 0,
            m_neg: false,
            sigma: 250_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 1_075_140_000,
            max_strike: 595_075_140_000,
            tick_size: 5_940_000,
            strike_points: vector[
                StrikePoint {
                    strike: 1_787_940_000,
                    expected_up: 841_371_696,
                    expected_dn: 158_628_303,
                },
                StrikePoint {
                    strike: 86_557_680_000,
                    expected_up: 500_012_031,
                    expected_dn: 499_987_968,
                },
                StrikePoint {
                    strike: 158_746_500_000,
                    expected_up: 158_659_005,
                    expected_dn: 841_340_994,
                },
                StrikePoint {
                    strike: 595_075_140_000,
                    expected_up: 22_750_051,
                    expected_dn: 977_249_948,
                },
            ],
        },
        // Index 1: STD_5PCT_1YR
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 0,
            b: 1_000_000_000,
            rho: 0,
            rho_neg: false,
            m: 0,
            m_neg: false,
            sigma: 250_000_000,
            rate: 50_000_000,
            expiry_ms: 31_536_000_000,
            now_ms: 0,
            min_strike: 1_075_140_000,
            max_strike: 595_075_140_000,
            tick_size: 5_940_000,
            strike_points: vector[
                StrikePoint {
                    strike: 1_787_940_000,
                    expected_up: 841_371_696,
                    expected_dn: 158_628_303,
                },
                StrikePoint {
                    strike: 86_557_680_000,
                    expected_up: 500_012_031,
                    expected_dn: 499_987_968,
                },
                StrikePoint {
                    strike: 158_746_500_000,
                    expected_up: 158_659_005,
                    expected_dn: 841_340_994,
                },
                StrikePoint {
                    strike: 595_075_140_000,
                    expected_up: 22_750_051,
                    expected_dn: 977_249_948,
                },
            ],
        },
        // Index 2: FULL_SVI
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 50_000_000,
            b: 800_000_000,
            rho: 300_000_000,
            rho_neg: true,
            m: 100_000_000,
            m_neg: false,
            sigma: 200_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 99_000_010_000,
            max_strike: 100_000_010_000,
            tick_size: 10_000,
            strike_points: vector[
                StrikePoint {
                    strike: 100_000_000_000,
                    expected_up: 400_737_521,
                    expected_dn: 599_262_478,
                },
            ],
        },
        // Index 3: SMALL_SIGMA
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 0,
            b: 1_000_000_000,
            rho: 0,
            rho_neg: false,
            m: 0,
            m_neg: false,
            sigma: 10_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 99_000_010_000,
            max_strike: 100_000_010_000,
            tick_size: 10_000,
            strike_points: vector[
                StrikePoint {
                    strike: 100_000_000_000,
                    expected_up: 480_061_194,
                    expected_dn: 519_938_805,
                },
            ],
        },
        // Index 4: NONZERO_A
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 100_000_000,
            b: 1_000_000_000,
            rho: 0,
            rho_neg: false,
            m: 0,
            m_neg: false,
            sigma: 250_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 99_000_010_000,
            max_strike: 100_000_010_000,
            tick_size: 10_000,
            strike_points: vector[
                StrikePoint {
                    strike: 100_000_000_000,
                    expected_up: 383_689_888,
                    expected_dn: 616_310_111,
                },
            ],
        },
        // Index 5: NEG_RHO
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 0,
            b: 1_000_000_000,
            rho: 300_000_000,
            rho_neg: true,
            m: 0,
            m_neg: false,
            sigma: 250_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 83_074_680_000,
            max_strike: 471_074_680_000,
            tick_size: 3_880_000,
            strike_points: vector[
                StrikePoint {
                    strike: 83_373_440_000,
                    expected_up: 499_997_113,
                    expected_dn: 500_002_886,
                },
                StrikePoint {
                    strike: 152_367_600_000,
                    expected_up: 158_656_117,
                    expected_dn: 841_343_882,
                },
                StrikePoint {
                    strike: 471_074_680_000,
                    expected_up: 22_750_126,
                    expected_dn: 977_249_873,
                },
            ],
        },
        // Index 6: NONZERO_M
        OracleScenario {
            spot: 100_000_000_000,
            forward: 100_000_000_000,
            a: 0,
            b: 1_000_000_000,
            rho: 0,
            rho_neg: false,
            m: 100_000_000,
            m_neg: false,
            sigma: 250_000_000,
            rate: 0,
            expiry_ms: 1_000_000,
            now_ms: 0,
            min_strike: 872_480_000,
            max_strike: 574_872_480_000,
            tick_size: 5_740_000,
            strike_points: vector[
                StrikePoint {
                    strike: 1_343_160_000,
                    expected_up: 841_323_194,
                    expected_dn: 158_676_805,
                },
                StrikePoint {
                    strike: 82_506_760_000,
                    expected_up: 499_986_741,
                    expected_dn: 500_013_258,
                },
                StrikePoint {
                    strike: 154_997_220_000,
                    expected_up: 158_655_175,
                    expected_dn: 841_344_824,
                },
                StrikePoint {
                    strike: 574_866_740_000,
                    expected_up: 22_750_205,
                    expected_dn: 977_249_794,
                },
            ],
        },
        // Index 7: S0
        OracleScenario {
            spot: 70_770_295_760_000,
            forward: 70_782_878_010_000,
            a: 1_080_000,
            b: 42_280_000,
            rho: 332_660_000,
            rho_neg: true,
            m: 3_020_000,
            m_neg: true,
            sigma: 126_980_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_241_327_070,
            min_strike: 63_704_659_590_000,
            max_strike: 77_861_659_590_000,
            tick_size: 141_570_000,
            strike_points: vector[
                StrikePoint {
                    strike: 63_704_659_590_000,
                    expected_up: 850_210_424,
                    expected_dn: 149_789_575,
                },
                StrikePoint {
                    strike: 67_243_768_020_000,
                    expected_up: 708_452_607,
                    expected_dn: 291_547_392,
                },
                StrikePoint {
                    strike: 70_782_876_450_000,
                    expected_up: 484_037_012,
                    expected_dn: 515_962_987,
                },
                StrikePoint {
                    strike: 74_321_984_880_000,
                    expected_up: 254_188_138,
                    expected_dn: 745_811_861,
                },
                StrikePoint {
                    strike: 77_861_234_880_000,
                    expected_up: 110_547_223,
                    expected_dn: 889_452_776,
                },
            ],
        },
        // Index 8: S1
        OracleScenario {
            spot: 74_228_286_720_000,
            forward: 74_241_496_580_000,
            a: 550_000,
            b: 26_870_000,
            rho: 360_900_000,
            rho_neg: true,
            m: 4_160_000,
            m_neg: true,
            sigma: 75_400_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_735_844_810,
            min_strike: 66_817_381_710_000,
            max_strike: 81_666_381_710_000,
            tick_size: 148_490_000,
            strike_points: vector[
                StrikePoint {
                    strike: 66_817_381_710_000,
                    expected_up: 928_762_514,
                    expected_dn: 71_237_485,
                },
                StrikePoint {
                    strike: 70_529_483_220_000,
                    expected_up: 802_613_996,
                    expected_dn: 197_386_003,
                },
                StrikePoint {
                    strike: 74_241_436_240_000,
                    expected_up: 489_956_951,
                    expected_dn: 510_043_048,
                },
                StrikePoint {
                    strike: 77_953_537_750_000,
                    expected_up: 159_022_073,
                    expected_dn: 840_977_926,
                },
                StrikePoint {
                    strike: 81_665_639_260_000,
                    expected_up: 37_121_418,
                    expected_dn: 962_878_581,
                },
            ],
        },
        // Index 9: S2
        OracleScenario {
            spot: 74_105_490_370_000,
            forward: 74_127_848_210_000,
            a: 960_000,
            b: 12_900_000,
            rho: 640_610_000,
            rho_neg: true,
            m: 16_010_000,
            m_neg: true,
            sigma: 31_180_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_825_103_183,
            min_strike: 66_715_072_620_000,
            max_strike: 81_541_072_620_000,
            tick_size: 148_260_000,
            strike_points: vector[
                StrikePoint {
                    strike: 66_715_072_620_000,
                    expected_up: 972_762_840,
                    expected_dn: 27_237_159,
                },
                StrikePoint {
                    strike: 70_421_424_360_000,
                    expected_up: 878_618_472,
                    expected_dn: 121_381_527,
                },
                StrikePoint {
                    strike: 74_127_776_100_000,
                    expected_up: 492_875_163,
                    expected_dn: 507_124_836,
                },
                StrikePoint {
                    strike: 77_834_276_100_000,
                    expected_up: 89_274_223,
                    expected_dn: 910_725_776,
                },
                StrikePoint {
                    strike: 81_540_627_840_000,
                    expected_up: 7_041_603,
                    expected_dn: 992_958_396,
                },
            ],
        },
        // Index 10: S3
        OracleScenario {
            spot: 72_385_193_560_000,
            forward: 72_523_227_120_000,
            a: 1_050_000,
            b: 12_360_000,
            rho: 526_610_000,
            rho_neg: true,
            m: 3_690_000,
            m_neg: true,
            sigma: 50_320_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_838_922_225,
            min_strike: 65_270_904_450_000,
            max_strike: 79_775_904_450_000,
            tick_size: 145_050_000,
            strike_points: vector[
                StrikePoint {
                    strike: 65_270_904_450_000,
                    expected_up: 968_571_444,
                    expected_dn: 31_428_555,
                },
                StrikePoint {
                    strike: 68_897_009_400_000,
                    expected_up: 856_810_021,
                    expected_dn: 143_189_978,
                },
                StrikePoint {
                    strike: 72_523_259_400_000,
                    expected_up: 491_894_599,
                    expected_dn: 508_105_400,
                },
                StrikePoint {
                    strike: 76_149_364_350_000,
                    expected_up: 108_023_926,
                    expected_dn: 891_976_073,
                },
                StrikePoint {
                    strike: 79_775_614_350_000,
                    expected_up: 11_265_982,
                    expected_dn: 988_734_017,
                },
            ],
        },
        // Index 11: S4
        OracleScenario {
            spot: 72_137_857_040_000,
            forward: 72_167_958_690_000,
            a: 770_000,
            b: 15_490_000,
            rho: 399_060_000,
            rho_neg: true,
            m: 4_540_000,
            m_neg: false,
            sigma: 54_360_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_842_876_472,
            min_strike: 64_951_123_580_000,
            max_strike: 79_385_123_580_000,
            tick_size: 144_340_000,
            strike_points: vector[
                StrikePoint {
                    strike: 64_951_123_580_000,
                    expected_up: 963_418_740,
                    expected_dn: 36_581_259,
                },
                StrikePoint {
                    strike: 68_559_623_580_000,
                    expected_up: 850_901_098,
                    expected_dn: 149_098_901,
                },
                StrikePoint {
                    strike: 72_167_979_240_000,
                    expected_up: 491_912_328,
                    expected_dn: 508_087_671,
                },
                StrikePoint {
                    strike: 75_776_334_900_000,
                    expected_up: 106_295_733,
                    expected_dn: 893_704_266,
                },
                StrikePoint {
                    strike: 79_384_690_560_000,
                    expected_up: 12_587_202,
                    expected_dn: 987_412_797,
                },
            ],
        },
        // Index 12: S5
        OracleScenario {
            spot: 72_137_857_040_000,
            forward: 72_167_958_690_000,
            a: 770_000,
            b: 15_490_000,
            rho: 399_060_000,
            rho_neg: true,
            m: 4_540_000,
            m_neg: false,
            sigma: 54_360_000,
            rate: 35_000_000,
            expiry_ms: 1_773_843_002_405,
            now_ms: 1_773_842_971_565,
            min_strike: 64_951_123_580_000,
            max_strike: 79_385_123_580_000,
            tick_size: 144_340_000,
            strike_points: vector[
                StrikePoint {
                    strike: 64_951_123_580_000,
                    expected_up: 963_418_740,
                    expected_dn: 36_581_259,
                },
                StrikePoint {
                    strike: 68_559_623_580_000,
                    expected_up: 850_901_098,
                    expected_dn: 149_098_901,
                },
                StrikePoint {
                    strike: 72_167_979_240_000,
                    expected_up: 491_912_328,
                    expected_dn: 508_087_671,
                },
                StrikePoint {
                    strike: 75_776_334_900_000,
                    expected_up: 106_295_733,
                    expected_dn: 893_704_266,
                },
                StrikePoint {
                    strike: 79_384_690_560_000,
                    expected_up: 12_587_202,
                    expected_dn: 987_412_797,
                },
            ],
        },
    ]
}
