// DO NOT EDIT — generated by generate.py
// Source of truth: scipy.stats.norm + Black-Scholes + SVI
// Regenerate: cd tests/generated_tests && python3 generate.py

#[test_only]
module deepbook_predict::generated_predict;


// === Mint pricing scenarios from real Block Scholes data ===
// Same snapshots as oracle scenarios, with spread + cost calculations.
// Default config: base_spread=0.02, min_spread=0.005, util_mult=2.0

// --- M0: spot=70770.30, forward=70782.88, tte=7.0d ---
public macro fun M0_SPOT(): u64 { 70_770_295_760_000 }
public macro fun M0_FORWARD(): u64 { 70_782_878_010_000 }
public macro fun M0_A(): u64 { 1_080_000 }
public macro fun M0_B(): u64 { 42_280_000 }
public macro fun M0_RHO(): u64 { 332_660_000 }
public macro fun M0_RHO_NEG(): u64 { 1 }
public macro fun M0_M(): u64 { 3_020_000 }
public macro fun M0_M_NEG(): u64 { 1 }
public macro fun M0_SIGMA(): u64 { 126_980_000 }
public macro fun M0_RATE(): u64 { 35_000_000 }
public macro fun M0_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M0_NOW_MS(): u64 { 1_773_241_327_070 }
public macro fun M0_VAULT_BALANCE(): u64 { 707_828_780_100 }
// M0_ATM_UP: strike=70782.88, UP, qty=10.0, util=0%
//   price=0.483713789, spread=0.009994694, util_spread=0.000000000, ask=0.493708482, bid=0.473719095
public macro fun M0_ATM_UP_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_ATM_UP_PRICE(): u64 { 483_713_788 }
public macro fun M0_ATM_UP_SPREAD(): u64 { 9_994_693 }
public macro fun M0_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_ATM_UP_ASK(): u64 { 493_708_482 }
public macro fun M0_ATM_UP_BID(): u64 { 473_719_094 }
public macro fun M0_ATM_UP_COST(): u64 { 4_937_084 }
public macro fun M0_ATM_UP_REDEEM_PAYOUT(): u64 { 4_737_190 }
// M0_ATM_DN: strike=70782.88, DN, qty=10.0, util=0%
//   price=0.515618669, spread=0.009995120, util_spread=0.000000000, ask=0.525613789, bid=0.505623549
public macro fun M0_ATM_DN_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_ATM_DN_PRICE(): u64 { 515_618_669 }
public macro fun M0_ATM_DN_SPREAD(): u64 { 9_995_119 }
public macro fun M0_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_ATM_DN_ASK(): u64 { 525_613_789 }
public macro fun M0_ATM_DN_BID(): u64 { 505_623_549 }
public macro fun M0_ATM_DN_COST(): u64 { 5_256_137 }
public macro fun M0_ATM_DN_REDEEM_PAYOUT(): u64 { 5_056_235 }
// M0_OTM_UP: strike=77861.17, UP, qty=10.0, util=0%
//   price=0.110475331, spread=0.006269626, util_spread=0.000000000, ask=0.116744958, bid=0.104205705
public macro fun M0_OTM_UP_STRIKE(): u64 { 77_861_165_811_000 }
public macro fun M0_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_OTM_UP_PRICE(): u64 { 110_475_331 }
public macro fun M0_OTM_UP_SPREAD(): u64 { 6_269_626 }
public macro fun M0_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_OTM_UP_ASK(): u64 { 116_744_957 }
public macro fun M0_OTM_UP_BID(): u64 { 104_205_705 }
public macro fun M0_OTM_UP_COST(): u64 { 1_167_449 }
public macro fun M0_OTM_UP_REDEEM_PAYOUT(): u64 { 1_042_057 }
// M0_ITM_UP: strike=63704.59, UP, qty=10.0, util=0%
//   price=0.849644866, spread=0.007148384, util_spread=0.000000000, ask=0.856793249, bid=0.842496482
public macro fun M0_ITM_UP_STRIKE(): u64 { 63_704_590_209_000 }
public macro fun M0_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_ITM_UP_PRICE(): u64 { 849_644_865 }
public macro fun M0_ITM_UP_SPREAD(): u64 { 7_148_383 }
public macro fun M0_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_ITM_UP_ASK(): u64 { 856_793_249 }
public macro fun M0_ITM_UP_BID(): u64 { 842_496_482 }
public macro fun M0_ITM_UP_COST(): u64 { 8_567_932 }
public macro fun M0_ITM_UP_REDEEM_PAYOUT(): u64 { 8_424_964 }
// M0_ATM_UP_UTIL50: strike=70782.88, UP, qty=10.0, util=50%
//   price=0.483713789, spread=0.009994694, util_spread=0.010000000, ask=0.503708482, bid=0.463719095
public macro fun M0_ATM_UP_UTIL50_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 353_914_390_049 }
public macro fun M0_ATM_UP_UTIL50_PRICE(): u64 { 483_713_788 }
public macro fun M0_ATM_UP_UTIL50_SPREAD(): u64 { 9_994_693 }
public macro fun M0_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 9_999_999 }
public macro fun M0_ATM_UP_UTIL50_ASK(): u64 { 503_708_482 }
public macro fun M0_ATM_UP_UTIL50_BID(): u64 { 463_719_094 }
public macro fun M0_ATM_UP_UTIL50_COST(): u64 { 5_037_084 }
public macro fun M0_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_637_190 }
// M0_ATM_UP_UTIL80: strike=70782.88, UP, qty=10.0, util=80%
//   price=0.483713789, spread=0.009994694, util_spread=0.025600000, ask=0.519308482, bid=0.448119095
public macro fun M0_ATM_UP_UTIL80_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M0_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 566_263_024_080 }
public macro fun M0_ATM_UP_UTIL80_PRICE(): u64 { 483_713_788 }
public macro fun M0_ATM_UP_UTIL80_SPREAD(): u64 { 9_994_693 }
public macro fun M0_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M0_ATM_UP_UTIL80_ASK(): u64 { 519_308_482 }
public macro fun M0_ATM_UP_UTIL80_BID(): u64 { 448_119_094 }
public macro fun M0_ATM_UP_UTIL80_COST(): u64 { 5_193_084 }
public macro fun M0_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_481_190 }
// M0_ATM_UP_SMALL: strike=70782.88, UP, qty=0.001, util=0%
//   price=0.483713789, spread=0.009994694, util_spread=0.000000000, ask=0.493708482, bid=0.473719095
public macro fun M0_ATM_UP_SMALL_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M0_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_ATM_UP_SMALL_PRICE(): u64 { 483_713_788 }
public macro fun M0_ATM_UP_SMALL_SPREAD(): u64 { 9_994_693 }
public macro fun M0_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_ATM_UP_SMALL_ASK(): u64 { 493_708_482 }
public macro fun M0_ATM_UP_SMALL_BID(): u64 { 473_719_094 }
public macro fun M0_ATM_UP_SMALL_COST(): u64 { 493 }
public macro fun M0_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 473 }
// M0_ATM_UP_LARGE: strike=70782.88, UP, qty=500.0, util=0%
//   price=0.483713789, spread=0.009994694, util_spread=0.000000000, ask=0.493708482, bid=0.473719095
public macro fun M0_ATM_UP_LARGE_STRIKE(): u64 { 70_782_878_010_000 }
public macro fun M0_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M0_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M0_ATM_UP_LARGE_PRICE(): u64 { 483_713_788 }
public macro fun M0_ATM_UP_LARGE_SPREAD(): u64 { 9_994_693 }
public macro fun M0_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M0_ATM_UP_LARGE_ASK(): u64 { 493_708_482 }
public macro fun M0_ATM_UP_LARGE_BID(): u64 { 473_719_094 }
public macro fun M0_ATM_UP_LARGE_COST(): u64 { 246_854_241 }
public macro fun M0_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 236_859_547 }

// --- M1: spot=70450.71, forward=70450.19, tte=5.9d ---
public macro fun M1_SPOT(): u64 { 70_450_708_810_000 }
public macro fun M1_FORWARD(): u64 { 70_450_190_810_000 }
public macro fun M1_A(): u64 { 2_080_000 }
public macro fun M1_B(): u64 { 34_010_000 }
public macro fun M1_RHO(): u64 { 481_790_000 }
public macro fun M1_RHO_NEG(): u64 { 1 }
public macro fun M1_M(): u64 { 4_090_000 }
public macro fun M1_M_NEG(): u64 { 1 }
public macro fun M1_SIGMA(): u64 { 113_820_000 }
public macro fun M1_RATE(): u64 { 35_000_000 }
public macro fun M1_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M1_NOW_MS(): u64 { 1_773_336_294_232 }
public macro fun M1_VAULT_BALANCE(): u64 { 704_501_908_100 }
// M1_ATM_UP: strike=70450.19, UP, qty=10.0, util=0%
//   price=0.484427122, spread=0.009995149, util_spread=0.000000000, ask=0.494422270, bid=0.474431973
public macro fun M1_ATM_UP_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_ATM_UP_PRICE(): u64 { 484_427_121 }
public macro fun M1_ATM_UP_SPREAD(): u64 { 9_995_148 }
public macro fun M1_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_ATM_UP_ASK(): u64 { 494_422_270 }
public macro fun M1_ATM_UP_BID(): u64 { 474_431_973 }
public macro fun M1_ATM_UP_COST(): u64 { 4_944_222 }
public macro fun M1_ATM_UP_REDEEM_PAYOUT(): u64 { 4_744_319 }
// M1_ATM_DN: strike=70450.19, DN, qty=10.0, util=0%
//   price=0.515010670, spread=0.009995493, util_spread=0.000000000, ask=0.525006163, bid=0.505015177
public macro fun M1_ATM_DN_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_ATM_DN_PRICE(): u64 { 515_010_669 }
public macro fun M1_ATM_DN_SPREAD(): u64 { 9_995_492 }
public macro fun M1_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_ATM_DN_ASK(): u64 { 525_006_162 }
public macro fun M1_ATM_DN_BID(): u64 { 505_015_177 }
public macro fun M1_ATM_DN_COST(): u64 { 5_250_061 }
public macro fun M1_ATM_DN_REDEEM_PAYOUT(): u64 { 5_050_151 }
// M1_OTM_UP: strike=77495.21, UP, qty=10.0, util=0%
//   price=0.094692180, spread=0.005855786, util_spread=0.000000000, ask=0.100547966, bid=0.088836394
public macro fun M1_OTM_UP_STRIKE(): u64 { 77_495_209_891_000 }
public macro fun M1_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_OTM_UP_PRICE(): u64 { 94_692_180 }
public macro fun M1_OTM_UP_SPREAD(): u64 { 5_855_785 }
public macro fun M1_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_OTM_UP_ASK(): u64 { 100_547_966 }
public macro fun M1_OTM_UP_BID(): u64 { 88_836_394 }
public macro fun M1_OTM_UP_COST(): u64 { 1_005_479 }
public macro fun M1_OTM_UP_REDEEM_PAYOUT(): u64 { 888_363 }
// M1_ITM_UP: strike=63405.17, UP, qty=10.0, util=0%
//   price=0.856823042, spread=0.007005064, util_spread=0.000000000, ask=0.863828107, bid=0.849817978
public macro fun M1_ITM_UP_STRIKE(): u64 { 63_405_171_729_000 }
public macro fun M1_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_ITM_UP_PRICE(): u64 { 856_823_042 }
public macro fun M1_ITM_UP_SPREAD(): u64 { 7_005_064 }
public macro fun M1_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_ITM_UP_ASK(): u64 { 863_828_106 }
public macro fun M1_ITM_UP_BID(): u64 { 849_817_977 }
public macro fun M1_ITM_UP_COST(): u64 { 8_638_281 }
public macro fun M1_ITM_UP_REDEEM_PAYOUT(): u64 { 8_498_179 }
// M1_ATM_UP_UTIL50: strike=70450.19, UP, qty=10.0, util=50%
//   price=0.484427122, spread=0.009995149, util_spread=0.010000000, ask=0.504422270, bid=0.464431973
public macro fun M1_ATM_UP_UTIL50_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 352_250_954_050 }
public macro fun M1_ATM_UP_UTIL50_PRICE(): u64 { 484_427_121 }
public macro fun M1_ATM_UP_UTIL50_SPREAD(): u64 { 9_995_148 }
public macro fun M1_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M1_ATM_UP_UTIL50_ASK(): u64 { 504_422_270 }
public macro fun M1_ATM_UP_UTIL50_BID(): u64 { 464_431_973 }
public macro fun M1_ATM_UP_UTIL50_COST(): u64 { 5_044_222 }
public macro fun M1_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_644_319 }
// M1_ATM_UP_UTIL80: strike=70450.19, UP, qty=10.0, util=80%
//   price=0.484427122, spread=0.009995149, util_spread=0.025600000, ask=0.520022270, bid=0.448831973
public macro fun M1_ATM_UP_UTIL80_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M1_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 563_601_526_480 }
public macro fun M1_ATM_UP_UTIL80_PRICE(): u64 { 484_427_121 }
public macro fun M1_ATM_UP_UTIL80_SPREAD(): u64 { 9_995_148 }
public macro fun M1_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M1_ATM_UP_UTIL80_ASK(): u64 { 520_022_270 }
public macro fun M1_ATM_UP_UTIL80_BID(): u64 { 448_831_973 }
public macro fun M1_ATM_UP_UTIL80_COST(): u64 { 5_200_222 }
public macro fun M1_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_488_319 }
// M1_ATM_UP_SMALL: strike=70450.19, UP, qty=0.001, util=0%
//   price=0.484427122, spread=0.009995149, util_spread=0.000000000, ask=0.494422270, bid=0.474431973
public macro fun M1_ATM_UP_SMALL_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M1_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_ATM_UP_SMALL_PRICE(): u64 { 484_427_121 }
public macro fun M1_ATM_UP_SMALL_SPREAD(): u64 { 9_995_148 }
public macro fun M1_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_ATM_UP_SMALL_ASK(): u64 { 494_422_270 }
public macro fun M1_ATM_UP_SMALL_BID(): u64 { 474_431_973 }
public macro fun M1_ATM_UP_SMALL_COST(): u64 { 494 }
public macro fun M1_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 474 }
// M1_ATM_UP_LARGE: strike=70450.19, UP, qty=500.0, util=0%
//   price=0.484427122, spread=0.009995149, util_spread=0.000000000, ask=0.494422270, bid=0.474431973
public macro fun M1_ATM_UP_LARGE_STRIKE(): u64 { 70_450_190_810_000 }
public macro fun M1_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M1_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M1_ATM_UP_LARGE_PRICE(): u64 { 484_427_121 }
public macro fun M1_ATM_UP_LARGE_SPREAD(): u64 { 9_995_148 }
public macro fun M1_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M1_ATM_UP_LARGE_ASK(): u64 { 494_422_270 }
public macro fun M1_ATM_UP_LARGE_BID(): u64 { 474_431_973 }
public macro fun M1_ATM_UP_LARGE_COST(): u64 { 247_211_135 }
public macro fun M1_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 237_215_986 }

// --- M2: spot=71459.79, forward=71461.69, tte=3.3d ---
public macro fun M2_SPOT(): u64 { 71_459_792_540_000 }
public macro fun M2_FORWARD(): u64 { 71_461_685_310_000 }
public macro fun M2_A(): u64 { 1_170_000 }
public macro fun M2_B(): u64 { 30_460_000 }
public macro fun M2_RHO(): u64 { 354_910_000 }
public macro fun M2_RHO_NEG(): u64 { 1 }
public macro fun M2_M(): u64 { 1_250_000 }
public macro fun M2_M_NEG(): u64 { 0 }
public macro fun M2_SIGMA(): u64 { 95_040_000 }
public macro fun M2_RATE(): u64 { 35_000_000 }
public macro fun M2_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M2_NOW_MS(): u64 { 1_773_558_189_150 }
public macro fun M2_VAULT_BALANCE(): u64 { 714_616_853_100 }
// M2_ATM_UP: strike=71461.69, UP, qty=10.0, util=0%
//   price=0.487109030, spread=0.009996676, util_spread=0.000000000, ask=0.497105706, bid=0.477112354
public macro fun M2_ATM_UP_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_ATM_UP_PRICE(): u64 { 487_109_029 }
public macro fun M2_ATM_UP_SPREAD(): u64 { 9_996_675 }
public macro fun M2_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_ATM_UP_ASK(): u64 { 497_105_705 }
public macro fun M2_ATM_UP_BID(): u64 { 477_112_353 }
public macro fun M2_ATM_UP_COST(): u64 { 4_971_057 }
public macro fun M2_ATM_UP_REDEEM_PAYOUT(): u64 { 4_771_123 }
// M2_ATM_DN: strike=71461.69, DN, qty=10.0, util=0%
//   price=0.512574922, spread=0.009996837, util_spread=0.000000000, ask=0.522571759, bid=0.502578086
public macro fun M2_ATM_DN_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_ATM_DN_PRICE(): u64 { 512_574_922 }
public macro fun M2_ATM_DN_SPREAD(): u64 { 9_996_836 }
public macro fun M2_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_ATM_DN_ASK(): u64 { 522_571_759 }
public macro fun M2_ATM_DN_BID(): u64 { 502_578_085 }
public macro fun M2_ATM_DN_COST(): u64 { 5_225_717 }
public macro fun M2_ATM_DN_REDEEM_PAYOUT(): u64 { 5_025_780 }
// M2_OTM_UP: strike=78607.85, UP, qty=10.0, util=0%
//   price=0.066965345, spread=0.005000000, util_spread=0.000000000, ask=0.071965345, bid=0.061965345
public macro fun M2_OTM_UP_STRIKE(): u64 { 78_607_853_841_000 }
public macro fun M2_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_OTM_UP_PRICE(): u64 { 66_965_344 }
public macro fun M2_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M2_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_OTM_UP_ASK(): u64 { 71_965_344 }
public macro fun M2_OTM_UP_BID(): u64 { 61_965_344 }
public macro fun M2_OTM_UP_COST(): u64 { 719_653 }
public macro fun M2_OTM_UP_REDEEM_PAYOUT(): u64 { 619_653 }
// M2_ITM_UP: strike=64315.52, UP, qty=10.0, util=0%
//   price=0.893875730, spread=0.006159932, util_spread=0.000000000, ask=0.900035662, bid=0.887715798
public macro fun M2_ITM_UP_STRIKE(): u64 { 64_315_516_779_000 }
public macro fun M2_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_ITM_UP_PRICE(): u64 { 893_875_730 }
public macro fun M2_ITM_UP_SPREAD(): u64 { 6_159_932 }
public macro fun M2_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_ITM_UP_ASK(): u64 { 900_035_662 }
public macro fun M2_ITM_UP_BID(): u64 { 887_715_798 }
public macro fun M2_ITM_UP_COST(): u64 { 9_000_356 }
public macro fun M2_ITM_UP_REDEEM_PAYOUT(): u64 { 8_877_157 }
// M2_ATM_UP_UTIL50: strike=71461.69, UP, qty=10.0, util=50%
//   price=0.487109030, spread=0.009996676, util_spread=0.010000000, ask=0.507105706, bid=0.467112354
public macro fun M2_ATM_UP_UTIL50_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 357_308_426_550 }
public macro fun M2_ATM_UP_UTIL50_PRICE(): u64 { 487_109_029 }
public macro fun M2_ATM_UP_UTIL50_SPREAD(): u64 { 9_996_675 }
public macro fun M2_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M2_ATM_UP_UTIL50_ASK(): u64 { 507_105_705 }
public macro fun M2_ATM_UP_UTIL50_BID(): u64 { 467_112_353 }
public macro fun M2_ATM_UP_UTIL50_COST(): u64 { 5_071_057 }
public macro fun M2_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_671_123 }
// M2_ATM_UP_UTIL80: strike=71461.69, UP, qty=10.0, util=80%
//   price=0.487109030, spread=0.009996676, util_spread=0.025600000, ask=0.522705706, bid=0.451512354
public macro fun M2_ATM_UP_UTIL80_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M2_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 571_693_482_480 }
public macro fun M2_ATM_UP_UTIL80_PRICE(): u64 { 487_109_029 }
public macro fun M2_ATM_UP_UTIL80_SPREAD(): u64 { 9_996_675 }
public macro fun M2_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M2_ATM_UP_UTIL80_ASK(): u64 { 522_705_705 }
public macro fun M2_ATM_UP_UTIL80_BID(): u64 { 451_512_353 }
public macro fun M2_ATM_UP_UTIL80_COST(): u64 { 5_227_057 }
public macro fun M2_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_515_123 }
// M2_ATM_UP_SMALL: strike=71461.69, UP, qty=0.001, util=0%
//   price=0.487109030, spread=0.009996676, util_spread=0.000000000, ask=0.497105706, bid=0.477112354
public macro fun M2_ATM_UP_SMALL_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M2_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_ATM_UP_SMALL_PRICE(): u64 { 487_109_029 }
public macro fun M2_ATM_UP_SMALL_SPREAD(): u64 { 9_996_675 }
public macro fun M2_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_ATM_UP_SMALL_ASK(): u64 { 497_105_705 }
public macro fun M2_ATM_UP_SMALL_BID(): u64 { 477_112_353 }
public macro fun M2_ATM_UP_SMALL_COST(): u64 { 497 }
public macro fun M2_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 477 }
// M2_ATM_UP_LARGE: strike=71461.69, UP, qty=500.0, util=0%
//   price=0.487109030, spread=0.009996676, util_spread=0.000000000, ask=0.497105706, bid=0.477112354
public macro fun M2_ATM_UP_LARGE_STRIKE(): u64 { 71_461_685_310_000 }
public macro fun M2_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M2_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M2_ATM_UP_LARGE_PRICE(): u64 { 487_109_029 }
public macro fun M2_ATM_UP_LARGE_SPREAD(): u64 { 9_996_675 }
public macro fun M2_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M2_ATM_UP_LARGE_ASK(): u64 { 497_105_705 }
public macro fun M2_ATM_UP_LARGE_BID(): u64 { 477_112_353 }
public macro fun M2_ATM_UP_LARGE_COST(): u64 { 248_552_852 }
public macro fun M2_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 238_556_176 }

// --- M3: spot=74228.29, forward=74241.50, tte=1.2d ---
public macro fun M3_SPOT(): u64 { 74_228_286_720_000 }
public macro fun M3_FORWARD(): u64 { 74_241_496_580_000 }
public macro fun M3_A(): u64 { 550_000 }
public macro fun M3_B(): u64 { 26_870_000 }
public macro fun M3_RHO(): u64 { 360_900_000 }
public macro fun M3_RHO_NEG(): u64 { 1 }
public macro fun M3_M(): u64 { 4_160_000 }
public macro fun M3_M_NEG(): u64 { 1 }
public macro fun M3_SIGMA(): u64 { 75_400_000 }
public macro fun M3_RATE(): u64 { 35_000_000 }
public macro fun M3_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M3_NOW_MS(): u64 { 1_773_735_844_810 }
public macro fun M3_VAULT_BALANCE(): u64 { 742_414_965_800 }
// M3_ATM_UP: strike=74241.50, UP, qty=10.0, util=0%
//   price=0.489892266, spread=0.009997956, util_spread=0.000000000, ask=0.499890223, bid=0.479894310
public macro fun M3_ATM_UP_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_ATM_UP_PRICE(): u64 { 489_892_266 }
public macro fun M3_ATM_UP_SPREAD(): u64 { 9_997_956 }
public macro fun M3_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_ATM_UP_ASK(): u64 { 499_890_222 }
public macro fun M3_ATM_UP_BID(): u64 { 479_894_309 }
public macro fun M3_ATM_UP_COST(): u64 { 4_998_902 }
public macro fun M3_ATM_UP_REDEEM_PAYOUT(): u64 { 4_798_943 }
// M3_ATM_DN: strike=74241.50, DN, qty=10.0, util=0%
//   price=0.509988813, spread=0.009998004, util_spread=0.000000000, ask=0.519986817, bid=0.499990808
public macro fun M3_ATM_DN_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_ATM_DN_PRICE(): u64 { 509_988_812 }
public macro fun M3_ATM_DN_SPREAD(): u64 { 9_998_004 }
public macro fun M3_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_ATM_DN_ASK(): u64 { 519_986_816 }
public macro fun M3_ATM_DN_BID(): u64 { 499_990_808 }
public macro fun M3_ATM_DN_COST(): u64 { 5_199_868 }
public macro fun M3_ATM_DN_REDEEM_PAYOUT(): u64 { 4_999_908 }
// M3_OTM_UP: strike=81665.65, UP, qty=10.0, util=0%
//   price=0.037116900, spread=0.005000000, util_spread=0.000000000, ask=0.042116900, bid=0.032116900
public macro fun M3_OTM_UP_STRIKE(): u64 { 81_665_646_238_000 }
public macro fun M3_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_OTM_UP_PRICE(): u64 { 37_116_900 }
public macro fun M3_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M3_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_OTM_UP_ASK(): u64 { 42_116_900 }
public macro fun M3_OTM_UP_BID(): u64 { 32_116_900 }
public macro fun M3_OTM_UP_COST(): u64 { 421_169 }
public macro fun M3_OTM_UP_REDEEM_PAYOUT(): u64 { 321_169 }
// M3_ITM_UP: strike=66817.35, UP, qty=10.0, util=0%
//   price=0.928652730, spread=0.005148081, util_spread=0.000000000, ask=0.933800810, bid=0.923504649
public macro fun M3_ITM_UP_STRIKE(): u64 { 66_817_346_922_000 }
public macro fun M3_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_ITM_UP_PRICE(): u64 { 928_652_729 }
public macro fun M3_ITM_UP_SPREAD(): u64 { 5_148_080 }
public macro fun M3_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_ITM_UP_ASK(): u64 { 933_800_810 }
public macro fun M3_ITM_UP_BID(): u64 { 923_504_648 }
public macro fun M3_ITM_UP_COST(): u64 { 9_338_008 }
public macro fun M3_ITM_UP_REDEEM_PAYOUT(): u64 { 9_235_046 }
// M3_ATM_UP_UTIL50: strike=74241.50, UP, qty=10.0, util=50%
//   price=0.489892266, spread=0.009997956, util_spread=0.010000000, ask=0.509890223, bid=0.469894310
public macro fun M3_ATM_UP_UTIL50_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 371_207_482_900 }
public macro fun M3_ATM_UP_UTIL50_PRICE(): u64 { 489_892_266 }
public macro fun M3_ATM_UP_UTIL50_SPREAD(): u64 { 9_997_956 }
public macro fun M3_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M3_ATM_UP_UTIL50_ASK(): u64 { 509_890_222 }
public macro fun M3_ATM_UP_UTIL50_BID(): u64 { 469_894_309 }
public macro fun M3_ATM_UP_UTIL50_COST(): u64 { 5_098_902 }
public macro fun M3_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_698_943 }
// M3_ATM_UP_UTIL80: strike=74241.50, UP, qty=10.0, util=80%
//   price=0.489892266, spread=0.009997956, util_spread=0.025600000, ask=0.525490223, bid=0.454294310
public macro fun M3_ATM_UP_UTIL80_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M3_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 593_931_972_640 }
public macro fun M3_ATM_UP_UTIL80_PRICE(): u64 { 489_892_266 }
public macro fun M3_ATM_UP_UTIL80_SPREAD(): u64 { 9_997_956 }
public macro fun M3_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M3_ATM_UP_UTIL80_ASK(): u64 { 525_490_222 }
public macro fun M3_ATM_UP_UTIL80_BID(): u64 { 454_294_309 }
public macro fun M3_ATM_UP_UTIL80_COST(): u64 { 5_254_902 }
public macro fun M3_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_542_943 }
// M3_ATM_UP_SMALL: strike=74241.50, UP, qty=0.001, util=0%
//   price=0.489892266, spread=0.009997956, util_spread=0.000000000, ask=0.499890223, bid=0.479894310
public macro fun M3_ATM_UP_SMALL_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M3_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_ATM_UP_SMALL_PRICE(): u64 { 489_892_266 }
public macro fun M3_ATM_UP_SMALL_SPREAD(): u64 { 9_997_956 }
public macro fun M3_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_ATM_UP_SMALL_ASK(): u64 { 499_890_222 }
public macro fun M3_ATM_UP_SMALL_BID(): u64 { 479_894_309 }
public macro fun M3_ATM_UP_SMALL_COST(): u64 { 499 }
public macro fun M3_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 479 }
// M3_ATM_UP_LARGE: strike=74241.50, UP, qty=500.0, util=0%
//   price=0.489892266, spread=0.009997956, util_spread=0.000000000, ask=0.499890223, bid=0.479894310
public macro fun M3_ATM_UP_LARGE_STRIKE(): u64 { 74_241_496_580_000 }
public macro fun M3_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M3_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M3_ATM_UP_LARGE_PRICE(): u64 { 489_892_266 }
public macro fun M3_ATM_UP_LARGE_SPREAD(): u64 { 9_997_956 }
public macro fun M3_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M3_ATM_UP_LARGE_ASK(): u64 { 499_890_222 }
public macro fun M3_ATM_UP_LARGE_BID(): u64 { 479_894_309 }
public macro fun M3_ATM_UP_LARGE_COST(): u64 { 249_945_111 }
public macro fun M3_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 239_947_154 }

// --- M4: spot=74105.49, forward=74127.85, tte=5.0h ---
public macro fun M4_SPOT(): u64 { 74_105_490_370_000 }
public macro fun M4_FORWARD(): u64 { 74_127_848_210_000 }
public macro fun M4_A(): u64 { 960_000 }
public macro fun M4_B(): u64 { 12_900_000 }
public macro fun M4_RHO(): u64 { 640_610_000 }
public macro fun M4_RHO_NEG(): u64 { 1 }
public macro fun M4_M(): u64 { 16_010_000 }
public macro fun M4_M_NEG(): u64 { 1 }
public macro fun M4_SIGMA(): u64 { 31_180_000 }
public macro fun M4_RATE(): u64 { 35_000_000 }
public macro fun M4_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M4_NOW_MS(): u64 { 1_773_825_103_183 }
public macro fun M4_VAULT_BALANCE(): u64 { 741_278_482_099 }
// M4_ATM_UP: strike=74127.85, UP, qty=10.0, util=0%
//   price=0.492854533, spread=0.009998979, util_spread=0.000000000, ask=0.502853512, bid=0.482855554
public macro fun M4_ATM_UP_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_ATM_UP_PRICE(): u64 { 492_854_532 }
public macro fun M4_ATM_UP_SPREAD(): u64 { 9_998_978 }
public macro fun M4_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_ATM_UP_ASK(): u64 { 502_853_511 }
public macro fun M4_ATM_UP_BID(): u64 { 482_855_554 }
public macro fun M4_ATM_UP_COST(): u64 { 5_028_535 }
public macro fun M4_ATM_UP_REDEEM_PAYOUT(): u64 { 4_828_555 }
// M4_ATM_DN: strike=74127.85, DN, qty=10.0, util=0%
//   price=0.507125602, spread=0.009998984, util_spread=0.000000000, ask=0.517124586, bid=0.497126618
public macro fun M4_ATM_DN_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_ATM_DN_PRICE(): u64 { 507_125_601 }
public macro fun M4_ATM_DN_SPREAD(): u64 { 9_998_984 }
public macro fun M4_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_ATM_DN_ASK(): u64 { 517_124_586 }
public macro fun M4_ATM_DN_BID(): u64 { 497_126_617 }
public macro fun M4_ATM_DN_COST(): u64 { 5_171_245 }
public macro fun M4_ATM_DN_REDEEM_PAYOUT(): u64 { 4_971_266 }
// M4_OTM_UP: strike=81540.63, UP, qty=10.0, util=0%
//   price=0.007041436, spread=0.005000000, util_spread=0.000000000, ask=0.012041436, bid=0.002041436
public macro fun M4_OTM_UP_STRIKE(): u64 { 81_540_633_031_000 }
public macro fun M4_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_OTM_UP_PRICE(): u64 { 7_041_435 }
public macro fun M4_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M4_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_OTM_UP_ASK(): u64 { 12_041_435 }
public macro fun M4_OTM_UP_BID(): u64 { 2_041_435 }
public macro fun M4_OTM_UP_COST(): u64 { 120_414 }
public macro fun M4_OTM_UP_REDEEM_PAYOUT(): u64 { 20_414 }
// M4_ITM_UP: strike=66715.06, UP, qty=10.0, util=0%
//   price=0.972743617, spread=0.005000000, util_spread=0.000000000, ask=0.977743617, bid=0.967743617
public macro fun M4_ITM_UP_STRIKE(): u64 { 66_715_063_389_000 }
public macro fun M4_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_ITM_UP_PRICE(): u64 { 972_743_617 }
public macro fun M4_ITM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M4_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_ITM_UP_ASK(): u64 { 977_743_617 }
public macro fun M4_ITM_UP_BID(): u64 { 967_743_617 }
public macro fun M4_ITM_UP_COST(): u64 { 9_777_436 }
public macro fun M4_ITM_UP_REDEEM_PAYOUT(): u64 { 9_677_436 }
// M4_ATM_UP_UTIL50: strike=74127.85, UP, qty=10.0, util=50%
//   price=0.492854533, spread=0.009998979, util_spread=0.010000000, ask=0.512853512, bid=0.472855554
public macro fun M4_ATM_UP_UTIL50_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 370_639_241_049 }
public macro fun M4_ATM_UP_UTIL50_PRICE(): u64 { 492_854_532 }
public macro fun M4_ATM_UP_UTIL50_SPREAD(): u64 { 9_998_978 }
public macro fun M4_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M4_ATM_UP_UTIL50_ASK(): u64 { 512_853_511 }
public macro fun M4_ATM_UP_UTIL50_BID(): u64 { 472_855_554 }
public macro fun M4_ATM_UP_UTIL50_COST(): u64 { 5_128_535 }
public macro fun M4_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_728_555 }
// M4_ATM_UP_UTIL80: strike=74127.85, UP, qty=10.0, util=80%
//   price=0.492854533, spread=0.009998979, util_spread=0.025600000, ask=0.528453512, bid=0.457255554
public macro fun M4_ATM_UP_UTIL80_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M4_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 593_022_785_679 }
public macro fun M4_ATM_UP_UTIL80_PRICE(): u64 { 492_854_532 }
public macro fun M4_ATM_UP_UTIL80_SPREAD(): u64 { 9_998_978 }
public macro fun M4_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_599_999 }
public macro fun M4_ATM_UP_UTIL80_ASK(): u64 { 528_453_511 }
public macro fun M4_ATM_UP_UTIL80_BID(): u64 { 457_255_554 }
public macro fun M4_ATM_UP_UTIL80_COST(): u64 { 5_284_535 }
public macro fun M4_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_572_555 }
// M4_ATM_UP_SMALL: strike=74127.85, UP, qty=0.001, util=0%
//   price=0.492854533, spread=0.009998979, util_spread=0.000000000, ask=0.502853512, bid=0.482855554
public macro fun M4_ATM_UP_SMALL_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M4_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_ATM_UP_SMALL_PRICE(): u64 { 492_854_532 }
public macro fun M4_ATM_UP_SMALL_SPREAD(): u64 { 9_998_978 }
public macro fun M4_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_ATM_UP_SMALL_ASK(): u64 { 502_853_511 }
public macro fun M4_ATM_UP_SMALL_BID(): u64 { 482_855_554 }
public macro fun M4_ATM_UP_SMALL_COST(): u64 { 502 }
public macro fun M4_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 482 }
// M4_ATM_UP_LARGE: strike=74127.85, UP, qty=500.0, util=0%
//   price=0.492854533, spread=0.009998979, util_spread=0.000000000, ask=0.502853512, bid=0.482855554
public macro fun M4_ATM_UP_LARGE_STRIKE(): u64 { 74_127_848_210_000 }
public macro fun M4_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M4_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M4_ATM_UP_LARGE_PRICE(): u64 { 492_854_532 }
public macro fun M4_ATM_UP_LARGE_SPREAD(): u64 { 9_998_978 }
public macro fun M4_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M4_ATM_UP_LARGE_ASK(): u64 { 502_853_511 }
public macro fun M4_ATM_UP_LARGE_BID(): u64 { 482_855_554 }
public macro fun M4_ATM_UP_LARGE_COST(): u64 { 251_426_755 }
public macro fun M4_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 241_427_777 }

// --- M5: spot=72385.19, forward=72523.23, tte=1.1h ---
public macro fun M5_SPOT(): u64 { 72_385_193_560_000 }
public macro fun M5_FORWARD(): u64 { 72_523_227_120_000 }
public macro fun M5_A(): u64 { 1_050_000 }
public macro fun M5_B(): u64 { 12_360_000 }
public macro fun M5_RHO(): u64 { 526_610_000 }
public macro fun M5_RHO_NEG(): u64 { 1 }
public macro fun M5_M(): u64 { 3_690_000 }
public macro fun M5_M_NEG(): u64 { 1 }
public macro fun M5_SIGMA(): u64 { 50_320_000 }
public macro fun M5_RATE(): u64 { 35_000_000 }
public macro fun M5_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M5_NOW_MS(): u64 { 1_773_838_922_225 }
public macro fun M5_VAULT_BALANCE(): u64 { 725_232_271_200 }
// M5_ATM_UP: strike=72523.23, UP, qty=10.0, util=0%
//   price=0.491896737, spread=0.009998687, util_spread=0.000000000, ask=0.501895424, bid=0.481898051
public macro fun M5_ATM_UP_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_ATM_UP_PRICE(): u64 { 491_896_737 }
public macro fun M5_ATM_UP_SPREAD(): u64 { 9_998_686 }
public macro fun M5_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_ATM_UP_ASK(): u64 { 501_895_424 }
public macro fun M5_ATM_UP_BID(): u64 { 481_898_050 }
public macro fun M5_ATM_UP_COST(): u64 { 5_018_954 }
public macro fun M5_ATM_UP_REDEEM_PAYOUT(): u64 { 4_818_980 }
// M5_ATM_DN: strike=72523.23, DN, qty=10.0, util=0%
//   price=0.508098734, spread=0.009998688, util_spread=0.000000000, ask=0.518097422, bid=0.498100046
public macro fun M5_ATM_DN_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_ATM_DN_PRICE(): u64 { 508_098_734 }
public macro fun M5_ATM_DN_SPREAD(): u64 { 9_998_688 }
public macro fun M5_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_ATM_DN_ASK(): u64 { 518_097_422 }
public macro fun M5_ATM_DN_BID(): u64 { 498_100_046 }
public macro fun M5_ATM_DN_COST(): u64 { 5_180_974 }
public macro fun M5_ATM_DN_REDEEM_PAYOUT(): u64 { 4_981_000 }
// M5_OTM_UP: strike=79775.55, UP, qty=10.0, util=0%
//   price=0.011266430, spread=0.005000000, util_spread=0.000000000, ask=0.016266430, bid=0.006266430
public macro fun M5_OTM_UP_STRIKE(): u64 { 79_775_549_832_000 }
public macro fun M5_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_OTM_UP_PRICE(): u64 { 11_266_430 }
public macro fun M5_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M5_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_OTM_UP_ASK(): u64 { 16_266_430 }
public macro fun M5_OTM_UP_BID(): u64 { 6_266_430 }
public macro fun M5_OTM_UP_COST(): u64 { 162_664 }
public macro fun M5_OTM_UP_REDEEM_PAYOUT(): u64 { 62_664 }
// M5_ITM_UP: strike=65270.90, UP, qty=10.0, util=0%
//   price=0.968567059, spread=0.005000000, util_spread=0.000000000, ask=0.973567059, bid=0.963567059
public macro fun M5_ITM_UP_STRIKE(): u64 { 65_270_904_407_999 }
public macro fun M5_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_ITM_UP_PRICE(): u64 { 968_567_058 }
public macro fun M5_ITM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M5_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_ITM_UP_ASK(): u64 { 973_567_058 }
public macro fun M5_ITM_UP_BID(): u64 { 963_567_058 }
public macro fun M5_ITM_UP_COST(): u64 { 9_735_670 }
public macro fun M5_ITM_UP_REDEEM_PAYOUT(): u64 { 9_635_670 }
// M5_ATM_UP_UTIL50: strike=72523.23, UP, qty=10.0, util=50%
//   price=0.491896737, spread=0.009998687, util_spread=0.010000000, ask=0.511895424, bid=0.471898051
public macro fun M5_ATM_UP_UTIL50_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 362_616_135_599 }
public macro fun M5_ATM_UP_UTIL50_PRICE(): u64 { 491_896_737 }
public macro fun M5_ATM_UP_UTIL50_SPREAD(): u64 { 9_998_686 }
public macro fun M5_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 9_999_999 }
public macro fun M5_ATM_UP_UTIL50_ASK(): u64 { 511_895_424 }
public macro fun M5_ATM_UP_UTIL50_BID(): u64 { 471_898_050 }
public macro fun M5_ATM_UP_UTIL50_COST(): u64 { 5_118_954 }
public macro fun M5_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_718_980 }
// M5_ATM_UP_UTIL80: strike=72523.23, UP, qty=10.0, util=80%
//   price=0.491896737, spread=0.009998687, util_spread=0.025600000, ask=0.527495424, bid=0.456298051
public macro fun M5_ATM_UP_UTIL80_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M5_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 580_185_816_960 }
public macro fun M5_ATM_UP_UTIL80_PRICE(): u64 { 491_896_737 }
public macro fun M5_ATM_UP_UTIL80_SPREAD(): u64 { 9_998_686 }
public macro fun M5_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M5_ATM_UP_UTIL80_ASK(): u64 { 527_495_424 }
public macro fun M5_ATM_UP_UTIL80_BID(): u64 { 456_298_050 }
public macro fun M5_ATM_UP_UTIL80_COST(): u64 { 5_274_954 }
public macro fun M5_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_562_980 }
// M5_ATM_UP_SMALL: strike=72523.23, UP, qty=0.001, util=0%
//   price=0.491896737, spread=0.009998687, util_spread=0.000000000, ask=0.501895424, bid=0.481898051
public macro fun M5_ATM_UP_SMALL_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M5_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_ATM_UP_SMALL_PRICE(): u64 { 491_896_737 }
public macro fun M5_ATM_UP_SMALL_SPREAD(): u64 { 9_998_686 }
public macro fun M5_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_ATM_UP_SMALL_ASK(): u64 { 501_895_424 }
public macro fun M5_ATM_UP_SMALL_BID(): u64 { 481_898_050 }
public macro fun M5_ATM_UP_SMALL_COST(): u64 { 501 }
public macro fun M5_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 481 }
// M5_ATM_UP_LARGE: strike=72523.23, UP, qty=500.0, util=0%
//   price=0.491896737, spread=0.009998687, util_spread=0.000000000, ask=0.501895424, bid=0.481898051
public macro fun M5_ATM_UP_LARGE_STRIKE(): u64 { 72_523_227_120_000 }
public macro fun M5_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M5_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M5_ATM_UP_LARGE_PRICE(): u64 { 491_896_737 }
public macro fun M5_ATM_UP_LARGE_SPREAD(): u64 { 9_998_686 }
public macro fun M5_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M5_ATM_UP_LARGE_ASK(): u64 { 501_895_424 }
public macro fun M5_ATM_UP_LARGE_BID(): u64 { 481_898_050 }
public macro fun M5_ATM_UP_LARGE_COST(): u64 { 250_947_712 }
public macro fun M5_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 240_949_025 }

// --- M6: spot=72137.86, forward=72167.96, tte=2m ---
public macro fun M6_SPOT(): u64 { 72_137_857_040_000 }
public macro fun M6_FORWARD(): u64 { 72_167_958_690_000 }
public macro fun M6_A(): u64 { 770_000 }
public macro fun M6_B(): u64 { 15_490_000 }
public macro fun M6_RHO(): u64 { 399_060_000 }
public macro fun M6_RHO_NEG(): u64 { 1 }
public macro fun M6_M(): u64 { 4_540_000 }
public macro fun M6_M_NEG(): u64 { 0 }
public macro fun M6_SIGMA(): u64 { 54_360_000 }
public macro fun M6_RATE(): u64 { 35_000_000 }
public macro fun M6_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M6_NOW_MS(): u64 { 1_773_842_876_472 }
public macro fun M6_VAULT_BALANCE(): u64 { 721_679_586_900 }
// M6_ATM_UP: strike=72167.96, UP, qty=10.0, util=0%
//   price=0.491915056, spread=0.009998693, util_spread=0.000000000, ask=0.501913749, bid=0.481916364
public macro fun M6_ATM_UP_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_ATM_UP_PRICE(): u64 { 491_915_056 }
public macro fun M6_ATM_UP_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_ATM_UP_ASK(): u64 { 501_913_748 }
public macro fun M6_ATM_UP_BID(): u64 { 481_916_363 }
public macro fun M6_ATM_UP_COST(): u64 { 5_019_137 }
public macro fun M6_ATM_UP_REDEEM_PAYOUT(): u64 { 4_819_163 }
// M6_ATM_DN: strike=72167.96, DN, qty=10.0, util=0%
//   price=0.508084804, spread=0.009998693, util_spread=0.000000000, ask=0.518083497, bid=0.498086111
public macro fun M6_ATM_DN_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_ATM_DN_PRICE(): u64 { 508_084_803 }
public macro fun M6_ATM_DN_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_ATM_DN_ASK(): u64 { 518_083_496 }
public macro fun M6_ATM_DN_BID(): u64 { 498_086_111 }
public macro fun M6_ATM_DN_COST(): u64 { 5_180_834 }
public macro fun M6_ATM_DN_REDEEM_PAYOUT(): u64 { 4_980_861 }
// M6_OTM_UP: strike=79384.75, UP, qty=10.0, util=0%
//   price=0.012586701, spread=0.005000000, util_spread=0.000000000, ask=0.017586701, bid=0.007586701
public macro fun M6_OTM_UP_STRIKE(): u64 { 79_384_754_559_000 }
public macro fun M6_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_OTM_UP_PRICE(): u64 { 12_586_700 }
public macro fun M6_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M6_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_OTM_UP_ASK(): u64 { 17_586_700 }
public macro fun M6_OTM_UP_BID(): u64 { 7_586_700 }
public macro fun M6_OTM_UP_COST(): u64 { 175_867 }
public macro fun M6_OTM_UP_REDEEM_PAYOUT(): u64 { 75_867 }
// M6_ITM_UP: strike=64951.16, UP, qty=10.0, util=0%
//   price=0.963418037, spread=0.005000000, util_spread=0.000000000, ask=0.968418037, bid=0.958418037
public macro fun M6_ITM_UP_STRIKE(): u64 { 64_951_162_821_000 }
public macro fun M6_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_ITM_UP_PRICE(): u64 { 963_418_037 }
public macro fun M6_ITM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M6_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_ITM_UP_ASK(): u64 { 968_418_037 }
public macro fun M6_ITM_UP_BID(): u64 { 958_418_037 }
public macro fun M6_ITM_UP_COST(): u64 { 9_684_180 }
public macro fun M6_ITM_UP_REDEEM_PAYOUT(): u64 { 9_584_180 }
// M6_ATM_UP_UTIL50: strike=72167.96, UP, qty=10.0, util=50%
//   price=0.491915056, spread=0.009998693, util_spread=0.010000000, ask=0.511913749, bid=0.471916364
public macro fun M6_ATM_UP_UTIL50_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 360_839_793_450 }
public macro fun M6_ATM_UP_UTIL50_PRICE(): u64 { 491_915_056 }
public macro fun M6_ATM_UP_UTIL50_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M6_ATM_UP_UTIL50_ASK(): u64 { 511_913_748 }
public macro fun M6_ATM_UP_UTIL50_BID(): u64 { 471_916_363 }
public macro fun M6_ATM_UP_UTIL50_COST(): u64 { 5_119_137 }
public macro fun M6_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_719_163 }
// M6_ATM_UP_UTIL80: strike=72167.96, UP, qty=10.0, util=80%
//   price=0.491915056, spread=0.009998693, util_spread=0.025600000, ask=0.527513749, bid=0.456316364
public macro fun M6_ATM_UP_UTIL80_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M6_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 577_343_669_520 }
public macro fun M6_ATM_UP_UTIL80_PRICE(): u64 { 491_915_056 }
public macro fun M6_ATM_UP_UTIL80_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M6_ATM_UP_UTIL80_ASK(): u64 { 527_513_748 }
public macro fun M6_ATM_UP_UTIL80_BID(): u64 { 456_316_363 }
public macro fun M6_ATM_UP_UTIL80_COST(): u64 { 5_275_137 }
public macro fun M6_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_563_163 }
// M6_ATM_UP_SMALL: strike=72167.96, UP, qty=0.001, util=0%
//   price=0.491915056, spread=0.009998693, util_spread=0.000000000, ask=0.501913749, bid=0.481916364
public macro fun M6_ATM_UP_SMALL_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M6_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_ATM_UP_SMALL_PRICE(): u64 { 491_915_056 }
public macro fun M6_ATM_UP_SMALL_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_ATM_UP_SMALL_ASK(): u64 { 501_913_748 }
public macro fun M6_ATM_UP_SMALL_BID(): u64 { 481_916_363 }
public macro fun M6_ATM_UP_SMALL_COST(): u64 { 501 }
public macro fun M6_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 481 }
// M6_ATM_UP_LARGE: strike=72167.96, UP, qty=500.0, util=0%
//   price=0.491915056, spread=0.009998693, util_spread=0.000000000, ask=0.501913749, bid=0.481916364
public macro fun M6_ATM_UP_LARGE_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M6_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M6_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M6_ATM_UP_LARGE_PRICE(): u64 { 491_915_056 }
public macro fun M6_ATM_UP_LARGE_SPREAD(): u64 { 9_998_692 }
public macro fun M6_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M6_ATM_UP_LARGE_ASK(): u64 { 501_913_748 }
public macro fun M6_ATM_UP_LARGE_BID(): u64 { 481_916_363 }
public macro fun M6_ATM_UP_LARGE_COST(): u64 { 250_956_874 }
public macro fun M6_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 240_958_181 }

// --- M7: spot=72137.86, forward=72167.96, tte=31s ---
public macro fun M7_SPOT(): u64 { 72_137_857_040_000 }
public macro fun M7_FORWARD(): u64 { 72_167_958_690_000 }
public macro fun M7_A(): u64 { 770_000 }
public macro fun M7_B(): u64 { 15_490_000 }
public macro fun M7_RHO(): u64 { 399_060_000 }
public macro fun M7_RHO_NEG(): u64 { 1 }
public macro fun M7_M(): u64 { 4_540_000 }
public macro fun M7_M_NEG(): u64 { 0 }
public macro fun M7_SIGMA(): u64 { 54_360_000 }
public macro fun M7_RATE(): u64 { 35_000_000 }
public macro fun M7_EXPIRY_MS(): u64 { 1_773_843_002_405 }
public macro fun M7_NOW_MS(): u64 { 1_773_842_971_565 }
public macro fun M7_VAULT_BALANCE(): u64 { 721_679_586_900 }
// M7_ATM_UP: strike=72167.96, UP, qty=10.0, util=0%
//   price=0.491915108, spread=0.009998693, util_spread=0.000000000, ask=0.501913801, bid=0.481916416
public macro fun M7_ATM_UP_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_ATM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_ATM_UP_PRICE(): u64 { 491_915_108 }
public macro fun M7_ATM_UP_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_ATM_UP_ASK(): u64 { 501_913_800 }
public macro fun M7_ATM_UP_BID(): u64 { 481_916_415 }
public macro fun M7_ATM_UP_COST(): u64 { 5_019_138 }
public macro fun M7_ATM_UP_REDEEM_PAYOUT(): u64 { 4_819_164 }
// M7_ATM_DN: strike=72167.96, DN, qty=10.0, util=0%
//   price=0.508084858, spread=0.009998693, util_spread=0.000000000, ask=0.518083550, bid=0.498086165
public macro fun M7_ATM_DN_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_DN_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_ATM_DN_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_ATM_DN_PRICE(): u64 { 508_084_857 }
public macro fun M7_ATM_DN_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_DN_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_ATM_DN_ASK(): u64 { 518_083_550 }
public macro fun M7_ATM_DN_BID(): u64 { 498_086_164 }
public macro fun M7_ATM_DN_COST(): u64 { 5_180_835 }
public macro fun M7_ATM_DN_REDEEM_PAYOUT(): u64 { 4_980_861 }
// M7_OTM_UP: strike=79384.75, UP, qty=10.0, util=0%
//   price=0.012586702, spread=0.005000000, util_spread=0.000000000, ask=0.017586702, bid=0.007586702
public macro fun M7_OTM_UP_STRIKE(): u64 { 79_384_754_559_000 }
public macro fun M7_OTM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_OTM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_OTM_UP_PRICE(): u64 { 12_586_702 }
public macro fun M7_OTM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M7_OTM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_OTM_UP_ASK(): u64 { 17_586_702 }
public macro fun M7_OTM_UP_BID(): u64 { 7_586_702 }
public macro fun M7_OTM_UP_COST(): u64 { 175_867 }
public macro fun M7_OTM_UP_REDEEM_PAYOUT(): u64 { 75_867 }
// M7_ITM_UP: strike=64951.16, UP, qty=10.0, util=0%
//   price=0.963418139, spread=0.005000000, util_spread=0.000000000, ask=0.968418139, bid=0.958418139
public macro fun M7_ITM_UP_STRIKE(): u64 { 64_951_162_821_000 }
public macro fun M7_ITM_UP_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_ITM_UP_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_ITM_UP_PRICE(): u64 { 963_418_138 }
public macro fun M7_ITM_UP_SPREAD(): u64 { 5_000_000 }
public macro fun M7_ITM_UP_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_ITM_UP_ASK(): u64 { 968_418_138 }
public macro fun M7_ITM_UP_BID(): u64 { 958_418_138 }
public macro fun M7_ITM_UP_COST(): u64 { 9_684_181 }
public macro fun M7_ITM_UP_REDEEM_PAYOUT(): u64 { 9_584_181 }
// M7_ATM_UP_UTIL50: strike=72167.96, UP, qty=10.0, util=50%
//   price=0.491915108, spread=0.009998693, util_spread=0.010000000, ask=0.511913801, bid=0.471916416
public macro fun M7_ATM_UP_UTIL50_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_UP_UTIL50_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_ATM_UP_UTIL50_VAULT_LIABILITY(): u64 { 360_839_793_450 }
public macro fun M7_ATM_UP_UTIL50_PRICE(): u64 { 491_915_108 }
public macro fun M7_ATM_UP_UTIL50_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_UP_UTIL50_UTIL_SPREAD(): u64 { 10_000_000 }
public macro fun M7_ATM_UP_UTIL50_ASK(): u64 { 511_913_800 }
public macro fun M7_ATM_UP_UTIL50_BID(): u64 { 471_916_415 }
public macro fun M7_ATM_UP_UTIL50_COST(): u64 { 5_119_138 }
public macro fun M7_ATM_UP_UTIL50_REDEEM_PAYOUT(): u64 { 4_719_164 }
// M7_ATM_UP_UTIL80: strike=72167.96, UP, qty=10.0, util=80%
//   price=0.491915108, spread=0.009998693, util_spread=0.025600000, ask=0.527513801, bid=0.456316416
public macro fun M7_ATM_UP_UTIL80_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_UP_UTIL80_QUANTITY(): u64 { 10_000_000 }
public macro fun M7_ATM_UP_UTIL80_VAULT_LIABILITY(): u64 { 577_343_669_520 }
public macro fun M7_ATM_UP_UTIL80_PRICE(): u64 { 491_915_108 }
public macro fun M7_ATM_UP_UTIL80_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_UP_UTIL80_UTIL_SPREAD(): u64 { 25_600_000 }
public macro fun M7_ATM_UP_UTIL80_ASK(): u64 { 527_513_800 }
public macro fun M7_ATM_UP_UTIL80_BID(): u64 { 456_316_415 }
public macro fun M7_ATM_UP_UTIL80_COST(): u64 { 5_275_138 }
public macro fun M7_ATM_UP_UTIL80_REDEEM_PAYOUT(): u64 { 4_563_164 }
// M7_ATM_UP_SMALL: strike=72167.96, UP, qty=0.001, util=0%
//   price=0.491915108, spread=0.009998693, util_spread=0.000000000, ask=0.501913801, bid=0.481916416
public macro fun M7_ATM_UP_SMALL_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_UP_SMALL_QUANTITY(): u64 { 1_000 }
public macro fun M7_ATM_UP_SMALL_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_ATM_UP_SMALL_PRICE(): u64 { 491_915_108 }
public macro fun M7_ATM_UP_SMALL_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_UP_SMALL_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_ATM_UP_SMALL_ASK(): u64 { 501_913_800 }
public macro fun M7_ATM_UP_SMALL_BID(): u64 { 481_916_415 }
public macro fun M7_ATM_UP_SMALL_COST(): u64 { 501 }
public macro fun M7_ATM_UP_SMALL_REDEEM_PAYOUT(): u64 { 481 }
// M7_ATM_UP_LARGE: strike=72167.96, UP, qty=500.0, util=0%
//   price=0.491915108, spread=0.009998693, util_spread=0.000000000, ask=0.501913801, bid=0.481916416
public macro fun M7_ATM_UP_LARGE_STRIKE(): u64 { 72_167_958_690_000 }
public macro fun M7_ATM_UP_LARGE_QUANTITY(): u64 { 500_000_000 }
public macro fun M7_ATM_UP_LARGE_VAULT_LIABILITY(): u64 { 0 }
public macro fun M7_ATM_UP_LARGE_PRICE(): u64 { 491_915_108 }
public macro fun M7_ATM_UP_LARGE_SPREAD(): u64 { 9_998_692 }
public macro fun M7_ATM_UP_LARGE_UTIL_SPREAD(): u64 { 0 }
public macro fun M7_ATM_UP_LARGE_ASK(): u64 { 501_913_800 }
public macro fun M7_ATM_UP_LARGE_BID(): u64 { 481_916_415 }
public macro fun M7_ATM_UP_LARGE_COST(): u64 { 250_956_900 }
public macro fun M7_ATM_UP_LARGE_REDEEM_PAYOUT(): u64 { 240_958_207 }
