#!/usr/bin/env python3
"""
Generates ground-truth test vectors for the predict package.

Outputs:
  generated_math.move   — ln, exp, normal_cdf test vectors
  generated_oracle.move — SVI + Black-Scholes oracle pricing scenarios

Source of truth: scipy.stats.norm + Python math
Usage: python3 generate.py
Dependencies: pip install scipy
"""

import math
import random
from pathlib import Path

from scipy.optimize import brentq
from scipy.stats import norm

# ====================================================================
# Shared constants
# ====================================================================

FLOAT_SCALING = 1_000_000_000
U64_MAX = 2**64 - 1
SECONDS_IN_YEAR = 365.0 * 24 * 60 * 60

DATA_DIR = Path(__file__).parent
MATH_OUTPUT = DATA_DIR / "generated_math.move"
ORACLE_OUTPUT = DATA_DIR / "generated_oracle.move"

# ====================================================================
# Shared scaling helpers
# ====================================================================


def to_float_scaled(value: float) -> int:
    """Convert to FLOAT_SCALING (1e9), floor-truncated."""
    return int(value * FLOAT_SCALING)


def to_bool(val) -> str:
    """Convert a Python truthy value to a Move bool literal."""
    return "true" if val else "false"


def fmt_u64(value: int) -> str:
    """Format an integer with underscore separators for Move readability."""
    return f"{value:_}"


# ====================================================================
# Move file writer
# ====================================================================


class MoveWriter:
    """Builds a #[test_only] Move module with generated constants."""

    def __init__(self):
        self.lines: list[str] = []

    def header(self, module_name: str):
        self.lines.append("// DO NOT EDIT — generated by generate.py")
        self.lines.append(
            "// Source of truth: scipy.stats.norm + Python math"
        )
        self.lines.append(
            "// Regenerate: cd tests/generated_tests && python3 generate.py"
        )
        self.lines.append("")
        self.lines.append("#[test_only]")
        self.lines.append(f"module deepbook_predict::{module_name};")

    def blank(self):
        self.lines.append("")

    def section(self, title: str):
        self.blank()
        self.lines.append(f"// === {title} ===")

    def raw(self, text: str):
        self.lines.append(text)

    def write(self, path: Path):
        with open(path, "w") as f:
            f.write("\n".join(self.lines))
            f.write("\n")
        print(f"Wrote {path} ({len(self.lines)} lines)")


# ####################################################################
#  MATH — ln, exp, normal_cdf test vectors
# ####################################################################

# ====================================================================
# Math constants
# ====================================================================

SEED = 42
N_RANDOM_PER_FUNCTION = 200

MAX_EXP_INPUT = 23_638_153_699  # contract aborts above this with EExpOverflow

LN_EXP_MAX = 19.26              # 10^19.26 ≈ u64_max
EXP_NEG_MAX = MAX_EXP_INPUT
CDF_RAND_MAX = 8 * FLOAT_SCALING

# ====================================================================
# Math handpicked + edge case inputs
# ====================================================================

LN_HANDPICKED = [
    1 * FLOAT_SCALING,       # ln(1) = 0
    2 * FLOAT_SCALING,       # ln(2)
    4 * FLOAT_SCALING,       # ln(4)
    8 * FLOAT_SCALING,       # ln(8)
    16 * FLOAT_SCALING,      # ln(16)
    2_718_281_828,            # ln(e) ≈ 1
    500_000_000,             # ln(0.5) = -ln(2)
    250_000_000,             # ln(0.25) = -ln(4)
    100_000_000,             # ln(0.1)
    999_000_000,             # ln(0.999) — tiny negative
    1_001_000_000,           # ln(1.001) — tiny positive
    1_500_000_000,           # ln(1.5)
    3_000_000_000,           # ln(3)
    5_000_000_000,           # ln(5)
    7_000_000_000,           # ln(7)
    10_000_000_000,          # ln(10)
    100_000_000_000,         # ln(100)
    1_000_000_000_000,       # ln(1000)
]

LN_EDGE_CASES = [
    1,                       # minimum valid input (ln(1e-9))
    2,                       # near minimum
    U64_MAX,                 # maximum u64
    U64_MAX - 1,             # near maximum
    FLOAT_SCALING - 1,       # just below 1.0
    FLOAT_SCALING + 1,       # just above 1.0
]

EXP_HANDPICKED = [
    (0, False),                             # e^0 = 1
    (FLOAT_SCALING, False),                 # e^1 = e
    (FLOAT_SCALING, True),                  # e^(-1) = 1/e
    (693_147_180, False),                   # e^ln2 = 2
    (693_147_180, True),                    # e^(-ln2) = 0.5
    (1_386_294_361, False),                 # e^ln4 = 4
    (1_386_294_361, True),                  # e^(-ln4) = 0.25
    (2_079_441_541, False),                 # e^ln8 = 8
    (2_079_441_541, True),                  # e^(-ln8) = 0.125
]

EXP_EDGE_CASES = [
    (MAX_EXP_INPUT, False),                 # max valid positive input
    (MAX_EXP_INPUT - 1, False),             # one below max
    (50 * FLOAT_SCALING, True),             # e^(-50) → 0
    (U64_MAX, True),                        # max u64 negative → 0
    (1, False),                             # e^(1e-9) ≈ 1
    (1, True),                              # e^(-1e-9) ≈ 1
]

CDF_HANDPICKED = [
    (0, False),                             # Φ(0) = 0.5
    (0, True),                              # Φ(-0) = 0.5
    (FLOAT_SCALING, False),                 # Φ(1) ≈ 0.841
    (FLOAT_SCALING, True),                  # Φ(-1) ≈ 0.159
    (2 * FLOAT_SCALING, False),             # Φ(2)
    (2 * FLOAT_SCALING, True),              # Φ(-2)
    (3 * FLOAT_SCALING, False),             # Φ(3)
    (3 * FLOAT_SCALING, True),              # Φ(-3)
]

CDF_EDGE_CASES = [
    (8 * FLOAT_SCALING, False),             # Φ(8) ≈ FLOAT
    (8 * FLOAT_SCALING, True),              # Φ(-8) ≈ 0
    (8 * FLOAT_SCALING + 1, False),         # just above clamp → FLOAT
    (8 * FLOAT_SCALING + 1, True),          # just above clamp → 0
    (U64_MAX, False),                       # → FLOAT
    (U64_MAX, True),                        # → 0
    (1, False),                             # Φ(1e-9) ≈ 0.5
    (1, True),                              # Φ(-1e-9) ≈ 0.5
    (662_000_000, False),                   # near SMALL_THRESHOLD (0.66291)
    (662_000_000, True),
    (5_656_000_000, False),                 # near MEDIUM_THRESHOLD (sqrt(32))
    (5_656_000_000, True),
]

# ====================================================================
# Math ground truth computation
# ====================================================================


def compute_ln(input_scaled: int) -> tuple[int, bool]:
    x = input_scaled / FLOAT_SCALING
    val = math.log(x)
    return to_float_scaled(abs(val)), val < 0


def compute_exp(input_scaled: int, is_negative: bool) -> int:
    x = input_scaled / FLOAT_SCALING
    return to_float_scaled(math.exp(-x if is_negative else x))


def compute_cdf(input_scaled: int, is_negative: bool) -> int:
    x = input_scaled / FLOAT_SCALING
    if x > 8.0:
        return 0 if is_negative else FLOAT_SCALING
    return to_float_scaled(norm.cdf(-x if is_negative else x))


# ====================================================================
# Math random input generation
# ====================================================================


def random_ln_inputs(rng: random.Random, n: int, existing: list[int]) -> list[int]:
    cases = list(existing)
    while len(cases) < len(existing) + n:
        t = rng.random() ** 2
        exp = t * LN_EXP_MAX
        x = min(U64_MAX, max(FLOAT_SCALING, int(10 ** exp)))
        if x not in cases:
            cases.append(x)
    return cases[len(existing):]


def random_exp_inputs(rng: random.Random, n: int, existing: list[tuple[int, bool]]) -> list[tuple[int, bool]]:
    cases = list(existing)
    half = n // 2
    pos_added = 0
    neg_added = 0

    while pos_added + neg_added < n:
        t = rng.random() ** 2
        if pos_added < half:
            entry = (int(t * MAX_EXP_INPUT), False)
            if entry not in cases:
                cases.append(entry)
                pos_added += 1
        else:
            x = int(t * EXP_NEG_MAX)
            entry = (x, True)
            if entry not in cases and compute_exp(x, True) > 0:
                cases.append(entry)
                neg_added += 1

    return cases[len(existing):]


def random_cdf_inputs(rng: random.Random, n: int, existing: list[tuple[int, bool]]) -> list[tuple[int, bool]]:
    cases = list(existing)
    half = n // 2
    added = 0

    while added < n:
        t = rng.random() ** 2
        x = int(t * CDF_RAND_MAX)
        is_neg = added >= half
        entry = (x, is_neg)
        if entry in cases:
            continue
        expected = compute_cdf(x, is_neg)
        if expected < 1_000 or expected > FLOAT_SCALING - 1_000:
            continue
        cases.append(entry)
        added += 1

    return cases[len(existing):]


# ====================================================================
# Math vector emission
# ====================================================================


def emit_ln_vector(w: MoveWriter, cases: list[int]):
    n = len(cases)
    w.section(f"ln test vector ({n} cases)")
    w.blank()
    w.raw("public struct LnCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    expected_mag: u64,")
    w.raw("    expected_neg: bool,")
    w.raw("}")
    w.blank()
    w.raw("public fun ln_input(c: &LnCase): u64 { c.input }")
    w.raw("public fun ln_expected_mag(c: &LnCase): u64 { c.expected_mag }")
    w.raw("public fun ln_expected_neg(c: &LnCase): bool { c.expected_neg }")
    w.blank()
    w.raw("public fun ln_cases(): vector<LnCase> { vector[")

    for input_scaled in cases:
        mag, neg = compute_ln(input_scaled)
        neg_str = "true" if neg else "false"
        w.raw(
            f"    LnCase {{ input: {fmt_u64(input_scaled)}, "
            f"expected_mag: {fmt_u64(mag)}, expected_neg: {neg_str} }},"
        )

    w.raw("]}")


def emit_exp_vector(w: MoveWriter, cases: list[tuple[int, bool]]):
    n = len(cases)
    w.section(f"exp test vector ({n} cases)")
    w.blank()
    w.raw("public struct ExpCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    is_negative: bool,")
    w.raw("    expected: u64,")
    w.raw("}")
    w.blank()
    w.raw("public fun exp_input(c: &ExpCase): u64 { c.input }")
    w.raw("public fun exp_is_negative(c: &ExpCase): bool { c.is_negative }")
    w.raw("public fun exp_expected(c: &ExpCase): u64 { c.expected }")
    w.blank()
    w.raw("public fun exp_cases(): vector<ExpCase> { vector[")

    for input_scaled, is_neg in cases:
        expected = compute_exp(input_scaled, is_neg)
        neg_str = "true" if is_neg else "false"
        w.raw(
            f"    ExpCase {{ input: {fmt_u64(input_scaled)}, "
            f"is_negative: {neg_str}, expected: {fmt_u64(expected)} }},"
        )

    w.raw("]}")


def emit_cdf_vector(w: MoveWriter, cases: list[tuple[int, bool]]):
    n = len(cases)
    w.section(f"Normal CDF test vector ({n} cases)")
    w.blank()
    w.raw("public struct CdfCase has copy, drop {")
    w.raw("    input: u64,")
    w.raw("    is_negative: bool,")
    w.raw("    expected: u64,")
    w.raw("}")
    w.blank()
    w.raw("public fun cdf_input(c: &CdfCase): u64 { c.input }")
    w.raw("public fun cdf_is_negative(c: &CdfCase): bool { c.is_negative }")
    w.raw("public fun cdf_expected(c: &CdfCase): u64 { c.expected }")
    w.blank()
    w.raw("public fun cdf_cases(): vector<CdfCase> { vector[")

    for input_scaled, is_neg in cases:
        expected = compute_cdf(input_scaled, is_neg)
        neg_str = "true" if is_neg else "false"
        w.raw(
            f"    CdfCase {{ input: {fmt_u64(input_scaled)}, "
            f"is_negative: {neg_str}, expected: {fmt_u64(expected)} }},"
        )

    w.raw("]}")


def generate_math():
    """Generate generated_math.move."""
    rng = random.Random(SEED)

    ln_fixed = LN_HANDPICKED + LN_EDGE_CASES
    ln_cases = ln_fixed + random_ln_inputs(rng, N_RANDOM_PER_FUNCTION, ln_fixed)

    exp_fixed = EXP_HANDPICKED + EXP_EDGE_CASES
    exp_cases = exp_fixed + random_exp_inputs(rng, N_RANDOM_PER_FUNCTION, exp_fixed)

    cdf_fixed = CDF_HANDPICKED + CDF_EDGE_CASES
    cdf_cases = cdf_fixed + random_cdf_inputs(rng, N_RANDOM_PER_FUNCTION, cdf_fixed)

    w = MoveWriter()
    w.header("generated_math")
    emit_ln_vector(w, ln_cases)
    emit_exp_vector(w, exp_cases)
    emit_cdf_vector(w, cdf_cases)
    w.write(MATH_OUTPUT)


# ####################################################################
#  ORACLE — SVI + Black-Scholes pricing scenarios
# ####################################################################

# ====================================================================
# Oracle constants
# ====================================================================

# Protocol quote bounds: only produce strikes where price is in [0.1c, 99.9c]
MIN_QUOTE_PRICE = 0.001
MAX_QUOTE_PRICE = 0.999

# ====================================================================
# Oracle ground truth computation
# ====================================================================


def svi_total_variance(
    k: float, a: float, b: float, rho: float, m: float, sigma: float
) -> float:
    """SVI total variance: a + b * (rho*(k-m) + sqrt((k-m)^2 + sigma^2))"""
    km = k - m
    return a + b * (rho * km + math.sqrt(km * km + sigma * sigma))


def binary_price(
    forward: float,
    strike: float,
    a: float,
    b: float,
    rho: float,
    m: float,
    sigma: float,
    rate: float,
    t: float,
    is_call: bool,
) -> float:
    """Binary option price via SVI + Black-Scholes.

    Binary call (UP) = discount * N(d2)
    Binary put (DN)  = discount * N(-d2)
    d2 = (-k - total_var/2) / sqrt(total_var), k = ln(strike/forward)
    """
    k = math.log(strike / forward)
    tv = svi_total_variance(k, a, b, rho, m, sigma)
    if tv <= 0:
        raise ValueError(f"Non-positive total variance: {tv}")
    sqrt_tv = math.sqrt(tv)
    d2 = (-k - tv / 2) / sqrt_tv
    discount = math.exp(-rate * t)
    return discount * norm.cdf(d2 if is_call else -d2)


def compute_strike_prices(
    forward: float, svi: dict, rate: float, t: float,
    strike_specs: list[tuple[str, float]],
) -> list[dict]:
    """Compute expected UP/DN prices for a list of strikes."""
    points = []
    for _label, strike in strike_specs:
        up = binary_price(forward, strike, **svi, rate=rate, t=t, is_call=True)
        dn = binary_price(forward, strike, **svi, rate=rate, t=t, is_call=False)
        if up < MIN_QUOTE_PRICE and dn < MIN_QUOTE_PRICE:
            continue
        points.append({
            "strike": to_float_scaled(strike),
            "expected_up": to_float_scaled(up),
            "expected_dn": to_float_scaled(dn),
        })
    return points


def svi_to_move(svi: dict, rate: float) -> dict:
    """Convert signed-float SVI params to Move-format unsigned + sign flag."""
    return {
        "a": to_float_scaled(abs(svi["a"])),
        "b": to_float_scaled(abs(svi["b"])),
        "rho": to_float_scaled(abs(svi["rho"])),
        "rho_neg": svi["rho"] < 0,
        "m": to_float_scaled(abs(svi["m"])),
        "m_neg": svi["m"] < 0,
        "sigma": to_float_scaled(svi["sigma"]),
        "rate": to_float_scaled(rate),
    }


# ====================================================================
# Oracle scenario data
# ====================================================================

# Standard SVI baseline: a=0, b=1, rho=0, m=0, sigma=0.25
STD_SVI = {"a": 0.0, "b": 1.0, "rho": 0.0, "m": 0.0, "sigma": 0.25}

T_SHORT = 1e6 / (SECONDS_IN_YEAR * 1000)
EXPIRY_SHORT = 1_000_000
NOW_SHORT = 0

T_1YR = 1.0
EXPIRY_1YR = int(SECONDS_IN_YEAR * 1000)

TARGET_D2S = [-2.0, -1.0, 0.0, 1.0, 2.0]

# (name, svi_params, rate, t, expiry_ms, now_ms, strike_mode)
SYNTHETIC_SCENARIOS = [
    ("STD",          STD_SVI,                              0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "d2"),
    ("STD_5PCT_1YR", STD_SVI,                              0.05, T_1YR,   EXPIRY_1YR,   0,         "d2"),
    ("FULL_SVI",     {"a": 0.05, "b": 0.8, "rho": -0.3,
                      "m": 0.1, "sigma": 0.2},             0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "atm"),
    ("SMALL_SIGMA",  {**STD_SVI, "sigma": 0.01},           0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "atm"),
    ("NONZERO_A",    {**STD_SVI, "a": 0.1},                0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "atm"),
    ("NEG_RHO",      {**STD_SVI, "rho": -0.3},             0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "d2"),
    ("NONZERO_M",    {**STD_SVI, "m": 0.1},                0.0,  T_SHORT, EXPIRY_SHORT, NOW_SHORT, "d2"),
]

# Extracted from oracle_prices_mar17.csv + oracle_svi_mar17.csv.
# 6 diversity-sampled snapshots at varying time-to-expiry (7d → 31s).
REAL_WORLD_SNAPSHOTS = [
    {   # S0: ~7d TTE
        "spot": 70_770_295_760_000, "forward": 70_782_878_010_000,
        "svi": {"a": 0.00108, "b": 0.04228, "rho": -0.33266,
                "m": -0.00302, "sigma": 0.12698},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_241_327_070,
        "ints": {"a": 1_080_000, "b": 42_280_000, "rho": 332_660_000,
                 "m": 3_020_000, "sigma": 126_980_000, "rate": 35_000_000},
    },
    {   # S1: ~1.2d TTE
        "spot": 74_228_286_720_000, "forward": 74_241_496_580_000,
        "svi": {"a": 0.00055, "b": 0.02687, "rho": -0.36090,
                "m": -0.00416, "sigma": 0.07540},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_735_844_810,
        "ints": {"a": 550_000, "b": 26_870_000, "rho": 360_900_000,
                 "m": 4_160_000, "sigma": 75_400_000, "rate": 35_000_000},
    },
    {   # S2: ~5h TTE
        "spot": 74_105_490_370_000, "forward": 74_127_848_210_000,
        "svi": {"a": 0.00096, "b": 0.01290, "rho": -0.64061,
                "m": -0.01601, "sigma": 0.03118},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_825_103_183,
        "ints": {"a": 960_000, "b": 12_900_000, "rho": 640_610_000,
                 "m": 16_010_000, "sigma": 31_180_000, "rate": 35_000_000},
    },
    {   # S3: ~1h TTE
        "spot": 72_385_193_560_000, "forward": 72_523_227_120_000,
        "svi": {"a": 0.00105, "b": 0.01236, "rho": -0.52661,
                "m": -0.00369, "sigma": 0.05032},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_838_922_225,
        "ints": {"a": 1_050_000, "b": 12_360_000, "rho": 526_610_000,
                 "m": 3_690_000, "sigma": 50_320_000, "rate": 35_000_000},
    },
    {   # S4: ~2m TTE
        "spot": 72_137_857_040_000, "forward": 72_167_958_690_000,
        "svi": {"a": 0.00077, "b": 0.01549, "rho": -0.39906,
                "m": 0.00454, "sigma": 0.05436},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_842_876_472,
        "ints": {"a": 770_000, "b": 15_490_000, "rho": 399_060_000,
                 "m": 4_540_000, "sigma": 54_360_000, "rate": 35_000_000},
    },
    {   # S5: ~31s TTE
        "spot": 72_137_857_040_000, "forward": 72_167_958_690_000,
        "svi": {"a": 0.00077, "b": 0.01549, "rho": -0.39906,
                "m": 0.00454, "sigma": 0.05436},
        "rate": 0.035,
        "expiry_ms": 1_773_843_002_405, "now_ms": 1_773_842_971_565,
        "ints": {"a": 770_000, "b": 15_490_000, "rho": 399_060_000,
                 "m": 4_540_000, "sigma": 54_360_000, "rate": 35_000_000},
    },
]

# ====================================================================
# Oracle strike generation
# ====================================================================


def find_strikes_for_d2_targets(
    forward: float, svi: dict, rate: float, t: float,
) -> list[tuple[str, float]]:
    """Reverse-solve for strikes that produce specific d2 values."""
    results = []
    discount = math.exp(-rate * t)

    for d2_target in TARGET_D2S:
        price = discount * norm.cdf(d2_target)
        if price < MIN_QUOTE_PRICE or price > MAX_QUOTE_PRICE:
            continue

        def d2_at_strike(s, _target=d2_target):
            if s <= 0:
                return 100.0
            k = math.log(s / forward)
            tv = svi_total_variance(k, **svi)
            if tv <= 0:
                return 100.0
            return (-k - tv / 2) / math.sqrt(tv) - _target

        try:
            strike = brentq(d2_at_strike, forward * 0.001, forward * 100.0)
        except ValueError:
            continue

        if abs(d2_target) < 0.01:
            label = "ATM"
        elif d2_target > 0:
            label = f"ITM_D{abs(d2_target):.0f}"
        else:
            label = f"OTM_D{abs(d2_target):.0f}"

        results.append((label, strike))

    return results


# ====================================================================
# Oracle scenario building
# ====================================================================


def build_synthetic_scenarios() -> tuple[list[dict], list[tuple[str, int]]]:
    scenarios = []
    index_names = []

    for name, svi, rate, t, expiry_ms, now_ms, strike_mode in SYNTHETIC_SCENARIOS:
        forward = 100.0
        if strike_mode == "d2":
            strike_specs = find_strikes_for_d2_targets(forward, svi, rate, t)
        else:
            strike_specs = [("ATM", forward)]

        strike_points = compute_strike_prices(forward, svi, rate, t, strike_specs)
        scenario = {
            "spot": to_float_scaled(forward),
            "forward": to_float_scaled(forward),
            **svi_to_move(svi, rate),
            "expiry_ms": expiry_ms,
            "now_ms": now_ms,
            "strike_points": strike_points,
        }
        scenarios.append(scenario)
        index_names.append((name, len(scenarios) - 1))

    return scenarios, index_names


def build_real_world_scenarios() -> tuple[list[dict], list[tuple[str, int]]]:
    scenarios = []
    index_names = []

    for idx, snap in enumerate(REAL_WORLD_SNAPSHOTS):
        forward = snap["forward"] / FLOAT_SCALING
        tte_ms = snap["expiry_ms"] - snap["now_ms"]
        t = tte_ms / 1000.0 / SECONDS_IN_YEAR

        strike_specs = [
            ("ATM", forward),
            ("OTM5", forward * 1.05),
            ("OTM10", forward * 1.10),
            ("ITM5", forward * 0.95),
            ("ITM10", forward * 0.90),
        ]

        ints = snap["ints"]
        strike_points = compute_strike_prices(
            forward, snap["svi"], snap["rate"], t, strike_specs)

        scenario = {
            "spot": snap["spot"],
            "forward": snap["forward"],
            "a": ints["a"], "b": ints["b"],
            "rho": ints["rho"], "rho_neg": snap["svi"]["rho"] < 0,
            "m": ints["m"], "m_neg": snap["svi"]["m"] < 0,
            "sigma": ints["sigma"], "rate": ints["rate"],
            "expiry_ms": snap["expiry_ms"],
            "now_ms": snap["now_ms"],
            "strike_points": strike_points,
        }
        scenarios.append(scenario)
        index_names.append((f"S{idx}", len(scenarios) - 1))

    return scenarios, index_names


# ====================================================================
# Oracle emission
# ====================================================================

ORACLE_FIELDS = [
    ("spot", "u64"), ("forward", "u64"),
    ("a", "u64"), ("b", "u64"), ("rho", "u64"), ("rho_neg", "bool"),
    ("m", "u64"), ("m_neg", "bool"), ("sigma", "u64"), ("rate", "u64"),
    ("expiry_ms", "u64"), ("now_ms", "u64"),
]

SCENARIO_FIELDS = [
    "spot", "forward", "a", "b", "rho", "rho_neg",
    "m", "m_neg", "sigma", "rate", "expiry_ms", "now_ms",
]


def emit_oracle_structs(w: MoveWriter):
    w.blank()
    w.raw("public struct StrikePoint has copy, drop {")
    w.raw("    strike: u64,")
    w.raw("    expected_up: u64,")
    w.raw("    expected_dn: u64,")
    w.raw("}")
    w.blank()
    w.raw("public struct OracleScenario has copy, drop {")
    for name, typ in ORACLE_FIELDS:
        w.raw(f"    {name}: {typ},")
    w.raw("    strike_points: vector<StrikePoint>,")
    w.raw("}")


def emit_oracle_getters(w: MoveWriter):
    w.blank()
    for name, typ in ORACLE_FIELDS:
        w.raw(f"public fun {name}(s: &OracleScenario): {typ} {{ s.{name} }}")
    w.raw(
        "public fun strike_points(s: &OracleScenario): "
        "&vector<StrikePoint> { &s.strike_points }"
    )
    w.blank()
    w.raw("public fun strike(sp: &StrikePoint): u64 { sp.strike }")
    w.raw("public fun expected_up(sp: &StrikePoint): u64 { sp.expected_up }")
    w.raw("public fun expected_dn(sp: &StrikePoint): u64 { sp.expected_dn }")


def emit_oracle_scenario(w: MoveWriter, scenario: dict, label: str, index: int):
    w.raw(f"        // Index {index}: {label}")
    w.raw("        OracleScenario {")
    for field in SCENARIO_FIELDS:
        val = scenario[field]
        formatted = to_bool(val) if isinstance(val, bool) else fmt_u64(val)
        w.raw(f"            {field}: {formatted},")
    w.raw("            strike_points: vector[")
    for sp in scenario["strike_points"]:
        w.raw(
            f"                StrikePoint {{ "
            f"strike: {fmt_u64(sp['strike'])}, "
            f"expected_up: {fmt_u64(sp['expected_up'])}, "
            f"expected_dn: {fmt_u64(sp['expected_dn'])} }},"
        )
    w.raw("            ],")
    w.raw("        },")


def emit_scenarios_vector(
    w: MoveWriter, scenarios: list[dict], index_names: list[tuple[str, int]],
):
    w.blank()
    w.raw("public fun scenarios(): vector<OracleScenario> {")
    w.raw("    vector[")
    for i, scenario in enumerate(scenarios):
        label = next((n for n, idx in index_names if idx == i), f"Index {i}")
        emit_oracle_scenario(w, scenario, label, i)
    w.raw("    ]")
    w.raw("}")


def generate_oracle():
    """Generate generated_oracle.move."""
    syn_scenarios, syn_names = build_synthetic_scenarios()
    real_scenarios, real_names = build_real_world_scenarios()

    all_scenarios = syn_scenarios + real_scenarios
    all_names = syn_names + [
        (name, idx + len(syn_scenarios)) for name, idx in real_names
    ]

    print(f"Oracle: {len(syn_scenarios)} synthetic + {len(real_scenarios)} real-world scenarios")

    w = MoveWriter()
    w.header("generated_oracle")
    emit_oracle_structs(w)
    emit_oracle_getters(w)
    emit_scenarios_vector(w, all_scenarios, all_names)
    w.write(ORACLE_OUTPUT)


# ####################################################################
#  Main
# ####################################################################


def main():
    generate_math()
    generate_oracle()


if __name__ == "__main__":
    main()
