#!/usr/bin/env python3
"""Deterministic structural checks for the Predict unit-test architecture."""

from __future__ import annotations

import re
import sys
from pathlib import Path

TESTS = Path(__file__).resolve().parent
REPO = TESTS.parents[2]
SCOPES = {"framework", "mechanics", "structure", "flow"}
INTENTS = {"behavior", "guard", "boundary", "rounding", "accounting", "reference", "policy"}
COMMENTS = re.compile(r"//[^\n]*|/\*.*?\*/", re.DOTALL)


def relative(path: Path) -> str:
    return path.relative_to(REPO).as_posix()


def source_without_comments(source: str) -> str:
    return COMMENTS.sub("", source)


def scenario_constructor_count(source: str) -> int:
    namespace_aliases = set(
        re.findall(r"\btest_scenario\s+as\s+([a-z][a-z0-9_]*)\b", source)
    )
    function_aliases: set[str] = set()
    for group in re.finditer(r"\btest_scenario\s*::\s*\{(?P<body>[^}]*)\}", source, re.DOTALL):
        body = group.group("body")
        namespace_aliases.update(
            re.findall(r"\bSelf\s+as\s+([a-z][a-z0-9_]*)\b", body)
        )
        for function in re.finditer(
            r"\bbegin\b(?:\s+as\s+([a-z][a-z0-9_]*))?",
            body,
        ):
            function_aliases.add(function.group(1) or "begin")
    for function in re.finditer(
        r"\buse\s+[^;]*\btest_scenario\s*::\s*begin\b"
        r"(?:\s+as\s+([a-z][a-z0-9_]*))?\s*;",
        source,
    ):
        function_aliases.add(function.group(1) or "begin")

    count = len(re.findall(r"\btest_scenario\s*::\s*begin\s*\(", source))
    count += sum(
        len(re.findall(rf"\b{re.escape(alias)}\s*::\s*begin\s*\(", source))
        for alias in namespace_aliases
    )
    count += sum(
        len(re.findall(rf"(?<!::)\b{re.escape(alias)}\s*\(", source))
        for alias in function_aliases
    )
    return count


def accesses_scenario_api(source: str) -> bool:
    if re.search(r"\bScenario\b|\btest_scenario\s*::\s*(?:begin|Self)\b", source):
        return True
    group = re.search(r"\btest_scenario\s*::\s*\{(?P<body>[^}]*)\}", source, re.DOTALL)
    if group and re.search(r"\b(?:begin|Self)\b", group.group("body")):
        return True
    return re.search(r"\btest_scenario\s+as\s+[a-z][a-z0-9_]*\b", source) is not None


def main() -> int:
    errors: list[str] = []
    move_files = sorted(TESTS.rglob("*.move"))
    world_file = TESTS / "framework" / "test_world.move"

    scenario_fields: list[tuple[Path, int]] = []
    world_constructor_count = 0
    for path in move_files:
        text = path.read_text()
        source = source_without_comments(text)
        field_count = len(re.findall(r":\s*Scenario\b", source))
        if field_count:
            scenario_fields.append((path, field_count))
        if path == world_file:
            world_constructor_count = scenario_constructor_count(source)
        elif accesses_scenario_api(source):
            errors.append(f"{relative(path)}: test_world must own all Scenario API access")
        if path != world_file and re.search(r"\btake_shared\s*<", text):
            errors.append(f"{relative(path)}: ambient take_shared<T> is bootstrap-only")
        if path.parent == TESTS / "framework" and path != world_file:
            if re.search(r"(?:\.|::)next_tx\s*\(", text):
                errors.append(f"{relative(path)}: framework prerequisite hides next_tx")

        if not re.search(r"#\[test(?:\]|,)", text):
            continue
        scope = path.relative_to(TESTS).parts[0]
        if scope not in SCOPES:
            errors.append(f"{relative(path)}: executable module has unknown scope path '{scope}'")
            continue
        module_match = re.search(r"module\s+deepbook_predict::([a-z0-9_]+)\s*;", text)
        if not module_match:
            errors.append(f"{relative(path)}: executable module name is missing or malformed")
            continue
        module = module_match.group(1)
        if not module.startswith(f"{scope}_"):
            errors.append(f"{relative(path)}: module '{module}' does not start with '{scope}_'")
        if not any(f"_{intent}_" in f"_{module}_" for intent in INTENTS):
            errors.append(f"{relative(path)}: module '{module}' has no intent token")

    if scenario_fields != [(world_file, 1)]:
        rendered = ", ".join(
            f"{relative(path)} ({count})" for path, count in scenario_fields
        ) or "none"
        errors.append(
            f"Scenario field owner must be exactly {relative(world_file)} (1); found {rendered}"
        )
    if world_constructor_count != 1:
        errors.append(
            f"{relative(world_file)}: expected exactly one aliased test_scenario::begin constructor; "
            f"found {world_constructor_count}"
        )

    for generated in move_files:
        text = generated.read_text()
        generator_match = re.search(r"^// @generated by (\S+)$", text, re.MULTILINE)
        if not generator_match:
            continue
        generator = REPO / generator_match.group(1)
        if not generator.is_file():
            errors.append(f"{relative(generated)}: generator does not exist: {generator_match.group(1)}")
        if not re.search(r"^// Regenerate: \S+", text, re.MULTILINE):
            errors.append(f"{relative(generated)}: missing regeneration command")
        if not re.search(r"^// Check: \S+", text, re.MULTILINE):
            errors.append(f"{relative(generated)}: missing stale-output check command")

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print(f"Predict test architecture: {len(errors)} error(s)")
        return 1
    print(f"Predict test architecture: ok ({len(move_files)} Move files checked)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
