// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

#[test_only]
module deepbook_predict::oracle_tests;

use deepbook_predict::oracle::{Self, new_price_data, new_svi_params, new_curve_point};
use std::unit_test::{assert_eq, destroy};
use sui::clock;

const FLOAT: u64 = 1_000_000_000;

// === Time constants ===
const MS_PER_YEAR: u64 = 31_536_000_000;
const STALENESS_THRESHOLD_MS: u64 = 30_000;
const HALF_YEAR_MS: u64 = 15_768_000_000;

// === Common test SVI params ===
const SIGMA_25: u64 = 250_000_000;
const SIGMA_01: u64 = 10_000_000;

// === Interest rates ===
const RATE_5_PCT: u64 = 50_000_000;
const RATE_10_PCT: u64 = 100_000_000;

// === True binary option prices (generated by generate_constants.py) ===
// Standard SVI (a=0, b=1, rho=0, m=0, sigma=0.25), rate=0
const PRICE_UP_ATM: u64 = 401_293_674;
const PRICE_DN_ATM: u64 = 598_706_325;
const PRICE_UP_STRIKE_2X: u64 = 108_101_717;
const PRICE_DN_STRIKE_2X: u64 = 891_898_282;
const PRICE_UP_DEEP_ITM: u64 = 773_988_940;
const PRICE_DN_DEEP_ITM: u64 = 226_011_059;
const PRICE_UP_DEEP_OTM: u64 = 11_485_171;
const PRICE_DN_DEEP_OTM: u64 = 988_514_828;
const PRICE_UP_S50: u64 = 647_390_543;
const PRICE_DN_S50: u64 = 352_609_456;
const PRICE_UP_S80: u64 = 538_253_668;
const PRICE_DN_S80: u64 = 461_746_331;
const PRICE_UP_S100: u64 = 401_293_674;
const PRICE_DN_S100: u64 = 598_706_325;
const PRICE_UP_S120: u64 = 272_292_717;
const PRICE_DN_S120: u64 = 727_707_282;
const PRICE_UP_S150: u64 = 175_521_297;
const PRICE_DN_S150: u64 = 824_478_702;
// With discount
const DISCOUNT_5PCT_1YR: u64 = 951_229_424;
const PRICE_UP_ATM_5PCT: u64 = 381_722_350;
const PRICE_DN_ATM_5PCT: u64 = 569_507_072;
const PRICE_UP_ATM_10PCT_PARTIAL: u64 = 388_768_371;
const PRICE_DN_ATM_10PCT_PARTIAL: u64 = 580_019_318;
const DISCOUNT_10PCT_HALF_YR: u64 = 951_229_424;
// Full SVI (a=50M, b=800M, rho=-300M, m=100M, sigma=200M), rate=0
const PRICE_UP_FULL_SVI: u64 = 400_737_521;
const PRICE_DN_FULL_SVI: u64 = 599_262_478;
// Small sigma (sigma=0.01), rate=0
const PRICE_UP_SMALL_SIGMA: u64 = 480_061_194;
const PRICE_DN_SMALL_SIGMA: u64 = 519_938_805;
// Nonzero a (a=100M, rest standard), rate=0
const PRICE_UP_A100M: u64 = 383_689_888;
// Prices with 5% discount at various strikes
const PRICE_UP_S60_5PCT: u64 = 587_883_669;
const PRICE_DN_S60_5PCT: u64 = 363_345_753;
const PRICE_UP_S80_5PCT: u64 = 512_002_726;
const PRICE_DN_S80_5PCT: u64 = 439_226_696;
const PRICE_UP_S100_5PCT: u64 = 381_722_350;
const PRICE_DN_S100_5PCT: u64 = 569_507_072;
const PRICE_UP_S120_5PCT: u64 = 259_012_844;
const PRICE_DN_S120_5PCT: u64 = 692_216_578;
const PRICE_UP_S140_5PCT: u64 = 189_768_394;
const PRICE_DN_S140_5PCT: u64 = 761_461_028;

// ============================================================
// Construction and Getters
// ============================================================

#[test]
fun create_test_oracle_initial_state() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    assert_eq!(oracle.underlying_asset(), b"BTC".to_string());
    assert_eq!(oracle.spot_price(), 0);
    assert_eq!(oracle.forward_price(), 0);
    assert_eq!(oracle.expiry(), 100_000);
    assert_eq!(oracle.risk_free_rate(), 0);
    assert_eq!(oracle.timestamp(), 0);
    assert_eq!(oracle.settlement_price().is_none(), true);
    // create_test_oracle sets active=true
    assert_eq!(oracle.is_active(), true);
    assert_eq!(oracle.is_settled(), false);

    destroy(oracle);
}

#[test]
fun create_test_oracle_with_nonzero_params() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(100, 200, 300, true, 400, false, 500);
    let prices = new_price_data(50 * FLOAT, 51 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"ETH".to_string(),
        svi,
        prices,
        42,
        999_999,
        12345,
        ctx,
    );

    assert_eq!(oracle.underlying_asset(), b"ETH".to_string());
    assert_eq!(oracle.spot_price(), 50 * FLOAT);
    assert_eq!(oracle.forward_price(), 51 * FLOAT);
    assert_eq!(oracle.expiry(), 999_999);
    assert_eq!(oracle.risk_free_rate(), 42);
    assert_eq!(oracle.timestamp(), 12345);

    destroy(oracle);
}

#[test]
fun curve_point_getters() {
    let pt = new_curve_point(50 * FLOAT, 600_000_000, 400_000_000);
    assert_eq!(pt.strike(), 50 * FLOAT);
    assert_eq!(pt.up_price(), 600_000_000);
    assert_eq!(pt.dn_price(), 400_000_000);
}

// ============================================================
// Staleness
// ============================================================

#[test]
fun is_stale_returns_false_when_fresh() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(50 * FLOAT, 50 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        10_000,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    // now=0 <= 10_000 + STALENESS_THRESHOLD_MS = 40_000
    assert_eq!(oracle.is_stale(&clock), false);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun is_stale_returns_true_when_stale() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(50 * FLOAT, 50 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        10_000,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    // now=40_001 > 10_000 + STALENESS_THRESHOLD_MS = 40_000
    clock.set_for_testing(10_000 + STALENESS_THRESHOLD_MS + 1);
    assert_eq!(oracle.is_stale(&clock), true);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun is_stale_boundary_exactly_at_threshold() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(50 * FLOAT, 50 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        10_000,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    // now = 10_000 + STALENESS_THRESHOLD_MS; not strictly greater, NOT stale
    clock.set_for_testing(10_000 + STALENESS_THRESHOLD_MS);
    assert_eq!(oracle.is_stale(&clock), false);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test, expected_failure(abort_code = oracle::EOracleStale)]
fun assert_not_stale_aborts_when_stale() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(50 * FLOAT, 50 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        10_000,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(10_000 + STALENESS_THRESHOLD_MS + 1);
    oracle.assert_not_stale(&clock);

    abort
}

#[test]
fun assert_not_stale_passes_when_fresh() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(50 * FLOAT, 50 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        10_000,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(10_000 + STALENESS_THRESHOLD_MS - 1);
    oracle.assert_not_stale(&clock);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Settlement (get_binary_price -- settled path)
// ============================================================

#[test]
fun settled_above_strike_up_wins() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    // Settle at 60, strike at 50: settlement > strike, UP wins
    oracle.settle_test_oracle(60 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let up_price = oracle.get_binary_price(50 * FLOAT, true, &clock);
    let dn_price = oracle.get_binary_price(50 * FLOAT, false, &clock);

    assert_eq!(up_price, FLOAT);
    assert_eq!(dn_price, 0);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun settled_below_strike_dn_wins() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    // Settle at 40, strike at 50: settlement < strike, DN wins
    oracle.settle_test_oracle(40 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let up_price = oracle.get_binary_price(50 * FLOAT, true, &clock);
    let dn_price = oracle.get_binary_price(50 * FLOAT, false, &clock);

    assert_eq!(up_price, 0);
    assert_eq!(dn_price, FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun settled_at_strike_dn_wins() {
    // ATM settles as DOWN win: settlement_price > strike is false when equal
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    oracle.settle_test_oracle(50 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let up_price = oracle.get_binary_price(50 * FLOAT, true, &clock);
    let dn_price = oracle.get_binary_price(50 * FLOAT, false, &clock);

    assert_eq!(up_price, 0);
    assert_eq!(dn_price, FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun settled_various_strikes() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    oracle.settle_test_oracle(100 * FLOAT);

    let clock = clock::create_for_testing(ctx);

    // Strike 99: settlement > strike, UP wins
    assert_eq!(oracle.get_binary_price(99 * FLOAT, true, &clock), FLOAT);
    assert_eq!(oracle.get_binary_price(99 * FLOAT, false, &clock), 0);

    // Strike 100: settlement == strike, DN wins
    assert_eq!(oracle.get_binary_price(100 * FLOAT, true, &clock), 0);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, false, &clock), FLOAT);

    // Strike 101: settlement < strike, DN wins
    assert_eq!(oracle.get_binary_price(101 * FLOAT, true, &clock), 0);
    assert_eq!(oracle.get_binary_price(101 * FLOAT, false, &clock), FLOAT);

    // Strike 1: settlement >> strike, UP wins
    assert_eq!(oracle.get_binary_price(1 * FLOAT, true, &clock), FLOAT);
    assert_eq!(oracle.get_binary_price(1 * FLOAT, false, &clock), 0);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun settled_up_plus_dn_always_one() {
    // For settled oracle, exactly one side wins: UP + DN = FLOAT always
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    oracle.settle_test_oracle(75 * FLOAT);

    let clock = clock::create_for_testing(ctx);

    let strikes = vector[1, 50, 74, 75, 76, 100, 200];
    strikes.do!(|s| {
        let strike = s * FLOAT;
        let up = oracle.get_binary_price(strike, true, &clock);
        let dn = oracle.get_binary_price(strike, false, &clock);
        assert_eq!(up + dn, FLOAT);
    });

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// is_settled and is_active
// ============================================================

#[test]
fun is_settled_true_after_settle() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(0, 0);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    oracle.settle_test_oracle(50 * FLOAT);

    assert_eq!(oracle.is_settled(), true);
    assert_eq!(oracle.is_active(), false);
    assert_eq!(oracle.settlement_price().destroy_some(), 50 * FLOAT);

    destroy(oracle);
}

// ============================================================
// get_binary_price -- Live path (SVI + Black-Scholes)
// ============================================================

// ATM test: strike == forward, m=0, rho=0
// SVI params: a=0, b=1.0, rho=0, m=0, sigma=0.25
// Hand-traced computation:
//   k = ln(1) = (0, false)
//   k_minus_m = (0, false)
//   sq = sigma = 250_000_000
//   inner = sigma = 250_000_000 (rho=0 so rho_km=0)
//   total_var = 0 + mul(1e9, 250M) = 250_000_000
//   sqrt_var = sqrt(250M, 1e9) = 500_000_000
//   d2: sub_signed(0, true, 125_000_000, false) = (125_000_000, true)
//   d2 = div(125M, 500M) = 250_000_000, d2_neg = true
//   For UP: cdf_neg = true; normal_cdf(250M, true)
//   For DN: cdf_neg = false; normal_cdf(250M, false)
// With risk_free_rate=0, discount=1.0

#[test]
fun live_atm_up_plus_dn_equals_discount() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let strike = forward;

    let up_price = oracle.get_binary_price(strike, true, &clock);
    let dn_price = oracle.get_binary_price(strike, false, &clock);

    assert_eq!(up_price, PRICE_UP_ATM);
    assert_eq!(dn_price, PRICE_DN_ATM);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_deep_itm_up() {
    // strike << forward: UP should be significantly above 0.5
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let strike = 10 * FLOAT;

    let up_price = oracle.get_binary_price(strike, true, &clock);
    let dn_price = oracle.get_binary_price(strike, false, &clock);

    assert_eq!(up_price, PRICE_UP_DEEP_ITM);
    assert_eq!(dn_price, PRICE_DN_DEEP_ITM);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_deep_otm_up() {
    // strike >> forward: UP should be well below 0.5
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let strike = 1000 * FLOAT;

    let up_price = oracle.get_binary_price(strike, true, &clock);
    let dn_price = oracle.get_binary_price(strike, false, &clock);

    assert_eq!(up_price, PRICE_UP_DEEP_OTM);
    assert_eq!(dn_price, PRICE_DN_DEEP_OTM);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_complement_property_various_strikes() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(50 * FLOAT, true, &clock), PRICE_UP_S50);
    assert_eq!(oracle.get_binary_price(50 * FLOAT, false, &clock), PRICE_DN_S50);
    assert_eq!(oracle.get_binary_price(80 * FLOAT, true, &clock), PRICE_UP_S80);
    assert_eq!(oracle.get_binary_price(80 * FLOAT, false, &clock), PRICE_DN_S80);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, true, &clock), PRICE_UP_S100);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, false, &clock), PRICE_DN_S100);
    assert_eq!(oracle.get_binary_price(120 * FLOAT, true, &clock), PRICE_UP_S120);
    assert_eq!(oracle.get_binary_price(120 * FLOAT, false, &clock), PRICE_DN_S120);
    assert_eq!(oracle.get_binary_price(150 * FLOAT, true, &clock), PRICE_UP_S150);
    assert_eq!(oracle.get_binary_price(150 * FLOAT, false, &clock), PRICE_DN_S150);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_discount_less_than_one_for_positive_rate() {
    // With positive rate and time to expiry, discount < 1.0
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_5_PCT,
        MS_PER_YEAR, // expiry = 1 year in ms
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    let up = oracle.get_binary_price(forward, true, &clock);
    let dn = oracle.get_binary_price(forward, false, &clock);

    assert_eq!(up, PRICE_UP_ATM_5PCT);
    assert_eq!(dn, PRICE_DN_ATM_5PCT);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_discount_is_one_past_expiry() {
    // Past expiry but not settled: compute_discount returns 1.0
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_5_PCT,
        100_000, // expiry at 100_000ms
        0,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(200_000); // past expiry

    let up = oracle.get_binary_price(forward, true, &clock);
    let dn = oracle.get_binary_price(forward, false, &clock);

    // discount = 1.0 past expiry, so prices equal the zero-rate ATM values
    assert_eq!(up, PRICE_UP_ATM);
    assert_eq!(dn, PRICE_DN_ATM);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun live_up_monotonically_decreasing_with_strike() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(50 * FLOAT, true, &clock), PRICE_UP_S50);
    assert_eq!(oracle.get_binary_price(80 * FLOAT, true, &clock), PRICE_UP_S80);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, true, &clock), PRICE_UP_S100);
    assert_eq!(oracle.get_binary_price(120 * FLOAT, true, &clock), PRICE_UP_S120);
    assert_eq!(oracle.get_binary_price(200 * FLOAT, true, &clock), PRICE_UP_STRIKE_2X);
    // Monotonicity: S50 > S80 > S100 > S120 > S200
    assert_eq!(PRICE_UP_S50 > PRICE_UP_S80, true);
    assert_eq!(PRICE_UP_S80 > PRICE_UP_S100, true);
    assert_eq!(PRICE_UP_S100 > PRICE_UP_S120, true);
    assert_eq!(PRICE_UP_S120 > PRICE_UP_STRIKE_2X, true);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Exact ATM computation trace
// ============================================================

// ============================================================
// SVI parameter sensitivity
// ============================================================

#[test]
fun live_nonzero_a_increases_variance() {
    // Adding a > 0 increases total_var, which increases |d2| for ATM
    let ctx = &mut tx_context::dummy();
    let svi0 = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let svi1 = new_svi_params(100_000_000, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);

    let oracle0 = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi0,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );
    let oracle1 = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi1,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle0.get_binary_price(forward, true, &clock), PRICE_UP_ATM);
    assert_eq!(oracle1.get_binary_price(forward, true, &clock), PRICE_UP_A100M);
    // Higher a lowers ATM UP price
    assert_eq!(PRICE_UP_A100M < PRICE_UP_ATM, true);

    destroy(oracle0);
    destroy(oracle1);
    clock.destroy_for_testing();
}

#[test]
fun live_negative_rho_affects_wings() {
    // Negative rho skews the smile
    let ctx = &mut tx_context::dummy();
    let svi_no_skew = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let svi_skew = new_svi_params(0, FLOAT, 500_000_000, true, 0, false, SIGMA_25);

    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);

    let oracle_no = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi_no_skew,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );
    let oracle_sk = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi_skew,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    // Check complement property still holds with skew
    let otm_put_strike = 80 * FLOAT;
    let up_no = oracle_no.get_binary_price(otm_put_strike, true, &clock);
    let dn_no = oracle_no.get_binary_price(otm_put_strike, false, &clock);
    let up_sk = oracle_sk.get_binary_price(otm_put_strike, true, &clock);
    let dn_sk = oracle_sk.get_binary_price(otm_put_strike, false, &clock);

    assert_eq!(up_no + dn_no, FLOAT);
    assert_eq!(up_sk + dn_sk, FLOAT);

    // Prices should differ with skew
    assert!(up_no != up_sk);

    destroy(oracle_no);
    destroy(oracle_sk);
    clock.destroy_for_testing();
}

#[test]
fun live_nonzero_m_shifts_smile() {
    let ctx = &mut tx_context::dummy();
    let svi_m0 = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let svi_m_pos = new_svi_params(0, FLOAT, 0, false, 100_000_000, false, SIGMA_25);

    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);

    let oracle0 = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi_m0,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );
    let oracle1 = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi_m_pos,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    let up0 = oracle0.get_binary_price(forward, true, &clock);
    let up1 = oracle1.get_binary_price(forward, true, &clock);
    let dn0 = oracle0.get_binary_price(forward, false, &clock);
    let dn1 = oracle1.get_binary_price(forward, false, &clock);

    // ATM prices differ since m shifts the SVI surface
    assert!(up0 != up1);
    assert_eq!(up0 + dn0, FLOAT);
    assert_eq!(up1 + dn1, FLOAT);

    destroy(oracle0);
    destroy(oracle1);
    clock.destroy_for_testing();
}

#[test]
fun live_small_sigma_atm_near_half() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_01);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(forward, true, &clock), PRICE_UP_SMALL_SIGMA);
    assert_eq!(oracle.get_binary_price(forward, false, &clock), PRICE_DN_SMALL_SIGMA);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Discount computation
// ============================================================

#[test]
fun discount_positive_rate_half_year() {
    // rate=10%, half year: discount = DISCOUNT_10PCT_HALF_YR
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);

    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_10_PCT,
        HALF_YEAR_MS,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let up = oracle.get_binary_price(forward, true, &clock);
    let dn = oracle.get_binary_price(forward, false, &clock);

    let sum = up + dn;
    assert_eq!(sum, DISCOUNT_10PCT_HALF_YR);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// build_curve -- settled oracle
// ============================================================

#[test]
fun build_curve_settled_oracle() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );

    oracle.settle_test_oracle(100 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    // Settled oracle returns 2-point step function
    assert_eq!(curve.length(), 2);

    let p0 = &curve[0];
    assert_eq!(p0.strike(), 100 * FLOAT - 1);
    assert_eq!(p0.up_price(), FLOAT);
    assert_eq!(p0.dn_price(), 0);

    let p1 = &curve[1];
    assert_eq!(p1.strike(), 100 * FLOAT);
    assert_eq!(p1.up_price(), 0);
    assert_eq!(p1.dn_price(), FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// build_curve -- single strike edge case
// ============================================================

#[test]
fun build_curve_single_strike() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(100 * FLOAT, 100 * FLOAT, &clock);

    assert_eq!(curve.length(), 1);
    let pt = &curve[0];
    assert_eq!(pt.strike(), 100 * FLOAT);
    assert_eq!(pt.up_price() + pt.dn_price(), FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// build_curve -- live oracle properties
// ============================================================

#[test]
fun build_curve_live_sorted_and_complement() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    let len = curve.length();
    // At least min, forward, max
    assert!(len >= 3);

    // Sorted by strike
    let mut i = 0;
    while (i < len - 1) {
        assert!(curve[i].strike() < curve[i + 1].strike());
        i = i + 1;
    };

    // Complement: UP + DN = discount = FLOAT (rate=0)
    i = 0;
    while (i < len) {
        assert_eq!(curve[i].up_price() + curve[i].dn_price(), FLOAT);
        i = i + 1;
    };

    // UP prices monotonically non-increasing
    i = 0;
    while (i < len - 1) {
        assert!(curve[i].up_price() >= curve[i + 1].up_price());
        i = i + 1;
    };

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun build_curve_includes_forward_when_in_range() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    let mut found = false;
    curve.do_ref!(|pt| {
        if (pt.strike() == forward) found = true;
    });
    assert!(found);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun build_curve_no_duplicate_when_forward_at_boundary() {
    // When forward == min_strike, no duplicate
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(forward, 150 * FLOAT, &clock);

    // All strikes must be strictly increasing (no duplicates)
    let len = curve.length();
    let mut i = 0;
    while (i < len - 1) {
        assert!(curve[i].strike() < curve[i + 1].strike());
        i = i + 1;
    };

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun build_curve_endpoints_match_min_max() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let min_strike = 50 * FLOAT;
    let max_strike = 150 * FLOAT;
    let curve = oracle.build_curve(min_strike, max_strike, &clock);

    // First point should be min_strike, last should be max_strike
    assert_eq!(curve[0].strike(), min_strike);
    assert_eq!(curve[curve.length() - 1].strike(), max_strike);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Exact normal_cdf values from contract for specific d2 magnitudes
// ============================================================

// ============================================================
// Edge cases
// ============================================================

#[test]
fun live_forward_one_unit_above_strike() {
    // Very close to ATM: strike = forward - 1
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let strike = forward - 1;

    let up = oracle.get_binary_price(strike, true, &clock);
    let dn = oracle.get_binary_price(strike, false, &clock);

    // Should be nearly identical to ATM since difference is 1 unit
    assert_eq!(up + dn, FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun build_curve_with_positive_rate_complement() {
    // With positive rate, UP + DN = discount < FLOAT
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);

    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_5_PCT,
        MS_PER_YEAR,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    // All curve points use the same discount factor.
    // eval_strike computes: up = mul(discount, nd2), dn = discount - up
    // So up + dn = discount exactly for every point (no rounding split).
    let len = curve.length();
    let mut i = 0;
    while (i < len) {
        let sum = curve[i].up_price() + curve[i].dn_price();
        assert_eq!(sum, DISCOUNT_5PCT_1YR);
        i = i + 1;
    };

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Exact-value tests: independently compute expected oracle output
// ============================================================

#[test]
fun exact_strike_2x_forward_price() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 50 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(100 * FLOAT, true, &clock), PRICE_UP_STRIKE_2X);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, false, &clock), PRICE_DN_STRIKE_2X);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun exact_discount_with_partial_year() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_10_PCT,
        20_000_000_000,
        0,
        ctx,
    );

    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(10_000_000_000);

    assert_eq!(oracle.get_binary_price(forward, true, &clock), PRICE_UP_ATM_10PCT_PARTIAL);
    assert_eq!(oracle.get_binary_price(forward, false, &clock), PRICE_DN_ATM_10PCT_PARTIAL);

    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun exact_full_svi_params() {
    // a=50M, b=800M, rho=-300M, m=100M, sigma=200M, ATM, rate=0
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(
        50_000_000,
        800_000_000,
        300_000_000,
        true,
        100_000_000,
        false,
        200_000_000,
    );
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(forward, true, &clock), PRICE_UP_FULL_SVI);
    assert_eq!(oracle.get_binary_price(forward, false, &clock), PRICE_DN_FULL_SVI);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Edge: zero forward aborts (div by zero)
// ============================================================

#[test, expected_failure]
fun live_price_with_zero_forward_aborts() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(0, 0);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    oracle.get_binary_price(50 * FLOAT, true, &clock);

    abort
}

// ============================================================
// build_curve: forward outside range
// ============================================================

#[test]
fun build_curve_forward_outside_range() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 200 * FLOAT; // outside [50,150]
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    assert!(curve.length() >= 2);
    assert_eq!(curve[0].strike(), 50 * FLOAT);
    assert_eq!(curve[curve.length() - 1].strike(), 150 * FLOAT);

    // Sorted
    let len = curve.length();
    let mut i = 0;
    while (i < len - 1) {
        assert!(curve[i].strike() < curve[i + 1].strike());
        i = i + 1;
    };

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Settled oracle: build_curve at different settlement
// ============================================================

#[test]
fun build_curve_settled_at_75() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );
    oracle.settle_test_oracle(75 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let curve = oracle.build_curve(50 * FLOAT, 150 * FLOAT, &clock);

    assert_eq!(curve.length(), 2);
    assert_eq!(curve[0].strike(), 75 * FLOAT - 1);
    assert_eq!(curve[0].up_price(), FLOAT);
    assert_eq!(curve[0].dn_price(), 0);
    assert_eq!(curve[1].strike(), 75 * FLOAT);
    assert_eq!(curve[1].up_price(), 0);
    assert_eq!(curve[1].dn_price(), FLOAT);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Prices bounded between 0 and discount for non-extreme strikes
// ============================================================

#[test]
fun live_prices_bounded_between_zero_and_discount() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let forward = 100 * FLOAT;
    let prices = new_price_data(forward, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        RATE_5_PCT,
        MS_PER_YEAR,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);

    assert_eq!(oracle.get_binary_price(60 * FLOAT, true, &clock), PRICE_UP_S60_5PCT);
    assert_eq!(oracle.get_binary_price(60 * FLOAT, false, &clock), PRICE_DN_S60_5PCT);
    assert_eq!(oracle.get_binary_price(80 * FLOAT, true, &clock), PRICE_UP_S80_5PCT);
    assert_eq!(oracle.get_binary_price(80 * FLOAT, false, &clock), PRICE_DN_S80_5PCT);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, true, &clock), PRICE_UP_S100_5PCT);
    assert_eq!(oracle.get_binary_price(100 * FLOAT, false, &clock), PRICE_DN_S100_5PCT);
    assert_eq!(oracle.get_binary_price(120 * FLOAT, true, &clock), PRICE_UP_S120_5PCT);
    assert_eq!(oracle.get_binary_price(120 * FLOAT, false, &clock), PRICE_DN_S120_5PCT);
    assert_eq!(oracle.get_binary_price(140 * FLOAT, true, &clock), PRICE_UP_S140_5PCT);
    assert_eq!(oracle.get_binary_price(140 * FLOAT, false, &clock), PRICE_DN_S140_5PCT);

    destroy(oracle);
    clock.destroy_for_testing();
}

// ============================================================
// Abort code coverage
// ============================================================

#[test, expected_failure(abort_code = oracle::EInvalidOracleCap)]
fun activate_with_unauthorized_cap_aborts() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );
    oracle.set_active_for_testing(false);
    let cap = oracle::create_oracle_cap(ctx);
    let clock = clock::create_for_testing(ctx);

    // Cap is not registered on this oracle
    oracle.activate(&cap, &clock);

    abort
}

#[test, expected_failure(abort_code = oracle::EOracleAlreadyActive)]
fun activate_already_active_oracle_aborts() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );
    let cap = oracle::create_oracle_cap(ctx);
    oracle::register_cap(&mut oracle, &cap);
    let clock = clock::create_for_testing(ctx);

    // Oracle is already active (create_test_oracle sets active=true)
    oracle.activate(&cap, &clock);

    abort
}

#[test, expected_failure(abort_code = oracle::EOracleExpired)]
fun activate_expired_oracle_aborts() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );
    oracle.set_active_for_testing(false);
    let cap = oracle::create_oracle_cap(ctx);
    oracle::register_cap(&mut oracle, &cap);
    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(200_000);

    oracle.activate(&cap, &clock);

    abort
}

#[test, expected_failure(abort_code = oracle::EOracleExpired)]
fun update_svi_on_settled_oracle_aborts() {
    let ctx = &mut tx_context::dummy();
    let svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let mut oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        100_000,
        0,
        ctx,
    );
    let cap = oracle::create_oracle_cap(ctx);
    oracle::register_cap(&mut oracle, &cap);
    oracle::settle_test_oracle(&mut oracle, 100 * FLOAT);

    let clock = clock::create_for_testing(ctx);
    let new_svi = new_svi_params(0, FLOAT, 0, false, 0, false, SIGMA_25);
    oracle.update_svi(&cap, new_svi, 0, &clock);

    abort
}

#[test, expected_failure(abort_code = oracle::ECannotBeNegative)]
fun compute_nd2_negative_inner_aborts() {
    let ctx = &mut tx_context::dummy();
    // Adversarial SVI: rho=-1.0, sigma~0 makes inner term negative for large k
    let svi = new_svi_params(0, FLOAT, FLOAT, true, 0, false, 1);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    oracle.get_binary_price(1000 * FLOAT, true, &clock);

    abort
}

#[test, expected_failure(abort_code = oracle::EZeroVariance)]
fun zero_svi_params_on_live_oracle_aborts() {
    let ctx = &mut tx_context::dummy();
    // a=0, b=0 → total_var = 0 → division by zero in compute_nd2
    let svi = new_svi_params(0, 0, 0, false, 0, false, 0);
    let prices = new_price_data(100 * FLOAT, 100 * FLOAT);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        0,
        1_000_000,
        0,
        ctx,
    );

    let clock = clock::create_for_testing(ctx);
    oracle.get_binary_price(100 * FLOAT, true, &clock);

    abort
}
