// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/// End-to-end tests using real-world Block Scholes SVI parameters.
/// Constants generated by tests/generate_constants.py using scipy.
/// If the contract disagrees, the test fails — exposing precision errors.
#[test_only]
module deepbook_predict::realworld_tests;

use deepbook_predict::oracle::{Self, new_price_data, new_svi_params};
use std::unit_test::{assert_eq, destroy};
use sui::clock;

const S0_SPOT: u64 = 70_189_182_420_000;
const S0_FORWARD: u64 = 70_204_457_950_000;
const S0_A: u64 = 2_020_000;
const S0_B: u64 = 39_490_000;
const S0_RHO: u64 = 331_240_000;
const S0_RHO_NEG: u64 = 1;
const S0_M: u64 = 4_150_000;
const S0_M_NEG: u64 = 0;
const S0_SIGMA: u64 = 117_830_000;
const S0_RATE: u64 = 35_000_000;
const S0_EXPIRY_MS: u64 = 1_773_843_002_405;
const S0_NOW_MS: u64 = 1_773_238_202_405;
const S0_STRIKE_ATM: u64 = 70_204_457_950_000;
const S0_UP_ATM: u64 = 483_315_795;
const S0_DN_ATM: u64 = 516_013_196;
const S0_STRIKE_OTM5: u64 = 73_714_680_847_500;
const S0_UP_OTM5: u64 = 257_883_845;
const S0_DN_OTM5: u64 = 741_445_147;
const S0_STRIKE_OTM10: u64 = 77_224_903_745_000;
const S0_UP_OTM10: u64 = 114_134_407;
const S0_DN_OTM10: u64 = 885_194_585;
const S0_STRIKE_ITM5: u64 = 66_694_235_052_500;
const S0_UP_ITM5: u64 = 702_559_024;
const S0_DN_ITM5: u64 = 296_769_967;
const S0_STRIKE_ITM10: u64 = 63_184_012_155_000;
const S0_UP_ITM10: u64 = 844_267_272;
const S0_DN_ITM10: u64 = 155_061_720;
const S1_SPOT: u64 = 70_426_826_290_000;
const S1_FORWARD: u64 = 70_426_846_370_000;
const S1_A: u64 = 640_000;
const S1_B: u64 = 35_910_000;
const S1_RHO: u64 = 293_470_000;
const S1_RHO_NEG: u64 = 1;
const S1_M: u64 = 18_950_000;
const S1_M_NEG: u64 = 0;
const S1_SIGMA: u64 = 142_010_000;
const S1_RATE: u64 = 35_000_000;
const S1_EXPIRY_MS: u64 = 1_773_843_002_405;
const S1_NOW_MS: u64 = 1_773_314_547_787;
const S1_STRIKE_ATM: u64 = 70_426_846_370_000;
const S1_UP_ATM: u64 = 484_288_747;
const S1_DN_ATM: u64 = 515_124_923;
const S1_STRIKE_OTM5: u64 = 73_948_188_688_500;
const S1_UP_OTM5: u64 = 244_036_857;
const S1_DN_OTM5: u64 = 755_376_812;
const S1_STRIKE_OTM10: u64 = 77_469_531_007_000;
const S1_UP_OTM10: u64 = 95_335_712;
const S1_DN_OTM10: u64 = 904_077_958;
const S1_STRIKE_ITM5: u64 = 66_905_504_051_500;
const S1_UP_ITM5: u64 = 714_565_738;
const S1_DN_ITM5: u64 = 284_847_931;
const S1_STRIKE_ITM10: u64 = 63_384_161_733_000;
const S1_UP_ITM10: u64 = 859_668_538;
const S1_DN_ITM10: u64 = 139_745_131;
const S2_SPOT: u64 = 71_449_138_440_000;
const S2_FORWARD: u64 = 71_513_704_810_000;
const S2_A: u64 = 1_870_000;
const S2_B: u64 = 32_700_000;
const S2_RHO: u64 = 518_490_000;
const S2_RHO_NEG: u64 = 1;
const S2_M: u64 = 25_180_000;
const S2_M_NEG: u64 = 1;
const S2_SIGMA: u64 = 116_780_000;
const S2_RATE: u64 = 35_000_000;
const S2_EXPIRY_MS: u64 = 1_773_843_002_405;
const S2_NOW_MS: u64 = 1_773_389_976_437;
const S2_STRIKE_ATM: u64 = 71_513_704_810_000;
const S2_UP_ATM: u64 = 485_169_811;
const S2_DN_ATM: u64 = 514_327_527;
const S2_STRIKE_OTM5: u64 = 75_089_390_050_500;
const S2_UP_OTM5: u64 = 236_684_583;
const S2_DN_OTM5: u64 = 762_812_755;
const S2_STRIKE_OTM10: u64 = 78_665_075_291_000;
const S2_UP_OTM10: u64 = 89_445_084;
const S2_DN_OTM10: u64 = 910_052_254;
const S2_STRIKE_ITM5: u64 = 67_938_019_569_500;
const S2_UP_ITM5: u64 = 728_909_489;
const S2_DN_ITM5: u64 = 270_587_848;
const S2_STRIKE_ITM10: u64 = 64_362_334_329_000;
const S2_UP_ITM10: u64 = 873_240_304;
const S2_DN_ITM10: u64 = 126_257_034;
const S3_SPOT: u64 = 71_029_437_950_000;
const S3_FORWARD: u64 = 71_106_779_210_000;
const S3_A: u64 = 1_030_000;
const S3_B: u64 = 32_140_000;
const S3_RHO: u64 = 292_690_000;
const S3_RHO_NEG: u64 = 1;
const S3_M: u64 = 8_550_000;
const S3_M_NEG: u64 = 0;
const S3_SIGMA: u64 = 108_810_000;
const S3_RATE: u64 = 35_000_000;
const S3_EXPIRY_MS: u64 = 1_773_843_002_405;
const S3_NOW_MS: u64 = 1_773_465_371_910;
const S3_STRIKE_ATM: u64 = 71_106_779_210_000;
const S3_UP_ATM: u64 = 486_243_007;
const S3_DN_ATM: u64 = 513_337_969;
const S3_STRIKE_OTM5: u64 = 74_662_118_170_500;
const S3_UP_OTM5: u64 = 220_468_654;
const S3_DN_OTM5: u64 = 779_112_322;
const S3_STRIKE_OTM10: u64 = 78_217_457_131_000;
const S3_UP_OTM10: u64 = 76_836_203;
const S3_DN_OTM10: u64 = 922_744_773;
const S3_STRIKE_ITM5: u64 = 67_551_440_249_500;
const S3_UP_ITM5: u64 = 741_534_891;
const S3_DN_ITM5: u64 = 258_046_085;
const S3_STRIKE_ITM10: u64 = 63_996_101_289_000;
const S3_UP_ITM10: u64 = 885_031_256;
const S3_DN_ITM10: u64 = 114_549_720;
const S4_SPOT: u64 = 71_200_563_760_000;
const S4_FORWARD: u64 = 71_212_555_400_000;
const S4_A: u64 = 1_210_000;
const S4_B: u64 = 30_940_000;
const S4_RHO: u64 = 347_440_000;
const S4_RHO_NEG: u64 = 1;
const S4_M: u64 = 2_090_000;
const S4_M_NEG: u64 = 0;
const S4_SIGMA: u64 = 97_150_000;
const S4_RATE: u64 = 35_000_000;
const S4_EXPIRY_MS: u64 = 1_773_843_002_405;
const S4_NOW_MS: u64 = 1_773_540_800_083;
const S4_STRIKE_ATM: u64 = 71_212_555_400_000;
const S4_UP_ATM: u64 = 486_851_914;
const S4_DN_ATM: u64 = 512_812_744;
const S4_STRIKE_OTM5: u64 = 74_773_183_170_000;
const S4_UP_OTM5: u64 = 212_040_973;
const S4_DN_OTM5: u64 = 787_623_685;
const S4_STRIKE_OTM10: u64 = 78_333_810_940_000;
const S4_UP_OTM10: u64 = 70_185_245;
const S4_DN_OTM10: u64 = 929_479_414;
const S4_STRIKE_ITM5: u64 = 67_651_927_630_000;
const S4_UP_ITM5: u64 = 749_681_936;
const S4_DN_ITM5: u64 = 249_982_723;
const S4_STRIKE_ITM10: u64 = 64_091_299_860_000;
const S4_UP_ITM10: u64 = 890_711_928;
const S4_DN_ITM10: u64 = 108_952_730;
const S5_SPOT: u64 = 72_746_678_060_000;
const S5_FORWARD: u64 = 72_742_173_970_000;
const S5_A: u64 = 1_820_000;
const S5_B: u64 = 25_690_000;
const S5_RHO: u64 = 600_260_000;
const S5_RHO_NEG: u64 = 1;
const S5_M: u64 = 29_960_000;
const S5_M_NEG: u64 = 1;
const S5_SIGMA: u64 = 85_100_000;
const S5_RATE: u64 = 35_000_000;
const S5_EXPIRY_MS: u64 = 1_773_843_002_405;
const S5_NOW_MS: u64 = 1_773_616_191_325;
const S5_STRIKE_ATM: u64 = 72_742_173_970_000;
const S5_UP_ATM: u64 = 487_785_531;
const S5_DN_ATM: u64 = 511_962_775;
const S5_STRIKE_OTM5: u64 = 76_379_282_668_500;
const S5_UP_OTM5: u64 = 199_037_556;
const S5_DN_OTM5: u64 = 800_710_750;
const S5_STRIKE_OTM10: u64 = 80_016_391_367_000;
const S5_UP_OTM10: u64 = 56_901_325;
const S5_DN_OTM10: u64 = 942_846_981;
const S5_STRIKE_ITM5: u64 = 69_105_065_271_500;
const S5_UP_ITM5: u64 = 770_110_330;
const S5_DN_ITM5: u64 = 229_637_976;
const S5_STRIKE_ITM10: u64 = 65_467_956_573_000;
const S5_UP_ITM10: u64 = 908_478_756;
const S5_DN_ITM10: u64 = 91_269_550;
const S6_SPOT: u64 = 73_967_402_550_000;
const S6_FORWARD: u64 = 73_975_419_760_000;
const S6_A: u64 = 780_000;
const S6_B: u64 = 26_540_000;
const S6_RHO: u64 = 365_990_000;
const S6_RHO_NEG: u64 = 1;
const S6_M: u64 = 2_370_000;
const S6_M_NEG: u64 = 1;
const S6_SIGMA: u64 = 76_190_000;
const S6_RATE: u64 = 35_000_000;
const S6_EXPIRY_MS: u64 = 1_773_843_002_405;
const S6_NOW_MS: u64 = 1_773_691_666_510;
const S6_STRIKE_ATM: u64 = 73_975_419_760_000;
const S6_UP_ATM: u64 = 489_401_679;
const S6_DN_ATM: u64 = 510_430_375;
const S6_STRIKE_OTM5: u64 = 77_674_190_748_000;
const S6_UP_OTM5: u64 = 168_046_789;
const S6_DN_OTM5: u64 = 831_785_265;
const S6_STRIKE_OTM10: u64 = 81_372_961_736_000;
const S6_UP_OTM10: u64 = 41_405_180;
const S6_DN_OTM10: u64 = 958_426_874;
const S6_STRIKE_ITM5: u64 = 70_276_648_772_000;
const S6_UP_ITM5: u64 = 793_133_916;
const S6_DN_ITM5: u64 = 206_698_138;
const S6_STRIKE_ITM10: u64 = 66_577_877_784_000;
const S6_UP_ITM10: u64 = 923_178_982;
const S6_DN_ITM10: u64 = 76_653_072;
const S7_SPOT: u64 = 74_169_033_570_000;
const S7_FORWARD: u64 = 74_181_404_030_000;
const S7_A: u64 = 350_000;
const S7_B: u64 = 23_720_000;
const S7_RHO: u64 = 205_610_000;
const S7_RHO_NEG: u64 = 1;
const S7_M: u64 = 5_000_000;
const S7_M_NEG: u64 = 0;
const S7_SIGMA: u64 = 65_970_000;
const S7_RATE: u64 = 35_000_000;
const S7_EXPIRY_MS: u64 = 1_773_843_002_405;
const S7_NOW_MS: u64 = 1_773_767_267_441;
const S7_STRIKE_ATM: u64 = 74_181_404_030_000;
const S7_UP_ATM: u64 = 491_165_300;
const S7_DN_ATM: u64 = 508_750_648;
const S7_STRIKE_OTM5: u64 = 77_890_474_231_500;
const S7_UP_OTM5: u64 = 133_604_249;
const S7_DN_OTM5: u64 = 866_311_700;
const S7_STRIKE_OTM10: u64 = 81_599_544_433_000;
const S7_UP_OTM10: u64 = 28_182_232;
const S7_DN_OTM10: u64 = 971_733_717;
const S7_STRIKE_ITM5: u64 = 70_472_333_828_500;
const S7_UP_ITM5: u64 = 832_563_225;
const S7_DN_ITM5: u64 = 167_352_724;
const S7_STRIKE_ITM10: u64 = 66_763_263_627_000;
const S7_UP_ITM10: u64 = 950_200_210;
const S7_DN_ITM10: u64 = 49_715_738;
const S8_SPOT: u64 = 72_173_265_630_000;
const S8_FORWARD: u64 = 72_173_794_960_000;
const S8_A: u64 = 580_000;
const S8_B: u64 = 16_960_000;
const S8_RHO: u64 = 467_690_000;
const S8_RHO_NEG: u64 = 1;
const S8_M: u64 = 6_060_000;
const S8_M_NEG: u64 = 1;
const S8_SIGMA: u64 = 62_460_000;
const S8_RATE: u64 = 35_000_000;
const S8_EXPIRY_MS: u64 = 1_773_843_002_405;
const S8_NOW_MS: u64 = 1_773_842_694_166;
const S8_STRIKE_ATM: u64 = 72_173_794_960_000;
const S8_UP_ATM: u64 = 492_030_927;
const S8_DN_ATM: u64 = 507_968_730;
const S8_STRIKE_OTM5: u64 = 75_782_484_708_000;
const S8_UP_OTM5: u64 = 104_358_699;
const S8_DN_OTM5: u64 = 895_640_958;
const S8_STRIKE_OTM10: u64 = 79_391_174_456_000;
const S8_UP_OTM10: u64 = 11_585_792;
const S8_DN_OTM10: u64 = 988_413_865;
const S8_STRIKE_ITM5: u64 = 68_565_105_212_000;
const S8_UP_ITM5: u64 = 855_073_509;
const S8_DN_ITM5: u64 = 144_926_148;
const S8_STRIKE_ITM10: u64 = 64_956_415_464_000;
const S8_UP_ITM10: u64 = 963_225_742;
const S8_DN_ITM10: u64 = 36_773_915;

fun create_scenario_oracle(
    spot: u64,
    forward: u64,
    a: u64,
    b: u64,
    rho: u64,
    rho_neg: bool,
    m: u64,
    m_neg: bool,
    sigma: u64,
    rate: u64,
    expiry_ms: u64,
    now_ms: u64,
    ctx: &mut TxContext,
): (oracle::OracleSVI, sui::clock::Clock) {
    let svi = new_svi_params(a, b, rho, rho_neg, m, m_neg, sigma);
    let prices = new_price_data(spot, forward);
    let oracle = oracle::create_test_oracle(
        b"BTC".to_string(),
        svi,
        prices,
        rate,
        expiry_ms,
        now_ms,
        ctx,
    );
    let mut clock = clock::create_for_testing(ctx);
    clock.set_for_testing(now_ms);
    (oracle, clock)
}

#[test]
fun scenario_0_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S0_SPOT,
        S0_FORWARD,
        S0_A,
        S0_B,
        S0_RHO,
        S0_RHO_NEG == 1,
        S0_M,
        S0_M_NEG == 1,
        S0_SIGMA,
        S0_RATE,
        S0_EXPIRY_MS,
        S0_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ATM, true, &clock), S0_UP_ATM);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ATM, false, &clock), S0_DN_ATM);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_OTM5, true, &clock), S0_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_OTM5, false, &clock), S0_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_OTM10, true, &clock), S0_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_OTM10, false, &clock), S0_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ITM5, true, &clock), S0_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ITM5, false, &clock), S0_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ITM10, true, &clock), S0_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S0_STRIKE_ITM10, false, &clock), S0_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_1_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S1_SPOT,
        S1_FORWARD,
        S1_A,
        S1_B,
        S1_RHO,
        S1_RHO_NEG == 1,
        S1_M,
        S1_M_NEG == 1,
        S1_SIGMA,
        S1_RATE,
        S1_EXPIRY_MS,
        S1_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ATM, true, &clock), S1_UP_ATM);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ATM, false, &clock), S1_DN_ATM);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_OTM5, true, &clock), S1_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_OTM5, false, &clock), S1_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_OTM10, true, &clock), S1_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_OTM10, false, &clock), S1_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ITM5, true, &clock), S1_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ITM5, false, &clock), S1_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ITM10, true, &clock), S1_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S1_STRIKE_ITM10, false, &clock), S1_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_2_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S2_SPOT,
        S2_FORWARD,
        S2_A,
        S2_B,
        S2_RHO,
        S2_RHO_NEG == 1,
        S2_M,
        S2_M_NEG == 1,
        S2_SIGMA,
        S2_RATE,
        S2_EXPIRY_MS,
        S2_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ATM, true, &clock), S2_UP_ATM);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ATM, false, &clock), S2_DN_ATM);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_OTM5, true, &clock), S2_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_OTM5, false, &clock), S2_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_OTM10, true, &clock), S2_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_OTM10, false, &clock), S2_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ITM5, true, &clock), S2_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ITM5, false, &clock), S2_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ITM10, true, &clock), S2_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S2_STRIKE_ITM10, false, &clock), S2_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_3_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S3_SPOT,
        S3_FORWARD,
        S3_A,
        S3_B,
        S3_RHO,
        S3_RHO_NEG == 1,
        S3_M,
        S3_M_NEG == 1,
        S3_SIGMA,
        S3_RATE,
        S3_EXPIRY_MS,
        S3_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ATM, true, &clock), S3_UP_ATM);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ATM, false, &clock), S3_DN_ATM);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_OTM5, true, &clock), S3_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_OTM5, false, &clock), S3_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_OTM10, true, &clock), S3_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_OTM10, false, &clock), S3_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ITM5, true, &clock), S3_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ITM5, false, &clock), S3_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ITM10, true, &clock), S3_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S3_STRIKE_ITM10, false, &clock), S3_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_4_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S4_SPOT,
        S4_FORWARD,
        S4_A,
        S4_B,
        S4_RHO,
        S4_RHO_NEG == 1,
        S4_M,
        S4_M_NEG == 1,
        S4_SIGMA,
        S4_RATE,
        S4_EXPIRY_MS,
        S4_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ATM, true, &clock), S4_UP_ATM);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ATM, false, &clock), S4_DN_ATM);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_OTM5, true, &clock), S4_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_OTM5, false, &clock), S4_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_OTM10, true, &clock), S4_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_OTM10, false, &clock), S4_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ITM5, true, &clock), S4_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ITM5, false, &clock), S4_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ITM10, true, &clock), S4_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S4_STRIKE_ITM10, false, &clock), S4_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_5_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S5_SPOT,
        S5_FORWARD,
        S5_A,
        S5_B,
        S5_RHO,
        S5_RHO_NEG == 1,
        S5_M,
        S5_M_NEG == 1,
        S5_SIGMA,
        S5_RATE,
        S5_EXPIRY_MS,
        S5_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ATM, true, &clock), S5_UP_ATM);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ATM, false, &clock), S5_DN_ATM);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_OTM5, true, &clock), S5_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_OTM5, false, &clock), S5_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_OTM10, true, &clock), S5_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_OTM10, false, &clock), S5_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ITM5, true, &clock), S5_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ITM5, false, &clock), S5_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ITM10, true, &clock), S5_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S5_STRIKE_ITM10, false, &clock), S5_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_6_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S6_SPOT,
        S6_FORWARD,
        S6_A,
        S6_B,
        S6_RHO,
        S6_RHO_NEG == 1,
        S6_M,
        S6_M_NEG == 1,
        S6_SIGMA,
        S6_RATE,
        S6_EXPIRY_MS,
        S6_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ATM, true, &clock), S6_UP_ATM);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ATM, false, &clock), S6_DN_ATM);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_OTM5, true, &clock), S6_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_OTM5, false, &clock), S6_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_OTM10, true, &clock), S6_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_OTM10, false, &clock), S6_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ITM5, true, &clock), S6_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ITM5, false, &clock), S6_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ITM10, true, &clock), S6_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S6_STRIKE_ITM10, false, &clock), S6_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_7_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S7_SPOT,
        S7_FORWARD,
        S7_A,
        S7_B,
        S7_RHO,
        S7_RHO_NEG == 1,
        S7_M,
        S7_M_NEG == 1,
        S7_SIGMA,
        S7_RATE,
        S7_EXPIRY_MS,
        S7_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ATM, true, &clock), S7_UP_ATM);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ATM, false, &clock), S7_DN_ATM);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_OTM5, true, &clock), S7_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_OTM5, false, &clock), S7_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_OTM10, true, &clock), S7_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_OTM10, false, &clock), S7_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ITM5, true, &clock), S7_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ITM5, false, &clock), S7_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ITM10, true, &clock), S7_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S7_STRIKE_ITM10, false, &clock), S7_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}

#[test]
fun scenario_8_real_world_prices() {
    let ctx = &mut tx_context::dummy();
    let (oracle, clock) = create_scenario_oracle(
        S8_SPOT,
        S8_FORWARD,
        S8_A,
        S8_B,
        S8_RHO,
        S8_RHO_NEG == 1,
        S8_M,
        S8_M_NEG == 1,
        S8_SIGMA,
        S8_RATE,
        S8_EXPIRY_MS,
        S8_NOW_MS,
        ctx,
    );
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ATM, true, &clock), S8_UP_ATM);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ATM, false, &clock), S8_DN_ATM);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_OTM5, true, &clock), S8_UP_OTM5);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_OTM5, false, &clock), S8_DN_OTM5);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_OTM10, true, &clock), S8_UP_OTM10);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_OTM10, false, &clock), S8_DN_OTM10);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ITM5, true, &clock), S8_UP_ITM5);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ITM5, false, &clock), S8_DN_ITM5);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ITM10, true, &clock), S8_UP_ITM10);
    assert_eq!(oracle.get_binary_price(S8_STRIKE_ITM10, false, &clock), S8_DN_ITM10);
    destroy(oracle);
    clock.destroy_for_testing();
}
