// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/reference/generate_pricing_reference.py
// Regenerate: python3 packages/predict/tests/reference/generate_pricing_reference.py
// Check: python3 packages/predict/tests/reference/generate_pricing_reference.py --check
//
// Committed synthetic production-safe inputs; no external-data provenance claim.
// True values use Python stdlib log/sqrt/erf. Tolerances are ex-ante intervals
// propagated from current fixed_math primitive contracts, never Move output.
// Profiles carry distinct Pyth spot, Block Scholes spot, and Block Scholes
// forward inputs; true values use the exact live-selected integer forward.
// Maximum permitted absolute tolerance: 10_000 units
// at 1e9 scale (0.1 basis point), used only as a test-usefulness ceiling.
// Worst generated absolute tolerance: 3_610 units at 1e9 scale.
#[test_only]
module deepbook_predict::pricing_reference_data;

use deepbook_predict::{constants, oracle_profile::{Self, SurfaceProfile}};

const ENoSuchProfile: u64 = 0;

public struct RefPoint has copy, drop {
    lower_tick: u64,
    higher_tick: u64,
    reference: u64,
    tolerance: u64,
}

public fun lower_tick(point: &RefPoint): u64 { point.lower_tick }

public fun higher_tick(point: &RefPoint): u64 { point.higher_tick }

public fun reference(point: &RefPoint): u64 { point.reference }

public fun tolerance(point: &RefPoint): u64 { point.tolerance }

public fun profile_count(): u64 { 3 }

public fun profile(index: u64): SurfaceProfile {
    if (index == 0) {
        // flat_medium_variance
        oracle_profile::new(
            oracle_profile::spot_prices(100_000_000_000, 100_000_000_000, 100_000_000_000),
            oracle_profile::svi_params(10_000_000, false, 0, 200_000_000, 0, false, 0, false),
            119_000,
        )
    } else if (index == 1) {
        // negative_skew_medium_variance
        oracle_profile::new(
            oracle_profile::spot_prices(102_000_000_000, 100_000_000_000, 101_000_000_000),
            oracle_profile::svi_params(
                2_000_000,
                false,
                40_000_000,
                180_000_000,
                350_000_000,
                true,
                15_000_000,
                false,
            ),
            119_001,
        )
    } else if (index == 2) {
        // negative_skew_small_variance
        oracle_profile::new(
            oracle_profile::spot_prices(100_000_000_000, 100_000_000_000, 100_000_000_000),
            oracle_profile::svi_params(
                80_000,
                false,
                4_000_000,
                8_000_000,
                250_000_000,
                true,
                5_000_000,
                true,
            ),
            119_002,
        )
    } else {
        abort ENoSuchProfile
    }
}

public fun points(index: u64): vector<RefPoint> {
    if (index == 0) {
        // flat_medium_variance
        vector[
            point(80, constants::pos_inf_tick!(), 985_424_390, 33),
            point(90, constants::pos_inf_tick!(), 842_215_516, 55),
            point(100, constants::pos_inf_tick!(), 480_061_194, 31),
            point(110, constants::pos_inf_tick!(), 157_905_874, 52),
            point(120, constants::pos_inf_tick!(), 30_519_312, 38),
            point(0, 100, 519_938_806, 31),
            point(90, 110, 684_309_642, 105),
        ]
    } else if (index == 1) {
        // negative_skew_medium_variance
        vector[
            point(85, constants::pos_inf_tick!(), 952_221_868, 83),
            point(95, constants::pos_inf_tick!(), 806_365_042, 92),
            point(101, constants::pos_inf_tick!(), 602_703_224, 61),
            point(107, constants::pos_inf_tick!(), 344_075_056, 64),
            point(117, constants::pos_inf_tick!(), 75_783_156, 75),
            point(0, 101, 397_296_776, 61),
            point(95, 107, 462_289_986, 153),
        ]
    } else if (index == 2) {
        // negative_skew_small_variance
        vector[
            point(97, constants::pos_inf_tick!(), 988_927_622, 356),
            point(99, constants::pos_inf_tick!(), 853_812_809, 2_074),
            point(100, constants::pos_inf_tick!(), 476_841_431, 693),
            point(101, constants::pos_inf_tick!(), 162_455_470, 1_538),
            point(103, constants::pos_inf_tick!(), 11_097_931, 321),
            point(0, 100, 523_158_569, 693),
            point(99, 101, 691_357_339, 3_610),
        ]
    } else {
        abort ENoSuchProfile
    }
}

fun point(lower_tick: u64, higher_tick: u64, reference: u64, tolerance: u64): RefPoint {
    RefPoint { lower_tick, higher_tick, reference, tolerance }
}
