// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0
//
// @generated by packages/predict/tests/reference/generate_pricing_reference.py
// Regenerate: python3 packages/predict/tests/reference/generate_pricing_reference.py
// Check: python3 packages/predict/tests/reference/generate_pricing_reference.py --check
//
// Committed synthetic production-safe inputs; no external-data provenance claim.
// True values use Python stdlib log/sqrt/erf. Tolerances are ex-ante intervals
// propagated from current fixed_math primitive contracts, never Move output.
// Pyth spot equals BS spot, so current mul_div_down reanchoring returns each
// configured forward exactly.
// Maximum permitted absolute tolerance: 10_000 units
// at 1e9 scale (0.1 basis point of payout probability).
// Worst generated absolute tolerance: 3_610 units at 1e9 scale.
#[test_only]
module deepbook_predict::pricing_reference_data;

use deepbook_predict::{constants, oracle_profile::{Self, SurfaceProfile}};

const ENoSuchProfile: u64 = 0;

public struct RefPoint has copy, drop {
    lower: u64,
    higher: u64,
    reference: u64,
    tolerance: u64,
}

public fun lower(point: &RefPoint): u64 { point.lower }

public fun higher(point: &RefPoint): u64 { point.higher }

public fun reference(point: &RefPoint): u64 { point.reference }

public fun tolerance(point: &RefPoint): u64 { point.tolerance }

public fun profile_count(): u64 { 3 }

public fun profile(index: u64): SurfaceProfile {
    if (index == 0) {
        // flat_medium_variance
        oracle_profile::new(
            100_000_000_000,
            100_000_000_000,
            10_000_000,
            false,
            0,
            200_000_000,
            0,
            false,
            0,
            false,
            119_000,
        )
    } else if (index == 1) {
        // negative_skew_medium_variance
        oracle_profile::new(
            100_000_000_000,
            101_000_000_000,
            2_000_000,
            false,
            40_000_000,
            180_000_000,
            350_000_000,
            true,
            15_000_000,
            false,
            119_001,
        )
    } else if (index == 2) {
        // negative_skew_small_variance
        oracle_profile::new(
            100_000_000_000,
            100_000_000_000,
            80_000,
            false,
            4_000_000,
            8_000_000,
            250_000_000,
            true,
            5_000_000,
            true,
            119_002,
        )
    } else {
        abort ENoSuchProfile
    }
}

public fun points(index: u64): vector<RefPoint> {
    if (index == 0) {
        // flat_medium_variance
        vector[
            point(80_000_000_000, constants::pos_inf!(), 985_424_390, 33),
            point(90_000_000_000, constants::pos_inf!(), 842_215_516, 55),
            point(100_000_000_000, constants::pos_inf!(), 480_061_194, 31),
            point(110_000_000_000, constants::pos_inf!(), 157_905_874, 52),
            point(120_000_000_000, constants::pos_inf!(), 30_519_312, 38),
            point(0, 100_000_000_000, 519_938_806, 31),
            point(90_000_000_000, 110_000_000_000, 684_309_642, 105),
        ]
    } else if (index == 1) {
        // negative_skew_medium_variance
        vector[
            point(85_000_000_000, constants::pos_inf!(), 939_036_848, 87),
            point(95_000_000_000, constants::pos_inf!(), 752_654_404, 84),
            point(101_000_000_000, constants::pos_inf!(), 516_161_933, 42),
            point(107_000_000_000, constants::pos_inf!(), 262_119_891, 72),
            point(117_000_000_000, constants::pos_inf!(), 50_122_208, 70),
            point(0, 101_000_000_000, 483_838_067, 42),
            point(95_000_000_000, 107_000_000_000, 490_534_513, 154),
        ]
    } else if (index == 2) {
        // negative_skew_small_variance
        vector[
            point(97_000_000_000, constants::pos_inf!(), 988_927_622, 356),
            point(99_000_000_000, constants::pos_inf!(), 853_812_809, 2_074),
            point(100_000_000_000, constants::pos_inf!(), 476_841_431, 693),
            point(101_000_000_000, constants::pos_inf!(), 162_455_470, 1_538),
            point(103_000_000_000, constants::pos_inf!(), 11_097_931, 321),
            point(0, 100_000_000_000, 523_158_569, 693),
            point(99_000_000_000, 101_000_000_000, 691_357_339, 3_610),
        ]
    } else {
        abort ENoSuchProfile
    }
}

fun point(lower: u64, higher: u64, reference: u64, tolerance: u64): RefPoint {
    RefPoint { lower, higher, reference, tolerance }
}
